<?php
  $displayOrderTable=Mage::getStoreConfig('tab1/order_information_system/display_order_table');
  $displayProductImage=Mage::getStoreConfig('tab1/order_information_system/display_product_image');
  $displayDiscount=Mage::getStoreConfig('tab1/order_information_system/display_discount');
  $displayShippingRate=Mage::getStoreConfig('tab1/order_information_system/display_shipping_rates');
  $displayTax=Mage::getStoreConfig('tab1/order_information_system/display_tax');
  $displayCmsBlockAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_above');
  $cmsBlockIdAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_above');
  $displayCmsBlockBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_below');
  $cmsBlockIdBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_below');
  $newsLetter=Mage::getStoreConfig('tab1/newsletter_subscription_section/display_section');

  $_coreHelper = $this->helper('core');

  $displayOrderTable=Mage::getStoreConfig('tab1/order_information_system/display_order_table');
  $displayProductImage=Mage::getStoreConfig('tab1/order_information_system/display_product_image');
  $displayDiscount=Mage::getStoreConfig('tab1/order_information_system/display_discount');
  $displayShippingRate=Mage::getStoreConfig('tab1/order_information_system/display_shipping_rates');
  $displayTax=Mage::getStoreConfig('tab1/order_information_system/display_tax');
  $displayCmsBlockAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_above');
  $cmsBlockIdAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_above');
  $displayCmsBlockBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_below');
  $cmsBlockIdBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_below');
  $newsLetter=Mage::getStoreConfig('tab1/newsletter_subscription_section/display_section');

  $_coreHelper = $this->helper('core');

    if($this->getOrderId()):
      $orderObj = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
      $lastOrder = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId());
      $billingAddress = $lastOrder->getBillingAddress();
      $shippingAddress = $lastOrder->getShippingAddress();
      $payment_method = $lastOrder->getPayment()->getMethodInstance()->getTitle();
      $payment_method_code = $lastOrder->getPayment()->getMethodInstance()->getCode();
?>

<div class="thanks-outer" id="thanks-order-page">
  <?php if($this->getTopBlock()!=false): ?>
  <?php if($displayCmsBlockAbove==1): ?>
  <div class="order-cms-block block1">
    <?php
      echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getTopBlock())->toHTML();
    ?>
  </div>
  <?php
     endif;
  endif;
?>
  <div class="thanks-inner">
    <div class="page-title thank">
      <h1><?php echo $this->__('Thank you for your order!') ?></h1>
    </div>
    <?php
    echo $this->getMessagesBlock()->getGroupedHtml() 
?>
    <div class="thanks-msz">
      <?php if($payment_method_code == 'phoenix_cashondelivery'){?>
      <h3>We will call you shortly!</h3>
      <p>Our team will call you within 24hrs for order confirmation.<br/>
        Your COD order will be processed after the confirmation call.</p>
      <?php }else{?>
      <h3>We will dispatch your order shortly !</h3>
      <p>A confirmation email has been sent to <a href="mailto:<?php echo $billingAddress["email"]?>"><?php echo $billingAddress["email"]?></a></p>
      <?php }?>
    </div>
    <div class="thkbox">
      <?php /*?><div class="thk-box1">
        <div class="outer-box">
          <h3><?php echo $this->__('Thank you for your order!') ?></h3>
          <div class="inner-box-1">
            <?php if($this->getOrderId()): ?>
            <?php if($this->getCanViewOrder()): ?>
            <?php  else: ?>
            <?php endif; ?>
            <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
            <?php if($this->getCanViewOrder() && $this->getCanPrintOrder()): ?>
            <?php echo $this->getChildHtml() ?>
            <?php endif; ?>
            <?php endif; ?>
            <a class="button btn-continue btn-inline" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>" title="<?php echo $this->__('Continue Shopping') ?>" ><span><span><?php echo $this->__('Continue Shopping') ?></span></span></a> </div>
        </div>
      </div><?php */?>
      <div class="section-title-big">
        <h2><?php echo $this->__('Order Summary') ?></h2  >
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="section-title">
            <h3><?php echo $this->__('Shipping Address') ?></h3>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
          <div class="inner-box-1">
            <table class="table">
              <tr>
                <td><h3>
        <?php 
        $country_name=Mage::app()->getLocale()->getCountryTranslation($shippingAddress['country_id']);        
        echo $shippingAddress['prefix'].' '.$shippingAddress['firstname'].' '.$shippingAddress['lastname'];
    ?>
                  </h3></td>
              </tr>
              <tr>
              <tr>
                <td><?php echo $shippingAddress['street']; ?>,<br/>
                  <?php echo $shippingAddress['city']; ?> - <?php echo $shippingAddress['postcode']; ?> (<?php echo $shippingAddress['region']; ?>) <?php echo $country_name; ?><br/>
                  <span style="width:62px;display:inline-block;">Mobile</span>: <?php echo $shippingAddress['telephone']; ?><br/>
                  <span style="width:62px;display:inline-block;">Email</span>: <?php echo $shippingAddress['email']; ?></td>
              </tr>
              <?php /*?>
<tr>
  <td><?php echo $shippingAddress['region']; ?>, Country - <?php echo $shippingAddress['country_id']; ?> </td>
</tr>
<?php */?>
              <?php endif; ?>
            </table>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="inner-box-1 order-table">
            <?php /*?><?php if($this->getOrderId()): ?>
            <?php echo $this->__('<a href="%s" onclick="this.target=\'_blank\'" class="button print-icon" title="Print Details">Print Details</a>', $this->getPrintUrl()) ?> <?php echo $this->getChildHtml() ?>
            <?php endif; ?><?php */?>
            <?php //******************************Order Summary *********************** ?>
            <table class="table">
              <?php
        if($this->getOrderId()):
          $orderObj = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
          $lastOrder = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId());
          $billingAddress = $lastOrder->getBillingAddress();
          $shippingAddress = $lastOrder->getShippingAddress();
          ?>
              <tr >
                <td><label><strong><?php echo $this->__('Date') ?></strong></label></td>
                <td><span class="sep">:</span></td>
                <td align="left"><span><?php echo $orderObj->getCreatedAtStoreDate(); ?></span></td>
              </tr>
              <tr>
                <td><label><strong><?php echo $this->__('Order Id') ?></strong></label></td>
                <td><span class="sep">:</span></td>
                <td align="left"><span>
                  <?php if($this->getCanViewOrder()): ?>
                  <?php echo $this->__(sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?>
                  <?php else: ?>
                  <?php echo $this->__($this->escapeHtml($this->getOrderId())) ?>
                  <?php endif; ?>
                  <?php echo $this->getChildHtml() ?> </span></td>
              </tr>
              <tr>
                <td><label><strong><?php echo $this->__('Order Amount') ?></strong></label></td>
                <td><span class="sep">:</span></td>
                <td align="left"><span><?php echo $_coreHelper->formatPrice($orderObj->getGrandTotal(),true) ?></span></td>
              </tr>
              <tr>
                <td><label><strong><?php echo $this->__('Payment Method') ?></strong></label></td>
                <td><span class="sep">:</span></td>
                <td align="left"><span><?php echo $payment_method ?></span></td>
              </tr>
              <?php endif; ?>
            </table>
          </div>
        </div>
      </div>
      <div class="clear"></div>
      <?php /*?><?php if($this->getOrderId()): ?>
      <?php echo $this->__('<a href="%s" onclick="this.target=\'_blank\'" class="btn btn-danger" title="Print Details">Print Details</a>', $this->getPrintUrl()) ?> <?php echo $this->getChildHtml() ?>
      <?php endif; ?>
      <div class="clear"></div><?php */?>
    </div>
    <?php 
//**********************************Order Details***************************
if($displayOrderTable==1):
  if($this->getOrderId()):
    $orderItems = $orderObj->getAllVisibleItems();
    ?>
    <div class="row">
      <div class="col-sm-12">
        <div class="section-title ">
          <h3 class="pull-left"><?php echo $this->__('Item Details') ?></h3>
          <h3 class="pull-right"><?php echo $this->__('Sub Total') ?></h3>
          <div class="clearfix"></div>
        </div>
        <?php foreach($orderItems as $items)
    {
      $_product = Mage::getModel('catalog/product')->load($items->getProductId());
      $product_small_image_path = Mage::helper('catalog/image')->init($_product,'small_image')->resize(75);
      
	  
	  $itemsInfoArray = $items->getData();
	  
	  $blank_backImagePath = '';
	  ///////////////////////////////////////Item front and back image path///////////////////////////////////
 			$folderURL = Mage::helper('function')->graGetFolderUrl($itemsInfoArray["prdUrl"]);
			$folderPath = Mage::helper('function')->graGetFolderPath($itemsInfoArray["prdUrl"]);

		if(is_file($folderPath . DS . 'mask-back.png')){		
			if(!is_file($folderPath . DS . 'resized75' . DS . 'mask-back.png'))
			{
			   $blank_backImagePath = Mage::helper('function')->resizeImg('mask-back.png', 75, 75,$folderURL,$folderPath,'resized75');
			}
			else
			{
				$blank_backImagePath = $folderURL . '/' . 'resized75' . '/' . 'mask-back.png';
			}
		}
		elseif(is_file($folderPath . DS . 'mask.png')){
			if(!is_file($folderPath . DS . 'resized75' . DS . 'mask.png'))
			{
			   $blank_backImagePath = Mage::helper('function')->resizeImg('mask.png', 75, 75,$folderURL,$folderPath,'resized75');
			}
			else
			{
				$blank_backImagePath = $folderURL . '/' . 'resized75' . '/' . 'mask.png';
			}
		}
      /////////////////////////////////////////////////////////////////////////////////////////////////////////
      
    ?>
        <table class="table">
          <tr>
            <td colspan="2" ><?php if($displayProductImage==1): ?>
              <span class="product-image-success">
	<?php
	if($blank_backImagePath != '')
	{?>
      <a href="<?php echo $itemsInfoArray["prdfullUrl"]?>"><img src="<?php echo $blank_backImagePath;?>" width="75" height="75" style="position:absolute"></a>
    <?php } ?>


			  <img src="<?php echo $product_small_image_path ?>" width="75" height="75" align="<?php echo $items->getName(); ?>"/> </span>
              <?php endif; ?>
              <div class="product-name"> 
				<a href="<?php echo $itemsInfoArray["prdfullUrl"]?>" id="<?php echo $items->getProductId();?>">
					<?php echo $items->getName(); ?>
				</a>
        
<?php $opts = $items->getProductOptions();
              
              /*echo '<pre>';
              print_r($opts);*/
              echo '<br/>';
              foreach($opts['options'] as $optsVal)
              {
                if(trim($optsVal['label']) == 'Product Detail')
                {
                  $explodeArray = explode('/',$optsVal['value']);
                  $category = Mage::getModel('catalog/category')->load($explodeArray[count($explodeArray)-1]);
                  $urlPath = Mage::helper('function')->getUrlPath($_product, $category);
/*				  
?>                  
<script type="text/javascript">
jQuery('#<?php echo $items->getProductId();?>').attr('href','<?php echo $urlPath;?>');
</script>                 
<?php
*/
                  continue;
                } 
                echo '<span class="fontSize11px fontStyleItalic"><strong>'.$optsVal['label'].': </strong></span><span class="fontSize11px fontStyleItalic fontStyleNormal">'.$optsVal['value'].'</span><br/>';                
              }
              foreach($opts['attributes_info'] as $optsVal)
              {
                if(trim($optsVal['label']) == 'Product Detail')
                {
                  $explodeArray = explode('/',$optsVal['value']);
                  $category = Mage::getModel('catalog/category')->load($explodeArray[count($explodeArray)-1]);
                  $urlPath = Mage::helper('function')->getUrlPath($_product, $category);
/*				  
?>                  
<script type="text/javascript">
jQuery('#<?php echo $items->getProductId();?>').attr('href','<?php echo $urlPath;?>');
</script>                 
<?php
*/
                  continue;
                } 
                echo '<span class="fontSize11px fontStyleItalic"><strong>'.$optsVal['label'].': </strong></span><span class="fontSize11px fontStyleItalic fontStyleNormal">'.$optsVal['value'].'</span><br/>';                
              }
              ?>        
        
        </div>
              <div>Quantity. <?php echo (int)$items->getQtyOrdered()?>&nbsp;&nbsp;&nbsp;&nbsp; Price : <?php echo $_coreHelper->formatPrice($items->getPrice());?></div></td>
            <td class="qty-item textAlignRight"><?php /*?><?php echo number_format($items->getQtyOrdered(),0); ?> <span class="xx">x</span> <?php echo $_coreHelper->formatPrice($items->getPrice(),true) ?>  = <?php */?>
              <?php $totalprice = ($items->getQtyOrdered())*($items->getPrice()); ?>
              <span class="alt-bg"><?php echo $_coreHelper->formatPrice($totalprice,true) ?></span></td>
          </tr>
        </table>
        <?php
            } 
          ?>
      </div>
      <div class="col-sm-6 floatRightCss">
        <?php /*?><div class="section-title text-danger text-right"><h3><?php echo $this->__('Sub Total') ?></h3></div><?php */?>
        <div class="section-title text-danger text-right">
          <h3>&nbsp;</h3>
        </div>
        <table class="table">
          <tr>
            <td width="100%" class="a-right" ><span ><?php echo $this->__('Cart Total') ?></span></td>
            <td class="a-left"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getSubtotal(),true) ?> </span></td>
          </tr>
          <?php //echo '<pre>'; print_r($orderObj); echo '</pre>'; 
      
      ?>
          <?php if($displayDiscount==1): ?>
          <?php if($orderObj->getDiscountAmount() != 0): ?>
          <tr class="discount">
            <td class="a-right"  ><?php echo $this->__('Coupon Discount').'('.$orderObj->getDiscountDescription().')' ?></td>
            <td class="last a-left"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getDiscountAmount(),true) ?> </span></td>
          </tr>
          <?php 
              endif; 
            endif; 
          ?>
          <?php if($displayShippingRate==1): ?>
          <tr class="shipping">
            <td class="a-right"  ><?php echo $this->__('Shipping Charges'); ?></td>
            <td class="last a-left"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getShippingInclTax(),true) ?> </span></td>
          </tr>
          <?php 
            endif; 
          ?>
          <?php if($displayTax==1): ?>
          <?php if($orderObj->getTaxAmount() != 0): ?>
          <tr class="tax">
            <td class="a-right"  ><?php echo $this->__('Tax')?></td>
            <td class="last a-left"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getTaxAmount(),true) ?> </span></td>
          </tr>
          <?php 
              endif;
            endif;
          ?>
          <?php if($payment_method_code == 'phoenix_cashondelivery'){?>
          
          <tr class="tax">
            <td class="a-right"  ><?php echo $this->__('Cash on Delivery Charge')?></td>
            <td class="last a-left"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getCodFee(),true) ?> </span></td>
          </tr>
          <?php } ?>
          <tr class="grand_total ">
            <td class="a-right"  ><label><strong><?php echo $this->__('Order Total') ?></strong></label></td>
            <td class="last a-left"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getGrandTotal(),true); ?></span></td>
          </tr>
        </table>
      </div>
    </div>
    <?php endif; 
endif;
?>
  </div>
  <?php if($this->getBottomBlock()!=false): ?>
  <?php if($displayCmsBlockBelow==1): ?>
  <div class="order-cms-block block_2"> <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getBottomBlock())->toHTML(); ?> </div>
  <?php
  endif;
endif;
?>
  <?php if($newsLetter==1): ?>
  <div class="order-newsletter"> <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?> </div>
  <?php 
  endif;
?>
</div>
<?php
Mage::getSingleton('core/session')->unsEmailID();
// code for t-shirt api
$read = Mage::getSingleton( 'core/resource' )->getConnection( 'core_read' );
$write = Mage::getSingleton( 'core/resource' )->getConnection( 'core_write' );

$orderIncrementId = $this->getOrderId();
$order = Mage::getModel('sales/order')->loadByIncrementId($orderIncrementId);
$order_id = $order->getEntity_id();
$payment_method = $order->getPayment()->getMethodInstance()->getTitle();
if($payment_method != 'Cash on Delivery')
{
  $payment_method = 'Prepaid';
  $orderItem = $read->query("SELECT `item_id` FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `product_type` = 'configurable'");
  $allOrderItem = $orderItem->fetch();
  $item_id = $allOrderItem['item_id'];
  $total_style_code = array();
  if($item_id != '')
  {
    // Shipping Address Data
    $shipping_address = $order->getShippingAddress();
    $shipping_data = $shipping_address->getData();
    $spostcode = $shipping_data['postcode'];
    $saddress1 = $shipping_data['street'];
    $scity = $shipping_data['city'];
    $sstate = $shipping_data['region'];
    $stelephone = $shipping_data['telephone'];
    $scountry_id = $shipping_data['country_id'];
    $countryModel = Mage::getModel('directory/country')->loadByCode($scountry_id);
    $scountryName = $countryModel->getName();
    
    // Billing Address Data
    $billing_address = $order->getBillingAddress();
    $billing_data = $billing_address->getData();
    $bpostcode = $billing_data['postcode'];
    $bsaddress1 = $billing_data['street'];
    $bcity = $billing_data['city'];
    $bstate = $shipping_data['region'];
    $btelephone = $billing_data['telephone'];
    $bcountry_id = $billing_data['country_id'];
    $countryModel = Mage::getModel('directory/country')->loadByCode($bcountry_id);
    $bcountryName = $countryModel->getName();
     
    if($order->canInvoice() and $order->getIncrementId())
    {
      $items = array();
      foreach ($order->getAllItems() as $item1) 
      {
      $items[$item1->getId()] = $item1->getQtyOrdered();
      }
      //public function create($orderIncrementId, $itemsQty, $comment = null, $email = false, $includeComment = false)
      $invoiceId = Mage::getModel('sales/order_invoice_api')->create($order->getIncrementId(),$items,null,false,true);
      //$invoice = Mage::getModel('sales/order_invoice_api')->capture($invoiceId);
    }
    
    if ($order->hasInvoices()) {
      foreach ($order->getInvoiceCollection() as $inv) {
      $invIncrementIDs = $inv->getIncrementId();
      $inv_total = round($inv->getGrandTotal());
      } 
    }
    
    $order_date = $order->getCreatedAt();
    $order_qty = $order->getTotalQtyOrdered();
    $subtotal = $order->getSubtotal();
    //$grandtotal = $order->getGrandTotal();    
    $customer_id = $order->getCustomerId();
    $base_currency_code = $order->getBaseCurrencyCode();
    $bill_id = $order->getBillingAddressId();
    $ship_id = $order->getShippingAddressId();
    $email = $order->getCustomerEmail();
    $title = $order->getCustomerPrefix();
    $fname = $order->getCustomerFirstname();
    $lname = $order->getCustomerLastname();
    $shipping_amount = $order->getShippingAmount();
    $discount = $order->getDiscountAmount();
    $coupon = $order->getCouponCode();
    $ship_method = $order->getShippingMethod();
    
    $xml = new SimpleXMLElement("<?xml version=\"1.0\" encoding=\"utf-8\"?><order></order>");
    $xml->addChild('order_id', $order_id);
    $xml->addChild('order_date', $order_date);
    $customer_details = $xml->addChild('customer_details');
    $customer_details->addChild('title', $title);
    $customer_details->addChild('first_name', $fname);
    $customer_details->addChild('last_name', $lname);
    $customer_details->addChild('email', $email);
    $shipping_address = $xml->addChild('shipping_address');
    $shipping_address->addChild('title', $title);
    $shipping_address->addChild('first_name', $fname);
    $shipping_address->addChild('last_name', $fname);
    $shipping_address->addChild('address_line1', $saddress1);
    $shipping_address->addChild('address_line2', $saddress1);
    $shipping_address->addChild('country', $scountryName);
    $shipping_address->addChild('city', $scity);
    $shipping_address->addChild('state', $sstate);
    $shipping_address->addChild('pincode', $spostcode);
    $shipping_address->addChild('mobile', $stelephone);
    $xml->addChild('self_shipping', 'no');
    $billing_address = $xml->addChild('billing_address');
    $billing_address->addChild('title', $title);
    $billing_address->addChild('first_name', $fname);
    $billing_address->addChild('last_name', $fname);
    $billing_address->addChild('address_line1', $saddress1);
    $billing_address->addChild('address_line2', $saddress1);
    $billing_address->addChild('country', $bcountryName);
    $billing_address->addChild('city', $scity);
    $billing_address->addChild('state', $bstate);
    $billing_address->addChild('pincode', $bpostcode);
    $billing_address->addChild('mobile', $stelephone);
    $invoice = $xml->addChild('invoice');
    $invoice->addChild('invoice_number', $invIncrementIDs);
    $invoice->addChild('invoice_value', $inv_total);
    $invoice->addChild('tax_percentage', 0);
    $invoice->addChild('tax_value', 0);  
    $invoice->addChild('payment_mode', $payment_method);
    $invoice->addChild('special_instruction', 'Test');
    $invoice->addChild('discount', round($discount));
    $invoice->addChild('shipping_charges', round($shipping_amount));
    $invoice->addChild('order_comment', 'Test');
    $invoice->addChild('voucher_text', 'Test');
    $invoice->addChild('voucher_value', '123');
    $invoice->addChild('cod_convenience_fee', '50');
    $invoice->addChild('currency', $base_currency_code);
    $courier = $xml->addChild('courier');
    $courier->addChild('courier_name', 'Delhivery COD');
    $courier->addChild('docket_number', '11');
    $products = $xml->addChild('products');
    
    $orderItem = $read->query("SELECT `item_id`, `product_id`, `price`, `row_total` FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `product_type` = 'configurable'");
    $allOrderItem = $orderItem->fetchAll();
    for($i=0;$i<count($allOrderItem);$i++)
    { 
      //print_r($allOrderItem);
      $configProductid = $allOrderItem[$i]['product_id'];
      $configProduct = Mage::getModel('catalog/product')->load($configProductid);  
      $ids = $configProduct->getCategoryIds();
      $categoryId = (isset($ids[0]) ? $ids[0] : $ids[1]);
      $style_code = $configProduct['style_code'];
      $design_code = $configProduct['design_code'];

      $getSimple = $read->query("SELECT * FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `parent_item_id` = '".$allOrderItem[$i]['item_id']."'");
      $getSimpleRes = $getSimple->fetch(); 

      $pr_qty = $getSimpleRes['qty_ordered'];
      $pr_price = $allOrderItem[$i]['price']; 
      $pr_row_total = $allOrderItem[$i]['row_total'];    

      $_product = Mage::getModel('catalog/product')->load($getSimpleRes['product_id']); 
          
      $color_qry = $read->query("SELECT `value` FROM `eav_attribute_option_value` WHERE `option_id` = '".$_product['color']."'");
      $color_row = $color_qry->fetch();
        
      $size_qry = $read->query("SELECT `value` FROM `eav_attribute_option_value` WHERE `option_id` = '".$_product['size']."'");
      $size_row = $size_qry->fetch(); 
      
      $color = $color_row['value'];
      $size = $size_row['value'];
      $price = $_product['price'];
      $name = $_product['name'];  
              
      $product_detail = $products->addChild('product_detail');
      $product_detail->addChild('product_name', $name);
      $product_detail->addChild('product_code', $style_code);
      $product_detail->addChild('product_color', $color);
      //$product_detail->addChild('product_design_id', $design_code);
      $product_detail->addChild('product_design_id', '001');
      $product_detail->addChild('tax', '0');
      $product_size = $product_detail->addChild('product_size');
      $product_size->addChild('size_name', $size);
      $product_size->addChild('size_quantity', round($pr_qty));
      $product_size->addChild('unit_price', round($pr_price));  

      $total_style_code[] = array($style_code, $_product['color'], $color, $_product['size'], $size, $categoryId);   
    }
    // code for invoice pdf
    require('html2pdf_sample/html2fpdf.php');
    $pdf = new HTML2FPDF();
    $pdf->AddPage();
    /*$fp = fopen("order_shipped.html","r");
    $strContent = fread($fp, filesize("order_shipped.html"));
    fclose($fp);*/
    $inv_no = rand(0, 100);
    $html = '';
    $html .= '<!doctype html>
      <html>
      <head>
      <meta charset="utf-8">
      <title>:: Retail Invoice dfdfd::</title>
      <style type="text/css">
      body { background: #fff; font-family: Arial, Gotham, Helvetica, sans-serif; font-size:13px }
      table { border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; /*font-size: 0*/ }
      table td { border-collapse: collapse; font-size: 0 }
      </style>
      <style type="text/css">
      @media only screen and (max-width: 599px) {
      .social-icon { top: 100px!important }
      }
      </style>
      </head>
      <body style="padding:0; margin:0" >
      <div style="background:#fff" class="main-box">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tbody>
            <tr>
              <td align="center"><div style="width:100%; max-width:840px">
                 <table width="100%" border="0" cellspacing="0" cellpadding="5">
                  <tbody>
                    <tr>
                      <td rowspan="2" width="150" valign="top"><img src="http://www.bhishoom.com/skin/frontend/rwd/default/images/logoFooterInvoice.jpg" style="display:block; width:100px" alt="bhishoom"/></td>
                      <td rowspan="2" width="20" valign="top">&nbsp;</td>
                      <td rowspan="2" valign="top"><div style=" font-size:12px"><strong>Dreambox Retail Pvt. Ltd. sdsds</strong><br>
                          37A, Bhagat Vatika, Raj Bhavan Road, <br>
                          Civil Lines, Jaipur - 302006</div><br>
                        <div style="font-size:12px"><strong>Call Us:</strong> +91 96100 55577</div><br>
                        <div style="font-size:12px"><strong>Email:</strong> support@bhishoom.com</div><br>
                        <div style="font-size:12px"><strong>Website:</strong> www.bhishoom.com</div></td>
                      <td rowspan="2" width="20" valign="top">&nbsp;</td>
                      <td valign="top" ><img src="http://www.bhishoom.com/skin/frontend/rwd/default/images/barcode.jpg" style=" border:1px solid #353535; padding:10px 10px 10px 10px; text-align:center" height="60" alt="Bhishoom" /></td>
                    </tr>
                    <tr>
                      <td valign="top"><span style="font-size:15px;  font-weight:bold; line-height:1; letter-spacing:15px; padding-left:15px">FEDEX</span><br>
                ( Collect Cash on Delivery )</td>
                    </tr>
                  </tbody>
                </table>
                  


                <table width="100%" border="0" cellspacing="0" cellpadding="5">
                    <tbody>
                      <tr>
                       <td colspan="4" align="center" style="font-size:22px; font-weight:bold; text-align:center; height:50px; text-transform:uppercase">Retails Invoice</td>
                      <tr>
                        <td bgcolor="#CCCCCC">SHIP T0 </td>
                        <td>&nbsp;</td>
                        <td colspan="2" bgcolor="#CCCCCC">SHIP T0</td>
                      </tr>
                      <tr>
                        <td><strong>Name - </strong>'.$fname.'</td>
                        <td>&nbsp;</td>
                        <td bgcolor="#CCCCCC" id="iin"> Invoice No. </td>
                        <td>#'.$invIncrementIDs.'</td>
                      </tr>
                      <tr>
                        <td>[Company Name]</td>
                        <td>&nbsp;</td>
                        <td bgcolor="#CCCCCC">Order No.</td>
                        <td>#'.$order_id.'</td>
                      </tr>
                      <tr>
                        <td><strong>Street Address - </strong>'.$saddress1.'</td>
                        <td>&nbsp;</td>
                        <td bgcolor="#CCCCCC">Order Date</td>
                        <td>'.$order_date.'</td>
                      </tr>
                      <tr>
                        <td><strong>City, ST -</strong> '.$scity.', '.$sstate.'</td>
                        <td>&nbsp;</td>
                        <td bgcolor="#CCCCCC">Payment </td>
                        <td>'.$payment_method.'</td>
                      </tr>
                      <tr>
                        <td>ZIP - '.$spostcode.'</td>
                        <td>&nbsp;</td>
                        <td bgcolor="#CCCCCC">TIN No. </td>
                        <td>987654123</td>
                      </tr>
                      <tr>
                        <td>Phone - '.$stelephone.'</td>
                        <td>&nbsp;</td>
                        <td bgcolor="#CCCCCC">&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <td>Email Address - '.$email.'</td>
                        <td>&nbsp;</td>
                        <td bgcolor="#CCCCCC">&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </tbody>
                  </table>
                 <div style=" height:1px; margin:5px 0 15px; width:100%"></div>

 
                  <div style=" height:1px; margin:25px 0 15px; width:100%"></div>
                  <table width="100%" border="1" cellspacing="15" cellpadding="10">
                    <tbody>
                      <tr>
                        <td align="center" bgcolor="#D4D4D4"><div style="font-size:16px">S. NO.</div></td>
                        <td align="center" bgcolor="#D4D4D4"><div style="font-size:16px">ITEM DESCRIPTION</div></td>
                        <td align="center" bgcolor="#D4D4D4"><div style="font-size:16px">PRICE</div></td>
                        <td align="center" bgcolor="#D4D4D4"><div style="font-size:16px">TAX</div></td>
                        <td align="center" bgcolor="#D4D4D4"><div style="font-size:16px">QTY</div></td>
                        <td align="center" bgcolor="#D4D4D4"><div style="font-size:16px">SUB TOTAL</div></td>
                      </tr>
                      '; 

                      // for shipping
                      $getTot = $read->query("SELECT * FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `product_type` = 'simple'");
                      $getTotProd = $getTot->fetchAll();
                      $t=0;$t_qty=0;
                      foreach ($getTotProd as $value) 
                      {//echo $value['parent_item_id'];
                          if($value['parent_item_id'] == NULL)
                          {
                            ++$t;
                            $t_qty += $value['qty_ordered'];
                          }
                          else
                          {
                            break;
                          }
                      }                      

                      $pr_discount_amount = 0;$pr_ship_qty = 0;$j=1;$pr_finel_total=0;
                      $orderItem = $read->query("SELECT `item_id`, `product_id`, `price`, `row_total`, `discount_amount` FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `product_type` = 'configurable'");
                        $allOrderItem = $orderItem->fetchAll();
                        for($i=0;$i<count($allOrderItem);$i++)
                        {                           
                          $configProductid = $allOrderItem[$i]['product_id'];
                          $configProduct = Mage::getModel('catalog/product')->load($configProductid);  
                          $ids = $configProduct->getCategoryIds();
                          $categoryId = (isset($ids[0]) ? $ids[0] : $ids[1]);
                          $style_code = $configProduct['style_code'];

                          $getSimple = $read->query("SELECT * FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `parent_item_id` = '".$allOrderItem[$i]['item_id']."'");
                          $getSimpleRes = $getSimple->fetch();  
                            $pr_qty = $getSimpleRes['qty_ordered'];
                            $pr_ship_qty += $getSimpleRes['qty_ordered'];
                            $pr_price = $allOrderItem[$i]['price']; 
                            $pr_row_total = $allOrderItem[$i]['row_total']; 
                            $pr_finel_total += $allOrderItem[$i]['row_total']; 
                            $pr_discount_amount += $allOrderItem[$i]['discount_amount'];   
                          $_product = Mage::getModel('catalog/product')->load($getSimpleRes['product_id']); 
                              
                          $color_qry = $read->query("SELECT `value` FROM `eav_attribute_option_value` WHERE `option_id` = '".$_product['color']."'");
                          $color_row = $color_qry->fetch();
                            
                          $size_qry = $read->query("SELECT `value` FROM `eav_attribute_option_value` WHERE `option_id` = '".$_product['size']."'");
                          $size_row = $size_qry->fetch(); 
                          
                          $color = $color_row['value'];
                          $size = $size_row['value'];
                          $price = $_product['price'];
                          $name = $_product['name']; 
                          $html.= '<tr><td align="center"><div style="font-size:16px">'.$j.'</div></td>
                          <td ><div style="font-size:16px">'.$name.' Cotton Tshirt<br>Color - '.$color.'<br>Size - '.$size.'</div></td>
                          <td align="center" ><div style="font-size:16px">INR '.round($pr_price).'</div></td>
                          <td align="center" ><div style="font-size:16px">NILL</div></td>
                          <td align="center" ><div style="font-size:16px">'.round($pr_qty).'</div></td>
                          <td align="right" ><div style="font-size:16px">INR '.round($pr_row_total).'</div></td></tr>';
                          $j++;
                        } 
                        if($shipping_amount > 0)                       
                        {
                          if($t > 0)
                          {
                            $shipping_amount = $pr_ship_qty*20;
                          }
                          else
                          {
                            $shipping_amount = ($pr_ship_qty*20)+19;
                          }
                        }
                        $grandtotal = ($pr_finel_total+$shipping_amount)-$pr_discount_amount;
                      $html.='
                      <tr>
                        <td colspan="5" align="center" ><div style="font-size:16px">Shipping Charges</div></td>
                        <td align="center" ></td>
                        <td align="right" ><div style="font-size:16px">INR '.$shipping_amount.'</div></td>
                      </tr>
                      <tr>
                        <td colspan="5" align="center" ><div style="font-size:16px">Coupon Discount (Online Payment)</div></td>
                        <td align="center" ></td>
                        <td align="right" ><div style="font-size:16px">- INR '.$pr_discount_amount.'</div></td>
                      </tr>                       
                      <tr>
                        <td colspan="5" align="center" ><div style="font-size:16px"><em>Thank you for purchasing item on Bhishoom</em></div></td>
                        <td align="center" ><div style="font-size:16px"><strong>TOTAL</strong></div></td>
                        <td align="right" ><div style="font-size:16px"><strong>INR '.$grandtotal.'</strong></div></td>
                      </tr>
                    </tbody>
                  </table>                  
                  <div style=" height:1px; margin:25px 0 15px; width:100%"></div>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0" >
                    <tbody>
                      <tr>
                        <td height="5px"></td>
                      </tr>
                      <tr>
                        <td><div style=" font-size:12px; text-align:center; padding:5px; color:#666"> This is a computer generated invoice and does not required signature.<br>
                            In case of any feedback or query mail us at support@bhishoom.com or call +91 96100 55577.</div></td>
                      </tr>
                      <tr>
                        <td height="5px"></td>
                      </tr>
                    </tbody>
                  </table>
                </div></td>
            </tr>
          </tbody>
        </table>
      </div>
      </body>
      </html>
      ';
    $pdf->WriteHTML($html);
    $pdf->Output("invoice/file001.pdf");

    $invoice_url = Mage::getBaseUrl().'invoice/file001.pdf';

    $estore = $xml->addChild('estore');
    $estore->addChild('estore_invoice_available', 'yes');
    $estore->addChild('estore_invoice_url', $invoice_url);
    $estore->addChild('estore_clearance_available', 'yes');
    $estore->addChild('estore_clearance_url', $invoice_url);
    $estore->addChild('estore_manifest_required', 'yes');

    $xml->asXML('xml-file1.xml');
    $xml_str = $xml->asXML();
    
    $curl = curl_init();
    curl_setopt_array($curl, array(
      CURLOPT_RETURNTRANSFER => 1,
      CURLOPT_URL => 'http://99prints.99-dot-com-website-testing.com/api/create_order.php',
      //CURLOPT_SSL_VERIFYPEER => false,
      CURLOPT_USERAGENT => 'Codular Sample cURL Request',
      CURLOPT_POST => 1,
      CURLOPT_POSTFIELDS => array(
      "api_key" => "234yNCmXtkVcFY9P",
      "order_data" => $xml_str
      )
    ));
    $resp = curl_exec($curl);
    curl_close($curl);
    print_r($resp);

    $new_style_code = array_unique($total_style_code);
    $scurl = curl_init();
    curl_setopt_array($scurl, array(
        CURLOPT_RETURNTRANSFER => 1,
        CURLOPT_URL => 'http://23.251.150.147/api_test/merchant/stock.php',
        CURLOPT_USERAGENT => 'Codular Sample cURL Request',
        CURLOPT_POST => 1,
        CURLOPT_POSTFIELDS => array(
            'api_key' => 'bDNymqvhpxKWg7fr'
        )
    ));
    $sresp = curl_exec($scurl);
    curl_close($scurl);
    $sxml = simplexml_load_string($sresp);

    for($i=0;$i<count($total_style_code);$i++)
    {
      $code = $total_style_code[$i][0];
      $color_id = $total_style_code[$i][1];
      $color_name = $total_style_code[$i][2];
      $size_id = $total_style_code[$i][3];
      $size_name = $total_style_code[$i][4];
      $cat_id = $total_style_code[$i][5];
      $this->update_stock($sxml, $code, $color_id, $color_name, $size_id, $size_name, $cat_id);
    }
    

    $style_id_array = array();
    $inventory_array = array();

    foreach($sxml as $data)
    {
      $style_id = $data->style_id;
      if(!in_array($style_id,$style_id_array))
       $style_id_array[] = $style_id;
      else
         continue; 
        foreach($data->style_color as $color)
        {
          $color_name = addslashes($color->style_color_name);
          foreach($color->style_size as $size)
          {
            $size_name = addslashes($size->size_name);
            $stock = $size->size_stock;
            $inventory_array["$style_id"]["$color_name"]["$size_name"] = array("$stock");       
          }     
        }   
    }  

    foreach($style_id_array as $style_id_array_val)
    {
       //echo $style_id_array_val;
       //echo '<br/>';
      $write->query("update a_create_tshirt_inventory set inVentory = '".base64_encode(serialize($inventory_array["$style_id_array_val"]))."' where designId = '".$style_id_array_val."'");
    }   
  }
}  
?>
