<?php /* ?>
<div class="header-language-background">
    <div class="header-language-container">
        <div class="store-language-container">
            <?php echo $this->getChildHtml('store_language') ?>
        </div>

        <?php echo $this->getChildHtml('currency_switcher') ?>

        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p>
    </div>
</div>
<?php */ 
 
$connection = Mage::getSingleton('core/resource')->getConnection('core_read');
$write = Mage::getSingleton('core/resource')->getConnection('core_write'); 

?>
<script type="text/javascript">
var redirectUrl = '<?php echo $this->helper('core/url')->getCurrentUrl();?>';
var URL = '<?php echo $this->getUrl(); ?>';
function show_reg()
{
	if(document.getElementById("old_user").style.display == "block" || document.getElementById("old_user").style.display == "")
	{	
		document.getElementById("old_user").style.display = "none";
		document.getElementById("new_register").style.display = "block";
	}
}
function show_login()
{
	if(document.getElementById("new_register").style.display == "block" || document.getElementById("new_register").style.display == "")
	{	
		document.getElementById("new_register").style.display = "none";
		document.getElementById("old_user").style.display = "block";
	}
}
</script>
<?php
$currCat = Mage::getModel('catalog/layer')->getCurrentCategory()->getName();
Mage::getSingleton('core/session')->setCurrCat($currCat);
?>
<?php /*?>
$myValue = '';	 
$myValue=Mage::getSingleton('core/session')->getMyValue(); 
if(isset($myValue) && $myValue == 'cart')
{		 
 ?>
  <script type="text/javascript">
  	jQuery(document).ready(function() {
		setTimeout(function(){
			jQuery("#header-cart").addClass("skip-active");
			setTimeout(function()
			{
				jQuery("#header-cart").removeClass("skip-active");
			}, 5000);
		}, 1000);
    });
  </script>
  <?php 
   Mage::getSingleton('core/session')->unsMyValue();
}
*/?>
<header id="header">
 <div class="container"> 
  <div  class="page-header">
   <div class="page-header-container">
    <div class="row">
     <div class="col-md-2">
      <a class="logo" href="<?php echo $this->getUrl('') ?>"> 
       <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" /> 
       <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" /> 
      </a>
     </div>
    <div style="display:none;"> <?php 
$sql        = "Select * from amenu_update_tracking where up_flag_type = 'upper'";
$rows       = $connection->fetchRow($sql); //fetchRow($sql), fetchOne($sql),...	
	
	if($rows["up_flag"]=='y'){
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text.txt", $this->getChildHtml('topLinks'));
	 
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text.txt", php_strip_whitespace (Mage::getBaseDir('media')."/menu_cache/menu_text.txt")); 
	
		$sql = "update amenu_update_tracking set up_flag='n' where up_flag_type = 'upper'";
		$write->query($sql);
	} 
	
	include_once(Mage::getBaseDir('media')."/menu_cache/menu_text.txt");	 
	 

	 ?>     
  </div>	 
<div id="wp-nav-container" class="nav-container">    
    <div style="" class="" id="custommenu">
<?php
 

	$sql        = "Select up_flag from amenu_update_tracking where up_flag_type = 'upper_menu_foooter'";
	$rows       = $connection->fetchRow($sql); //fetchRow($sql), fetchOne($sql),...	
	
	if($rows["up_flag"]=='y'){ 
  
		 $menuContent = Mage::helper('custommenu')->getMenuContent(); 
		 $mobileMenuContent = Mage::helper('custommenu')->getMobileMenuContent();		 
 
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_top.txt", ($menuContent['topMenu'])); 
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_top.txt", php_strip_whitespace (Mage::getBaseDir('media')."/menu_cache/menu_text_top.txt"));
		
		
		
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_popup.txt", ($menuContent['popupMenu'])); 
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_popup.txt", php_strip_whitespace (Mage::getBaseDir('media')."/menu_cache/menu_text_popup.txt"));
		
		
		
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_mobile.txt", ($mobileMenuContent)); 
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_mobile.txt", php_strip_whitespace (Mage::getBaseDir('media')."/menu_cache/menu_text_mobile.txt")); 
 
		$sql = "update amenu_update_tracking set up_flag='n' where up_flag_type = 'upper_menu_foooter'";
		$write->query($sql);
	}

include_once(Mage::getBaseDir('media')."/menu_cache/menu_text_popup.txt");	 
include_once(Mage::getBaseDir('media')."/menu_cache/menu_text_top.txt");	 
?>
	</div>
</div>	
 	 
	 
	 
     <!-- Search -->
     <div class="col-md-4 pull-right">
      <div id="<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){ ?>header-search2<?php }else{?>header-search<?php }?>" class="skip-content"> <?php echo $this->getChildHtml('topSearch'); ?> </div>      
      <!-- Skip Links -->      
      <div class="skip-links"> 
       <a href="#header-nav" class="skip-link skip-nav"> <span class="icon"></span> <span class="label"><?php echo $this->__('Menu'); ?></span></a> 
       <a href="#header-search" class="skip-link skip-search"> <span class="icon"></span> <span class="label"><?php echo $this->__('Search'); ?></span> </a> 
       <!--<a href="#header-account" class="skip-link skip-account"> <i class="fa fa-user fa-lg"></i> -->
		<?php if(Mage::getSingleton('customer/session')->isLoggedIn()):    ?>
       	 <a title="Log Out" class="login-link skip-account" href="<?php echo $this->getUrl('').'customer/account/logout/';?>"><i class="fa fa-sign-out fa-lg"></i></a>
         <a title="My Account" class="login-link skip-account myHead" href="<?php echo $this->getUrl('').'customer/account/';?>"><i class="fa fa-user fa-lg"></i>
</a>
        <?php else: ?>
         <a title="Log In" class="login-link skip-account" id="alogin" href="javascript:void(0)"><i class="fa fa-user fa-lg"></i></i></a>             
      	<?php endif; ?>
		 </a> 
        <!-- Cart -->
       <div class="header-minicart"> <?php echo $this->getChildHtml('minicart_head'); ?> </div>
       <div class="store-language-container"></div>
      </div>
     </div>
    </div>
   </div> 
  </div>
 </div>   
</header>

<div class="nav-section">
 <div class="container">
  <div class="page-header">     
   <!-- Navigation -->  
   <div id="header-nav" class="skip-content nav-collapse collapse">   
   <div class="navbar_icon_bar">
   	<ul>
    	<li class="free_shiping">All Products Are<br>Dispatched in 3-5 Days.</li>
        <li class="best_in_class">Best-in-Class<br>Quality Guaranteed.</li>
    </ul>
   </div>
    <?php //echo $this->getChildHtml('topMenu') ?>   
    <?php 


/*$sql        = "Select * from amenu_update_tracking where up_flag_type = 'lower'";
$rows       = $connection->fetchRow($sql); //fetchRow($sql), fetchOne($sql),...	
	
	if($rows["up_flag"]=='y'){ 
			 $rootcatId= '24';
	$categories = Mage::getModel('catalog/category')->getCategories($rootcatId);
	

	
	file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu.txt", Mage::helper('function')->get_categories($categories));
	
	
	file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu.txt", php_strip_whitespace (Mage::getBaseDir('media')."/menu_cache/menu.txt"));
	
			$sql = "update amenu_update_tracking set up_flag='n' where up_flag_type = 'lower'";
			$write->query($sql);
	} */
	
	include_once(Mage::getBaseDir('media')."/menu_cache/menu.txt");
	
	//echo file_get_contents(Mage::getBaseUrl('media')."/menu_cache/menu.txt");
	?>
   </div>    
   <!-- Account -->
  </div>
 </div>
</div>
<?php echo $this->getChildHtml('topContainer'); ?> 

<?php
$j=0;
?>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('quicklogin/tinybox.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('quicklogin/quicklogin.js') ?>"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery(".dropdown").hover(
        function() { jQuery('.dropdown-menu', this).fadeIn("fast");
        },
        function() { jQuery('.dropdown-menu', this).fadeOut("fast");
    });
});
function get_device(val, type_id, select2)
{
   var dataString = "get_device="+val+"&type_id="+type_id+"&select="+select2;
   var reloadurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'admin_cat.php'?>';
	//Element.show('loadingmask');
	new Ajax.Request(reloadurl, {
	method: 'post',
	parameters: dataString,
	onComplete: function(transport) {
	//Element.hide('loadingmask');
	document.getElementById("bvalues").innerHTML = transport.responseText;
	}
	});
}
function get_device1(val, type_id, select3)
{
   var dataString = "get_device="+val+"&type_id="+type_id+"&select="+select3;
   var reloadurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'admin_cat.php'?>';
	//Element.show('loadingmask');
	new Ajax.Request(reloadurl, {
	method: 'post',
	parameters: dataString,
	onComplete: function(transport) {
	//Element.hide('loadingmask');
	document.getElementById("bvalues1").innerHTML = transport.responseText;
	}
	});
}
function chk_validate()
{
	var bselect = document.getElementById("bselects").value;
	var bvalue = document.getElementById("bvalues").value;	
	if(bselect == 0)
	{
		alert("Please Select First Value");
		return false;
	}
	if(bvalue == 0)
	{
		alert("Please Select Second Value");
		return false;
	}
	
	var dataString = "get_bselect="+bselect+"&get_bvalue="+bvalue;
    var reloadurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'admin_cat.php'?>';
	//Element.show('loadingmask');
	new Ajax.Request(reloadurl, {
	method: 'post',
	parameters: dataString,
	onComplete: function(transport) {
	window.location.href = transport.responseText;
	}
	});
}
jQuery(function ($) {
    var $active = $('#accordion-skin .panel-collapse.in').prev().addClass('active');
    $active.find('a').append('<i class="glyphicon glyphicon-minus" id="acc-sign"></i>');
    $('#accordion-skin .panel-heading').not($active).find('a').append('<i class="glyphicon glyphicon-plus" id="acc-sign"></i>');
    $('#accordion-skin').on('show.bs.collapse', function (e) {
        $('#accordion-skin .panel-heading.active').removeClass('active').find('.glyphicon').toggleClass('glyphicon-plus glyphicon-minus');
        $(e.target).prev().addClass('active').find('.glyphicon').toggleClass('glyphicon-plus glyphicon-minus');
    })
});
jQuery(function ($) {
    var $active = $('#accordion-lapi .panel-collapse.in').prev().addClass('active');
    $active.find('a').append('<i class="glyphicon glyphicon-minus" id="acc-sign"></i>');
    $('#accordion-lapi .panel-heading').not($active).find('a').append('<i class="glyphicon glyphicon-plus" id="acc-sign"></i>');
    $('#accordion-lapi').on('show.bs.collapse', function (e) {
        $('#accordion-lapi .panel-heading.active').removeClass('active').find('.glyphicon').toggleClass('glyphicon-plus glyphicon-minus');
        $(e.target).prev().addClass('active').find('.glyphicon').toggleClass('glyphicon-plus glyphicon-minus');
    })
});
</script>