<?php /* ?>
<div class="header-language-background"> 
    <div class="header-language-container">
        <div class="store-language-container">
            <?php echo $this->getChildHtml('store_language') ?>
        </div>

        <?php echo $this->getChildHtml('currency_switcher') ?>

        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p>
    </div>
</div>
<?php */ 
 
$connection = Mage::helper('function/more')->getDbReadObject();
$write = Mage::helper('function/more')->getDbWriteObject();	

$checkMobileDeviceBhishoom = Mage::helper('function/more')->chkIfmobileBhishomm();
?>
<script type="text/javascript">
var redirectUrl = '<?php echo $this->helper('core/url')->getCurrentUrl();?>';
var URL = '<?php echo $this->getUrl(); ?>';
function show_reg()
{
	 	jQuery("#old_user").hide();
		jQuery("#new_register").show();
	 
}
function show_login()
{

		jQuery("#quicklogin").find('#old_user').show();
		jQuery("#quicklogin").find('#new_register').hide();


}
</script>
<?php
$currCat = Mage::getModel('catalog/layer')->getCurrentCategory()->getName();
Mage::getSingleton('core/session')->setCurrCat($currCat);
?>
<?php /*?>
$myValue = '';	 
$myValue=Mage::getSingleton('core/session')->getMyValue(); 
if(isset($myValue) && $myValue == 'cart')
{		 
 ?>
  <script type="text/javascript">
  	jQuery(document).ready(function() {
		setTimeout(function(){
			jQuery("#header-cart").addClass("skip-active");
			setTimeout(function()
			{
				jQuery("#header-cart").removeClass("skip-active");
			}, 5000);
		}, 1000);
    });
  </script>
  <?php 
   Mage::getSingleton('core/session')->unsMyValue();
}
*/?>

<div id="responsiveHeader" class="hidden-lg hidden-md">
  <div class="container-fluid">
    <div class="row row-xs">
      <div class="col-xs-4 ">
        <button id="responsiveBtn"  data-toggle="offcanvas" class="navbar-toggle pull-left collapsed" type="button"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      </div>
      <div class="col-xs-4"> <a class="logoM"  href="<?php echo $this->getUrl('') ?>"> <img src="<?php echo $this->getSkinUrl('images/logo.png');?>" alt="<?php echo $this->getLogoAlt() ?>" /> </a></div>
      <div class="col-xs-4">
        <div id="responsiveLinks" class="">
          <div class="responsiveLinks"> 
		<span id="searchBtnH" ><i class="fa fa-search"></i></span>
          
            <!--<a href="#header-account" class="skip-link skip-account"> <i class="fa fa-user fa-lg"></i> -->
			<?php /*<?php if(Mage::getSingleton('customer/session')->isLoggedIn()):    ?>
            <a title="Log Out" class="login-link skip-account" href="<?php echo $this->getUrl('').'customer/account/logout/';?>"><i class="fa fa-sign-out fa-lg"></i></a> 
			<a title="My Account" class="login-link skip-account myHead" href="<?php echo $this->getUrl('').'customer/account/';?>"><i class="fa fa-user fa-lg"></i> </a>
            <?php else: ?>
            <span id="searchBtnH" ><i class="fa fa-search"></i></span>
            */
			?>
			<?php /*?> <div id="<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){ ?>header-search2<?php }else{?>header-search<?php }?>" class="skip-content"> <?php echo $this->getChildHtml('topSearch'); ?> </div><?php */?>
			 <?php
			 $cart = 0;
			  $items = Mage::getSingleton('checkout/session')->getQuote()->getAllItems();
			foreach($items as $item){
				$cart  += $item->getQty();
			}
			
 ?>
            <a href="<?php echo $this->getBaseUrl().'checkout/cart/';?>" title="<?php echo $cart ?> Item in your cart" class="skip-cart  no-count">
            <div class="noti_bubble"><?php echo $cart ?> </div>
             <img src="http://magento.itcslive.com/napfond/skin/frontend/rwd/default/images/BAG_ICON.png" alt="shopping-icon"> </a>
            
            
            <!-- Cart -->
            <div class="header-minicart">
              <?php //echo $this->getChildHtml('minicart_head'); ?>
            </div>
            <div class="store-language-container"></div>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<div class="clearfix"></div>
<div id="responsiveSearch"> <?php echo $this->getChildHtml('topSearch'); ?> </div>
<div class="clearfix"></div>
<div id="responsiveNavItem">
  <div class="blackBackresponsive"></div>
  <header id="header" class="hidden-xs hidden-sm">
    <div class="container">
      <div  class="page-header">
        <div class="page-header-container">
          <div class="row">
            <div class="col-md-2 hidden-sm hidden-xs"> <a class="logo" href="<?php echo $this->getUrl('') ?>"> <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
              <?php /*?> <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" /> <?php */?>
              </a> </div>
            <div style="display:none;">
              <?php 
$sql        = "Select * from amenu_update_tracking where up_flag_type = 'upper'";
$rows       = $connection->fetchRow($sql); //fetchRow($sql), fetchOne($sql),...	
	
	if($rows["up_flag"]=='y'){
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text.txt", $this->getChildHtml('topLinks'));
	 
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text.txt", php_strip_whitespace (Mage::getBaseDir('media')."/menu_cache/menu_text.txt")); 
	
		$sql = "update amenu_update_tracking set up_flag='n' where up_flag_type = 'upper'";
		$write->query($sql);
	} 
	
	include_once(Mage::getBaseDir('media')."/menu_cache/menu_text.txt");	 

	 ?>
            </div>
            <div id="wp-nav-container" class="nav-container">
              <div style="" class="" id="custommenu">
                <?php

	$sql        = "Select up_flag from amenu_update_tracking where up_flag_type = 'upper_menu_foooter'";
	$rows       = $connection->fetchRow($sql); //fetchRow($sql), fetchOne($sql),...	
	
	if($rows["up_flag"]=='y'){ 
  
		 $menuContent = Mage::helper('custommenu')->getMenuContent(); 
		 $mobileMenuContent = Mage::helper('custommenu')->getMobileMenuContent();		 
 
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_top.txt", ($menuContent['topMenu'])); 
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_top.txt", php_strip_whitespace (Mage::getBaseDir('media')."/menu_cache/menu_text_top.txt"));
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_popup.txt", ($menuContent['popupMenu'])); 
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_popup.txt", php_strip_whitespace (Mage::getBaseDir('media')."/menu_cache/menu_text_popup.txt"));
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_mobile.txt", ($mobileMenuContent)); 
		file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu_text_mobile.txt", php_strip_whitespace (Mage::getBaseDir('media')."/menu_cache/menu_text_mobile.txt")); 
		$sql = "update amenu_update_tracking set up_flag='n' where up_flag_type = 'upper_menu_foooter'";
		$write->query($sql);
	}

include_once(Mage::getBaseDir('media')."/menu_cache/menu_text_popup.txt");	 
include_once(Mage::getBaseDir('media')."/menu_cache/menu_text_top.txt");	 
?>
              </div>
            </div>
            <div class="col-md-5 pull-right hidden-sm hidden-xs">
              <div id="<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){ ?>header-search2<?php }else{?>header-search<?php }?>" class="skip-content"> <?php echo $this->getChildHtml('topSearch'); ?> </div>
              <!-- Skip Links -->
              <div class="skip-links"> <a href="#header-nav" class="skip-link skip-nav"> <span class="icon"></span> <span class="label"><?php echo $this->__('Menu'); ?></span></a> <a href="#header-search" class="skip-link skip-search"> <span class="icon"></span> <span class="label"><?php echo $this->__('Search'); ?></span> </a>
                <?php if(Mage::getSingleton('customer/session')->isLoggedIn()):    ?>
                <a title="Log Out" class="login-link skip-account hidden-sm hidden-xs" href="<?php echo $this->getUrl('').'customer/account/logout/';?>"><i class="fa fa-sign-out fa-lg"></i></a> <a title="My Account" class="login-link skip-account myHead  hidden-sm hidden-xs" href="<?php echo $this->getUrl('').'customer/account/edit';?>"><i class="fa fa-user fa-lg"></i> </a>
                <?php else: ?>
                <a title="Log In" class="login-link skip-account" id="alogin" href="javascript:void(0)"><i class="fa fa-user fa-lg"></i></i></a>
                <?php endif; ?>
                <!-- Cart -->
                <div class="header-minicart"> <?php echo $this->getChildHtml('minicart_head'); ?> </div>
                <div class="store-language-container"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="nav-section">
    <div class="container">
      <div class="page-header">
        <div class="resVHeaderLogoVf">
          <div class="row row-xs">
            <div class="col-xs-3"> <a id="responsiveBtn1">Back</a> </div>
            <div class="col-xs-6 text-center"> <a class="logoM" href="<?php echo $this->getUrl('') ?>"> <img src="<?php echo $this->getSkinUrl('images/logo.png');?>" alt="<?php echo $this->getLogoAlt() ?>" /> </a></div>
          </div>
        </div>
        <div class="clearfix"></div>
        <!-- Navigation -->
        <div id="header-nav" class="skip-content1 nav-collapse1 collapse1">
          <div class="navbar_icon_bar">
            <ul>
              <li class="free_shiping">Free shipping <br>
                above Rupees <?php echo Mage::getStoreConfig('carriers/fedex/free_shipping_subtotal');?>/-</li>
              <li class="best_in_class">Best-in-Class<br>
                Quality Guaranteed.</li>
            </ul>
          </div>
          <?php //echo $this->getChildHtml('topMenu') ?>
          <?php 


/*$sql        = "Select * from amenu_update_tracking where up_flag_type = 'lower'";
$rows       = $connection->fetchRow($sql); //fetchRow($sql), fetchOne($sql),...	
	
	if($rows["up_flag"]=='y'){ 
			 $rootcatId= '24';
	$categories = Mage::getModel('catalog/category')->getCategories($rootcatId);
	

	
	file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu.txt", Mage::helper('function')->get_categories($categories));
	
	
	file_put_contents(Mage::getBaseDir('media')."/menu_cache/menu.txt", php_strip_whitespace (Mage::getBaseDir('media')."/menu_cache/menu.txt"));
	
			$sql = "update amenu_update_tracking set up_flag='n' where up_flag_type = 'lower'";
			$write->query($sql);
	} */
	
	include_once(Mage::getBaseDir('media')."/menu_cache/menu.txt");
	
	//echo file_get_contents(Mage::getBaseUrl('media')."/menu_cache/menu.txt");
	?>
        </div>
		<?php //if($checkMobileDeviceBhishoom){?>
        <div  id="responsiveNav">
          <?php include_once(Mage::getBaseDir('media')."/menu_cache/mobile_menu_bhishoom.txt"); ?>
          <?php 
			$sessionCustomer =Mage::getSingleton("customer/session");
			 if ($sessionCustomer->isLoggedIn()) {
			?>
          <ul class="loginNav navGroup3">
            <li><a href="<?php echo Mage::getUrl('customer/account/edit');?>"><i class="mi mi-Login"></i>My Account</a></li>
            <li><a href="<?php echo Mage::getUrl('customer/account/logout');?>"><i class="mi mi-logOut"></i>Logout</a></li>
          </ul>
          <?php
				} 
				else {
				?>
          <ul class="loginNav navGroup4">
            <li><a href="<?php echo Mage::getUrl('customer/account/login'); ?>"><i class="mi mi-Login"></i> Login</a> </li>
          </ul>
          <?php   
				}
				?>
          <ul class="mainNav1 navGroup2">
            <li><a href="<?php echo $this->getUrl('faq')?>"><i class="mi mi-faqs"></i>FAQ's</a></li>
            <li><a href="<?php echo $this->getUrl('trackorder') ?>"> <i class="mi mi-orderStatus"></i>Track Order</a></li>
            <li><a href="<?php echo $this->getUrl('contacts') ?>"><i class="mi mi-contactUs"></i>Contact Us</a></li>
          </ul>
        </div>
        <?php //}?>
        <!-- Account --> 
      </div>
    </div>
  </div>
</div>
<?php echo $this->getChildHtml('topContainer'); ?>
<?php
$j=0;
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('quicklogin/tinybox.js') ?>"></script> 
<script type="text/javascript" src="<?php echo $this->getSkinUrl('quicklogin/quicklogin.js') ?>"></script> 
<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery(".dropdown").hover(
        function() { jQuery('.dropdown-menu', this).fadeIn("fast");
        },
        function() { jQuery('.dropdown-menu', this).fadeOut("fast");
    });
});
function get_device(val, type_id, select2)
{
   var dataString = "get_device="+val+"&type_id="+type_id+"&select="+select2;
   var reloadurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'admin_cat.php'?>';
	//Element.show('loadingmask');
	new Ajax.Request(reloadurl, {
	method: 'post',
	parameters: dataString,
	onComplete: function(transport) {
	//Element.hide('loadingmask');
	document.getElementById("bvalues").innerHTML = transport.responseText;
	}
	});
}
function get_device1(val, type_id, select3)
{
   var dataString = "get_device="+val+"&type_id="+type_id+"&select="+select3;
   var reloadurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'admin_cat.php'?>';
	//Element.show('loadingmask');
	new Ajax.Request(reloadurl, {
	method: 'post',
	parameters: dataString,
	onComplete: function(transport) {
	//Element.hide('loadingmask');
	document.getElementById("bvalues1").innerHTML = transport.responseText;
	}
	});
}
function chk_validate()
{
	var bselect = document.getElementById("bselects").value;
	var bvalue = document.getElementById("bvalues").value;	
	if(bselect == 0)
	{
		alert("Please Select First Value");
		return false;
	}
	if(bvalue == 0)
	{
		alert("Please Select Second Value");
		return false;
	}
	
	var dataString = "get_bselect="+bselect+"&get_bvalue="+bvalue;
    var reloadurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'admin_cat.php'?>';
	//Element.show('loadingmask');
	new Ajax.Request(reloadurl, {
	method: 'post', 
	parameters: dataString,
	onComplete: function(transport) {
	window.location.href = transport.responseText;
	}
	});
}
jQuery(function () {
    var $active = jQuery('#accordion-skin .panel-collapse.in').prev().addClass('active');
    $active.find('a').append('<i class="glyphicon glyphicon-minus" id="acc-sign"></i>');
    jQuery('#accordion-skin .panel-heading').not($active).find('a').append('<i class="glyphicon glyphicon-plus" id="acc-sign"></i>');
    jQuery('#accordion-skin').on('show.bs.collapse', function (e) {
        jQuery('#accordion-skin .panel-heading.active').removeClass('active').find('.glyphicon').toggleClass('glyphicon-plus glyphicon-minus');
        jQuery(e.target).prev().addClass('active').find('.glyphicon').toggleClass('glyphicon-plus glyphicon-minus');
    })
});
jQuery(function () {
    var $active = jQuery('#accordion-lapi .panel-collapse.in').prev().addClass('active');
    $active.find('a').append('<i class="glyphicon glyphicon-minus" id="acc-sign"></i>');
    jQuery('#accordion-lapi .panel-heading').not($active).find('a').append('<i class="glyphicon glyphicon-plus" id="acc-sign"></i>');
    jQuery('#accordion-lapi').on('show.bs.collapse', function (e) {
        jQuery('#accordion-lapi .panel-heading.active').removeClass('active').find('.glyphicon').toggleClass('glyphicon-plus glyphicon-minus');
        jQuery(e.target).prev().addClass('active').find('.glyphicon').toggleClass('glyphicon-plus glyphicon-minus');
    })
});
/* My Model ceter code*/
/*jQuery(document).ready(function(){
    function alignModal(){
        var modalDialog = jQuery(this).find(".modal-dialog");
        
        // Applying the top margin on modal dialog to align it vertically center
        modalDialog.css("margin-top", Math.max(0, (jQuery(window).height() - modalDialog.height()) / 2));
    }
    // Align modal when it is displayed
    jQuery(".modal").on("shown.bs.modal", alignModal);
    
    // Align modal when user resize the window
    jQuery(window).on("resize", function(){
       jQuery(".modal:visible").each(alignModal);
    });   
});*/

</script>
<script>
jQuery(document).ready(function(){
	var thing = jQuery('#responsiveNavItem');
    var extra = 100;
    var old = jQuery(thing).scrollTop();
    $(thing).scroll(function() {
        if ($(thing).scrollTop() < old) {
            $(thing).scrollTop($(thing).scrollTop()-extra);
        } else if ($(thing).scrollTop() > old) {
            $(thing).scrollTop($(thing).scrollTop()+extra);
        }
        old = $(thing).scrollTop();
    });
	
	jQuery(".skip-cart").click(function(){jQuery("#header-cart").addClass('skip-active');})
	jQuery(".skip-link-close").click(function(){jQuery("#header-cart").removeClass('skip-active');})
});
</script>
