<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use/
 * @version      Release: 1.0.0
 * @since        Available since Release 1.0.0
 */
?>
<h3 class="product-name"><a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a></h3>
<?php if (($_options = $this->getOptionList()) || $this->getDesignOption()):?>
<dl class="item-options">
    <?php if ($this->getDesignOption()): ?>
        <dt><?php echo $this->__('Design'); ?></dt>
    <?php endif;?>
    <?php if ($_options): ?>
        <?php foreach ($_options as $_option) : ?>
        <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
        <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
        <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
            <?php if (isset($_formatedOptionValue['full_view'])): ?>
            <div class="truncated_full_value">
                <dl class="item-options">
                    <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                    <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                </dl>
            </div>
            <?php endif; ?>
        </dd>
        <?php endforeach; ?>
    <?php endif;?>
</dl>
<?php endif; ?>
