<?php
/**
* Strapp Changeproductposition Module
*
* @category    design
* @package     default_default
**/
?>

<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'strapp/jquery/jquery-1.7.2.min.js'; ?>"></script>
<script type="text/javascript">jQuery.noConflict();</script>
<style type="text/css" >
    ul { list-style-type:none; padding:0; margin:0; }
    li { margin-left:0; border:1px solid #ccc; margin:2px; padding:2px 2px 2px 2px; font:normal 12px sans-serif; }
    img { margin-right:5px; }
</style>

<?php
$allCategoryIds 	= Mage::getModel('catalog/category')->getTreeModel()->load()->getCollection()->getAllIds();
$records		=count(file($this->getImportfilename()))-1;
$processedRecords	=0;
$i			=0;
if($records !=0)
{
?>
  <ul>
      <li>
	<img src="<?php echo $this->getSkinUrl('images/note_msg_icon.gif')?>" class="v-middle" style="margin-right:5px"/>
        <?php echo $this->__("Starting profile execution, please wait...");?>
      </li>
      <li style="background-color:#FFD;">
        <img src="<?php echo $this->getSkinUrl('images/fam_bullet_error.gif');?>" class="v-middle" style="margin-right:5px"/>
            <?php echo $this->__("Warning: Please do not close the window during importing of data");?>
      </li>
  </ul>
  <ul id="profileRows">
    <li style="background-color:#DDF;">Found <strong><?php echo $records?></strong> rows.Please don't close till you got success message.
    </li>
     
    <li id="importpositionprogress" style="display:none;">
    <img id="progressimage" src="<?php echo $this->getSkinUrl('images/ajax-loader.gif');?>" class="v-middle" style="margin-right:5px"/>
    Processed <strong id="processpercentage"></strong> <strong id="processedrecords"></strong><strong>/<?php echo $records;?></strong> Records
    </li>
  </ul>
<?php        
  if (($handle = fopen($this->getImportfilename(), "r")) !== FALSE)
  {	  
      while (($data = fgetcsv($handle)) !== FALSE)
      {		
	  if($i == 0){$i++; continue;}
	  if($data[0]!=''&&$data[1]!=''&&$data[2]!='')
	  {
	      $productId =Mage::getModel("catalog/product")->getIdBySku($data[1]);
	      if(!(in_array($data[0],$allCategoryIds)))
	      {
		  //Mage::getSingleton('adminhtml/session')->addError(Mage::helper('changeproductposition')->__('Mention correct category id for record %d',$i));
		  
		  echo "<ul><li style=\"color:#DF280A\">Mention correct category id for record ".$i."</li></ul>";
		 
	      }
	      elseif($productId =='')
	      {
		  //Mage::getSingleton('adminhtml/session')->addError(Mage::helper('changeproductposition')->__('Mention correct product sku for record %d',$i));
		  echo "<ul><li style=\"color:#DF280A\">Mention correct product sku for record ".$i."</li></ul>";
		 
	      }
	      else
	      {?>
		  <script type="text/javascript">		       	  
		      importPosition("<?php echo Mage::helper("adminhtml")->getUrl('changeproductposition/adminhtml_importposition/processrecord', array('cat_id' =>$data[0],'product_id' =>$productId,'position' =>$data[2],'records'=>$processedRecords)); ?>");
		      
		      function importPosition(url)
		      {
			jQuery.ajax( 
			{
			  url : url,
			  dataType : 'json',
			  async :false,
			  success : function(data) 
			  {     
			    if(data.status == 'SUCCESS')
			    {			     
			      <?php ++$processedRecords;?>
			      jQuery('#importpositionprogress').show();
			      jQuery('#processpercentage').html(<?php echo ceil((($i/$records)*1000)/10);?>+'%');
			      jQuery('#processedrecords').html(<?php echo $i; ?>);		      			      
			    }
			  }

			});
		      }
		  </script>
	    <?php	    
	      }	
	      $i++;
	  }  
	  else
	  {
	      //Mage::getSingleton('adminhtml/session')->addError(Mage::helper('changeproductposition')->__('Error in record %d',$i));
	      echo "<ul><li style=\"color:#DF280A\">Error in record ".$i."</li></ul>";
	      $i++;
	  }	  
      }      
  }
  ?>
  <ul>
    <li id="importedRecords" style="display:none;">Imported <strong><?php echo $processedRecords;?>/<?php echo $records;?></strong> Records.
    </li>
    <li id="processindex" style="background-color:#FFD; display:none;">
      <img src="<?php echo $this->getSkinUrl('images/fam_bullet_error.gif');?>" class="v-middle" style="margin-right:5px"/>
      <?php echo $this->__("Please wait while the indexes are being refreshed.");?>
      <img id="before-finish-wait-img" src="<?php echo $this->getSkinUrl('images/rule-ajax-loader.gif');?>" class="v-middle" style="margin-right:5px"/>
    </li>
  <li id="liFinished" style="display:none;">
	<img src="<?php echo $this->getSkinUrl('images/note_msg_icon.gif');?>" class="v-middle" style="margin-right:5px"/>
	<?php echo $this->__("Finished the process of importing of product position.");?>
    </li>
</ul>
<script type="text/javascript">
  jQuery('#progressimage').hide();
  jQuery('#importedRecords').show();
  jQuery('#processindex').show();
  processProductIndex("<?php echo Mage::helper("adminhtml")->getUrl('changeproductposition/adminhtml_importposition/processindex')?>");
  
  function processProductIndex(url)
  {    
    jQuery.ajax( 
      {
	  url : url,
	  dataType : 'json',
	  async :false,
	  success : function(data) 
	  {     
	    if(data.status == 'SUCCESS')
	    {
	      jQuery('#processindex').hide();
	    }
	  }
      }
	      );
  }
		      
  jQuery('#liFinished').show();
</script>
<?php    
}
else
{
//   Mage::getSingleton('adminhtml/session')->addError(Mage::helper('changeproductposition')->__('Please specify atleast one record in csv file'));
   echo "<ul><li style=\"color:#DF280A\">Please specify atleast one record in csv file</li></ul>";  
}
?>
