<?php
/**
* Strapp Changeproductposition Module
*
* @category    design
* @package     default_default
**/
?>
<script type="text/javascript">
function runProfile()
{
    var url = '<?php echo $this->getUrl('*/*/run') ?>';
    var file = getSelectedFiles();
    if (file == '') 
    {
        alert('Please select imported files');
        $('file_list').show();
          return false;
    }
    url += 'files/' + file + '/';
    window.open(url);    
}

function getSelectedFiles()
{
    return $('files').options[$('files').options.selectedIndex].value;
}
</script>

<ul class="messages">
<li class="notice-msg">
    <ul>
        <li><?php echo $this->__('Please make sure that you uploaded correct file before processing the import.') ?></li>
    </ul>
</li>
</ul>
<div id="file_list">
<select id="files" name="files">
    <option value="">Select a file</option>
    <?php if ($files = $this->getImportedCsvFiles()) :
    foreach ($files as $file) : ?>
        <option value=<?php echo $file ?>><?php echo $file ?></option>
<?php   endforeach;
    endif; ?>
</select>
<br />&nbsp;
</div>
<?php echo $this->getRunButtonHtml() ?><br/>    