<?php 
function getFeaturedProductsCollection($pCatId,$styleId)
{
	 $products = Mage::getModel('catalog/category')->load($pCatId); //put your category id here
	 $productslist = $products->getProductCollection()->addAttributeToSelect('*')->addAttributeToSelect('case_style', $styleId)->setCurPage(1)->setPageSize(5); 
	 $productslist->getSelect()->order(new Zend_Db_Expr('RAND()'));
	 return $productslist;
}

		$read = Mage::getSingleton('core/resource')->getConnection('core_read');
		$write = Mage::getSingleton('core/resource')->getConnection('core_write');	
		 


?>
<div class="row" id="home-cat-1">
 <div class="mid-line">
  <h2 class="feature-tag">Featured Products</h2>
 </div>
 <?php
 for($iiCounter=1;$iiCounter<5;$iiCounter++)
 {	
  if($iiCounter == 4)
  { ?>
    <div class="col-sm-12">         
     <div id="case-slider<?php echo $iiCounter;?>" class="carousel slide case-slide1" data-interval="false" data-ride="carousel">       
      <?php $_category = Mage::getModel('catalog/category')->load(4);
      if($_category->getIsActive()) 
      {?>     
        <div class="carousel-inner">
         <div class="active item">
          <img src="<?php echo $this->getSkinUrl('images/t-shirt1.png');?>" style="float:left;">               
          <img src="<?php echo $this->getSkinUrl('images/t-shirt2.png');?>" style="float:left;">               
          <img src="<?php echo $this->getSkinUrl('images/t-shirt3.png');?>" style="float:left;">               
          <div class="carousel-caption">
           <h3>First slide label</h3>                 
          </div>
         </div>
         <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/t-shirt7.png');?>" style="float:left;">               
          <img src="<?php echo $this->getSkinUrl('images/t-shirt8.png');?>" style="float:left;">               
          <img src="<?php echo $this->getSkinUrl('images/t-shirt9.png');?>" style="float:left;">               
          <div class="carousel-caption">
           <h3>Second slide label</h3>                  
          </div>
         </div>
         <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/t-shirt4.png');?>" style="float:left;">               
          <img src="<?php echo $this->getSkinUrl('images/t-shirt5.png');?>" style="float:left;">               
          <img src="<?php echo $this->getSkinUrl('images/t-shirt6.png');?>" style="float:left;">               
          <div class="carousel-caption">
           <h3>Third slide label</h3>                  
          </div>
         </div>
         <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/t-shirt10.png');?>" style="float:left;">               
          <img src="<?php echo $this->getSkinUrl('images/t-shirt11.png');?>" style="float:left;">               
          <img src="<?php echo $this->getSkinUrl('images/t-shirt12.png');?>" style="float:left;">               
          <div class="carousel-caption">
           <h3>Third slide label</h3>                  
          </div>
         </div>
        </div>
        <h2 class="skin-name"><?php echo $_category->getName();?></h2>
        <a class="carousel-control left" href="#case-slider<?php echo $iiCounter;?>" data-slide="prev">
      	 <i class="fa fa-angle-left fa-lg"></i>
     	</a>
     	<a class="carousel-control right" href="#case-slider<?php echo $iiCounter;?>" data-slide="next">
      	 <i class="fa fa-angle-right fa-lg"></i>
     	</a>
       <?php
	   }?> 
      </div>
     </div> 
   <?php  
   }
   else
   {
   ?>
    <div class="col-sm-4">         
     <div id="case-slider<?php echo $iiCounter;?>" class="carousel slide case-slide1" data-interval="false" data-ride="carousel">       
     <?php 
   	  if($iiCounter == 1)
  	  {
	  	 $_category = Mage::getModel('catalog/category')->load(3);
	     if($_category->getIsActive()) 
		 {?>
          <div class="carousel-inner">
           <?php
		   $products = getFeaturedProductsCollection(3,41); 
		   $i=1;
		   
		   $sql = "Select * from amenu_update_tracking where up_flag_type = 'mobile_case'";
		   $rows = $read->fetchRow($sql); //fetchRow($sql), fetchOne($sql),...	
		   $mobile_case_cat_arr_url_key = explode(',',$rows['menu_cnt_top']);
		   $mobile_case_cat_arr_id = explode(',',$rows['menu_cnt_pop']);
		   $mobile_case_cat_arr_length = (count($mobile_case_cat_arr_url_key)-1);
		   
		   foreach($products as $product)
		   { 
				$get_random_cat = rand(0,$mobile_case_cat_arr_length);					
				while(!is_file(Mage::getBaseDir('media').'/blank_images/mobile-case/'.$mobile_case_cat_arr_url_key[$get_random_cat].'/mask.png'))
				{
					$get_random_cat = rand(0,$mobile_case_cat_arr_length);		
				}			  
				$mimetype = mime_content_type(Mage::getBaseDir('media').'/blank_images/mobile-case/'.$mobile_case_cat_arr_url_key[$get_random_cat].'/mask.png');
			  	$blank_backImagePath = Mage::helper('function')->getRandomMobileCaseBlankImage($mobile_case_cat_arr_url_key[$get_random_cat]);
			  	$categoryObjForUrl = Mage::getSingleton('catalog/category')->load($mobile_case_cat_arr_id[$get_random_cat]); 			  
		   ?>	
			
        	 <div class="item <?php if($i == 1){ echo 'active';}?>">
           	  <a href="<?php echo Mage::helper('function')->getUrlPath($product,$categoryObjForUrl);?>">
			  <img src="<?php echo $blank_backImagePath;?>" width="245" height="245" style="position:absolute;left:24px;">
			  <img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize(245);//echo $product->getThumbnail();?>"></a>
           	  <div class="carousel-caption">
           		<h3><a href="<?php echo $product->getProductUrl();?>"><?php echo $product->getName();?></a></h3>                  
	          </div> 
    	     </div><?php 
		 	 $i++;
		   	}?>		  
     	  </div>
     	  <h2 class="skin-name"><?php echo $_category->getName();?></h2>     
  		<?php  
      	  }
	   }	 
 	   if($iiCounter == 2)
  	   {
		   $_category = Mage::getModel('catalog/category')->load(34);
		 
		   $sql = "Select * from amenu_update_tracking where up_flag_type = 'mobile_skin'";
		   $rows = $read->fetchRow($sql); //fetchRow($sql), fetchOne($sql),...	
		   $mobile_skin_cat_arr_url_key = explode(',',$rows['menu_cnt_top']);
		   $mobile_skin_cat_arr_id = explode(',',$rows['menu_cnt_pop']);
		   $mobile_skin_cat_arr_length = (count($mobile_skin_cat_arr_url_key)-1);		 
		 
  		 if($_category->getIsActive()) 
 		 {?>
  		   <div class="carousel-inner">
           <?php
	 		$products = getFeaturedProductsCollection(34, 228); 
			$i=1;
			foreach($products as $product)
			{ 
			
				$get_random_cat = rand(0,$mobile_skin_cat_arr_length); 
				
				while(!is_file(Mage::getBaseDir('media').'/blank_images/mobile-skin/'.$mobile_skin_cat_arr_url_key[$get_random_cat].'/mask-back.png'))
					{
						$get_random_cat = rand(0,$mobile_skin_cat_arr_length);		
					}
			  
			  
			
				$blank_backImagePath = Mage::helper('function')->getRandomMobileSkinBlankImage($mobile_skin_cat_arr_url_key[$get_random_cat]);
				
				$categoryObjForUrl = Mage::getSingleton('catalog/category')->load($mobile_skin_cat_arr_id[$get_random_cat]);
				
			?>		 
          	 <div class="item <?php if($i == 1){ echo 'active';}?>">
           	  <a href="<?php echo Mage::helper('function')->getUrlPath($product,$categoryObjForUrl);?>">
			  <img src="<?php echo $blank_backImagePath;?>" width="245" height="245" style="position:absolute;left:24px;">
			  <img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize(245);?>"></a>
		   	  <div class="carousel-caption">
               <h3><a href="<?php echo $product->getProductUrl();?>"><?php echo $product->getName();?></a></h3>                  
              </div> 
             </div>
			 <?php 
          	 $i++;
			 }?>		 
		   </div>
       	   <h2 class="skin-name"><?php echo $_category->getName();?></h2>
          <?php  
   		  }
		}
   		if($iiCounter == 3)
  		{    
	      $_category = Mage::getModel('catalog/category')->load(8);
    	  if($_category->getIsActive()) 
      	  {?> 
           <div class="carousel-inner">      
            <div class="active item">
             <img src="<?php echo $this->getSkinUrl('images/laptop-1.png');?>">               
             <div class="carousel-caption">
              <h3>First slide label</h3>                 
             </div>
            </div>
            <div class="item">
             <img src="<?php echo $this->getSkinUrl('images/laptop-2.png');?>">                
             <div class="carousel-caption">
              <h3>Second slide label</h3>                  
             </div>
            </div>
            <div class="item">
             <img src="<?php echo $this->getSkinUrl('images/laptop-3.png');?>">                
             <div class="carousel-caption">
              <h3>Third slide label</h3>                  
             </div>
            </div>
            <div class="item">
             <img src="<?php echo $this->getSkinUrl('images/laptop-4.png');?>">                
             <div class="carousel-caption">
              <h3>Third slide label</h3>                  
             </div>
            </div>
            <div class="item">
             <img src="<?php echo $this->getSkinUrl('images/laptop-5.png');?>">                
             <div class="carousel-caption">
              <h3>Third slide label</h3>                  
             </div>
            </div>
           </div>
           <h2 class="skin-name"><?php echo $_category->getName();?></h2>        
  		  <?php  
 		   }
		 }
         /*if($iiCounter == 5)
  		 {
	      $_category = Mage::getModel('catalog/category')->load(6);
    	  if($_category->getIsActive()) 
      	  {?>
       		<div class="carousel-inner">
	         <div class="active item">
              <img src="<?php echo $this->getSkinUrl('images/cool1.png');?>">               
           	  <div class="carousel-caption">
               <h3>First slide label</h3>                 
           	  </div>
          	</div>
         	<div class="item">
          	 <img src="<?php echo $this->getSkinUrl('images/cool2.png');?>">                
           	 <div class="carousel-caption">
           	  <h3>Second slide label</h3>                  
          	 </div>
         	</div>
           </div>
           <h2 class="skin-name"><?php echo $_category->getName();?></h2>
         <?php  
  		   }
		  }*/?>
  		<a class="carousel-control left" href="#case-slider<?php echo $iiCounter;?>" data-slide="prev">
      	 <i class="fa fa-angle-left fa-lg"></i>
     	</a>
     	<a class="carousel-control right" href="#case-slider<?php echo $iiCounter;?>" data-slide="next">
      	 <i class="fa fa-angle-right fa-lg"></i>
     	</a>    
    </div>
   </div>
   <?php
  }
 }?>
</div>