<?php 
$mode = Mage::getStoreConfig('featuredproduct/general/show_type');
$delay_time = Mage::getStoreConfig('featuredproduct/general/delay_time') * 1000;

$parentCategoryId = 24;
$cat = Mage::getModel('catalog/category')->load($parentCategoryId);
$subcats = $cat->getChildren();

$catIdArr = array();		   
	
function getSubcategoriesOfCategories2($catId)	
 { 
	global $catIdArr;
    $children = Mage::getModel('catalog/category')->getCategories($catId);
	foreach ($children as $category) {		 
	    $catIdArr[] = $category->getId();
		getSubcategoriesOfCategories2($category->getId());
	} 
	return $catIdArr; 
 }
 

function getFeaturedProductsCollection($pCatId,$styleId,$catIdArr)
 {
	 global $catIdArr;
     $catIdArr = array();
	 $catIdArr = getSubcategoriesOfCategories2($pCatId);
	  
				$products = Mage::getModel('catalog/product')->getCollection();
				$products->joinField(
					'qty',
					'cataloginventory/stock_item',
					'qty',
					'product_id=entity_id',
					'{{table}}.stock_id=1',
					'left'
				);
				$products->addAttributeToFilter('qty', array('neq' => 0));
				$products->addAttributeToFilter('fb_product', array('eq' => '1'));
				$products->addAttributeToFilter('status', 1);
				$products->addAttributeToFilter('visibility', 4);
				$products->addAttributeToSelect('sku');
			 
				$products->addAttributeToSelect('name');
				 
				$products->addAttributeToSelect('description');
				$products->addAttributeToSelect('short_description');
				$products->addAttributeToSelect('url');
				$products->addAttributeToSelect('image'); 
				$products->addAttributeToSelect('special_price');
				$products->addAttributeToSelect('manufacturer');
				$products->joinField('category_id',
					'catalog/category_product',
					'category_id',
					'product_id=entity_id',
					null,
					'left'
				);
			

		/*
         $catNum = 7; //The number of the category you want to load
		$category = Mage::getModel('catalog/category')->load($catNum);
		$products = Mage::getResourceModel('reports/product_collection')
		->addOrderedQty()
		->addAttributeToSelect('*')
		->setStoreId($storeId)
		->addStoreFilter($storeId)
		->addCategoryFilter($category);*/
				
	 $products->addAttributeToFilter('category_id', array('in' => $catIdArr));	 			 
	 $products->getSelect()->limit(5); 
 
 
     return $products;
 }
?>
<?php /*?><?php if (($products = $this->getProductCollection())): ?>
	<div id="fp" class="fp"  <?php if($mode != 'static'){?>style ="height:200px;"<?php }?>>
		<div id="slider" <?php if($mode == 'slider'){?>style ="margin-left:25px;"<?php }?>>
			<a name="sliderbutton" onclick="prevSlider()"class="slider-button left" href="#" <?php if($mode == 'slider2'){?>style ="display:block;"<?php }?>>&#139;</a>
			<div id="main-slider">
				<div id="frame">
					<?php $i = 0; foreach ($products->getItems() as $product): ?>
					<div  <?php if($mode != 'static'){?>style="width:410px; text-align:left; position:absolute; <?php if($i != 0){?>opacity:0; filter: alpha(opacity = 0); display:none;<?php }else{?> opacity:1; filter: alpha(opacity = 100); <?php } }?>" class="product-block" id="slider-<?php echo $i ?>" <?php if($mode == 'static'){?>onmouseover="showDes(<?php echo $i ?>, event)" onmouseout="hideDes()"<?php }?>>
						<h4><?php echo $this->htmlEscape($product->getName()) ?></h4>
						<a href="<?php echo $product->getProductUrl() ?>">
							<img class="product-image" src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(120, 120); ?>" <?php if($mode != 'static'){?>style ="float:left;"<?php }?>/>
						</a>
						
						<span class="product-info">
							<span class="product-des" id="des-<?php echo $i ?>" <?php if($mode != 'static'){?>style="display:inline;"<?php }?>>
								<?php echo substr($product->getShortDescription(), 0, 220); if(strlen($product->getShortDescription()) > 220) echo '...';?>
							</span>
							<?php echo $this->getPriceHtml($product, true) ?>
						</span>
					</div>
					<?php $i++; endforeach;?>
				</div>
			</div>
			<a name="sliderbutton" onclick="nextSlider()" class="slider-button right" href="#" <?php if($mode == 'slider2'){?>style ="display:block;"<?php }?>>&#155;</a>
		</div>
		<div id="popup-des"></div>
	</div>
<?php endif; ?> <?php */?>


<div class="row" id="home-cat-1">
  <h2 class="feature-tag">Featured Products</h2>
  <?php		 
   $iiCounter = 1;		 
    /*foreach(explode(',',$subcats) as $subCatid)
    {*/
      $_category = Mage::getModel('catalog/category')->load(3);
      if($_category->getIsActive()) 
      {
 
      ?>

       <div class="col-sm-4">         
 
       <div id="case-slider<?php echo $iiCounter;?>" class="carousel slide case-slide1" data-interval="false" data-ride="carousel">       
         <div class="carousel-inner">
		 
<?php
 $catIdArr = array();		
 $products = getFeaturedProductsCollection(3); 
		 
		  $i=1;
		  foreach($products as $product)
		  { ?>		 
              <div class="item <?php if($i == 1){ echo 'active';}?>">
            	<a href="<?php echo $product->getProductUrl();?>"><img src="<?php echo $product->getImageUrl();?>"></a>
            	 <div class="carousel-caption">
             		<h3><a href="<?php echo $product->getProductUrl();?>"><?php echo $product->getName();?></a></h3>                  
            	</div> 
           	  </div><?php 
			 $i++;
  }?>		  
         <?php /*?><div class="item">
          <img src="<?php echo $this->getSkinUrl('images/image.png');?>">                
          <div class="carousel-caption">
           <h3>Second slide label</h3>                  
          </div>
         </div>
         <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/military.png');?>">                
          <div class="carousel-caption">
           <h3>Third slide label</h3>                  
          </div>
         </div><?php */?>

        </div>
        <h2 class="skin-name"><?php echo $_category->getName();?></h2>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#case-slider<?php echo $iiCounter;?>" data-slide="prev">
         <i class="fa fa-angle-left fa-lg"></i>
        </a>
        <a class="carousel-control right" href="#case-slider<?php echo $iiCounter;?>" data-slide="next">
         <i class="fa fa-angle-right fa-lg"></i>
        </a>

     </div>
    
   </div>
  <?php  
  }/*$iiCounter++;
 }		
   */?>
   
   
  <?php		 
   $iiCounter = 2;		 
    /*foreach(explode(',',$subcats) as $subCatid)
    {*/
      $_category = Mage::getModel('catalog/category')->load(34);
      if($_category->getIsActive()) 
      {
 
      ?>

       <div class="col-sm-4">         
 
       <div id="case-slider<?php echo $iiCounter;?>" class="carousel slide case-slide1" data-interval="false" data-ride="carousel">       
         <div class="carousel-inner">
		 
<?php
 $catIdArr = array();		
 $products = getFeaturedProductsCollection(34); 
		 
		  $i=1;
		  foreach($products as $product)
		  { ?>		 
              <div class="item <?php if($i == 1){ echo 'active';}?>">
            	<a href="<?php echo $product->getProductUrl();?>"><img src="<?php echo $product->getImageUrl();?>"></a>
				<?php /*?> <img src="<?php echo $this->getSkinUrl('images/image.png');?>">    <?php */?>       
            	 <div class="carousel-caption">
             		<h3><a href="<?php echo $product->getProductUrl();?>"><?php echo $product->getName();?></a></h3>                  
            	</div> 
           	  </div><?php 
			 $i++;
  }?>		 
		 <?php /*?>
          <div class="active item">
           <img src="<?php echo $this->getSkinUrl('images/flora.png');?>">               
           <div class="carousel-caption">
            <h3>First slide label</h3>                 
           </div>
          </div>
         <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/image.png');?>">                
          <div class="carousel-caption">
           <h3>Second slide label</h3>                  
          </div>
         </div>
         <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/military.png');?>">                
          <div class="carousel-caption">
           <h3>Third slide label</h3>                  
          </div>
         </div>
		<?php */?>
        </div>
        <h2 class="skin-name"><?php echo $_category->getName();?></h2>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#case-slider<?php echo $iiCounter;?>" data-slide="prev">
         <i class="fa fa-angle-left fa-lg"></i>
        </a>
        <a class="carousel-control right" href="#case-slider<?php echo $iiCounter;?>" data-slide="next">
         <i class="fa fa-angle-right fa-lg"></i>
        </a>

     </div>
    
   </div>
  <?php  
  }/*$iiCounter++;
 }		
   */?>
   
   
   
   
   
   <?php		 
   $iiCounter = 3;		 
    /*foreach(explode(',',$subcats) as $subCatid)
    {*/
      $_category = Mage::getModel('catalog/category')->load(8);
      if($_category->getIsActive()) 
      {
 
      ?>

       <div class="col-sm-4">         
 
       <div id="case-slider<?php echo $iiCounter;?>" class="carousel slide case-slide1" data-interval="false" data-ride="carousel">       
         <div class="carousel-inner">
          <div class="active item">
           <img src="<?php echo $this->getSkinUrl('images/laptop-1.png');?>">               
           <div class="carousel-caption">
            <h3>First slide label</h3>                 
           </div>
          </div>
         <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/laptop-2.png');?>">                
          <div class="carousel-caption">
           <h3>Second slide label</h3>                  
          </div>
         </div>
         <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/laptop-3.png');?>">                
          <div class="carousel-caption">
           <h3>Third slide label</h3>                  
          </div>
         </div>
          <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/laptop-4.png');?>">                
          <div class="carousel-caption">
           <h3>Third slide label</h3>                  
          </div>
         </div>
          <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/laptop-5.png');?>">                
          <div class="carousel-caption">
           <h3>Third slide label</h3>                  
          </div>
         </div>
        </div>
        <h2 class="skin-name"><?php echo $_category->getName();?></h2>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#case-slider<?php echo $iiCounter;?>" data-slide="prev">
         <i class="fa fa-angle-left fa-lg"></i>
        </a>
        <a class="carousel-control right" href="#case-slider<?php echo $iiCounter;?>" data-slide="next">
         <i class="fa fa-angle-right fa-lg"></i>
        </a>

     </div>
    
   </div>
  <?php  
  }/*$iiCounter++;
 }		
   */?>
  
   
   
   
   
   
   
  <?php		 
   $iiCounter = 4;		 
    /*foreach(explode(',',$subcats) as $subCatid)
    {*/
      $_category = Mage::getModel('catalog/category')->load(4);
      if($_category->getIsActive()) 
      {
 
      ?>

       <div class="col-sm-8">         
 
       <div id="case-slider<?php echo $iiCounter;?>" class="carousel slide case-slide1" data-interval="false" data-ride="carousel">       
         <div class="carousel-inner">
          <div class="active item">
           <img src="<?php echo $this->getSkinUrl('images/t-shirt1.png');?>" style="float:left;">               
           <img src="<?php echo $this->getSkinUrl('images/t-shirt2.png');?>" style="float:left;">               
           <img src="<?php echo $this->getSkinUrl('images/t-shirt3.png');?>" style="float:left;">               
           <div class="carousel-caption">
            <h3>First slide label</h3>                 
           </div>
          </div>
         <div class="item">
           <img src="<?php echo $this->getSkinUrl('images/t-shirt4.png');?>" style="float:left;">               
           <img src="<?php echo $this->getSkinUrl('images/t-shirt5.png');?>" style="float:left;">               
           <img src="<?php echo $this->getSkinUrl('images/t-shirt6.png');?>" style="float:left;">               
          <div class="carousel-caption">
           <h3>Second slide label</h3>                  
          </div>
         </div>
         <div class="item">
           <img src="<?php echo $this->getSkinUrl('images/t-shirt7.png');?>" style="float:left;">               
           <img src="<?php echo $this->getSkinUrl('images/t-shirt2.png');?>" style="float:left;">               
           <img src="<?php echo $this->getSkinUrl('images/t-shirt8.png');?>" style="float:left;">               
          <div class="carousel-caption">
           <h3>Third slide label</h3>                  
          </div>
         </div>

        </div>
        <h2 class="skin-name"><?php echo $_category->getName();?></h2>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#case-slider<?php echo $iiCounter;?>" data-slide="prev">
         <i class="fa fa-angle-left fa-lg"></i>
        </a>
        <a class="carousel-control right" href="#case-slider<?php echo $iiCounter;?>" data-slide="next">
         <i class="fa fa-angle-right fa-lg"></i>
        </a>

     </div>
    
   </div>
  <?php  
  }/*$iiCounter++;
 }		
   */?>
   
   
   
   
 



  <?php		 
   $iiCounter = 5;		 
    /*foreach(explode(',',$subcats) as $subCatid)
    {*/
      $_category = Mage::getModel('catalog/category')->load(9);
      if($_category->getIsActive()) 
      {
 
      ?>

       <div class="col-sm-4">         
 
       <div id="case-slider<?php echo $iiCounter;?>" class="carousel slide case-slide1" data-interval="false" data-ride="carousel">       
         <div class="carousel-inner">
          <div class="active item">
           <img src="<?php echo $this->getSkinUrl('images/cool1.png');?>">               
           <div class="carousel-caption">
            <h3>First slide label</h3>                 
           </div>
          </div>
         <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/cool2.png');?>">                
          <div class="carousel-caption">
           <h3>Second slide label</h3>                  
          </div>
         </div>
        <?php /*?> <div class="item">
          <img src="<?php echo $this->getSkinUrl('images/cool3.png');?>">                
          <div class="carousel-caption">
           <h3>Third slide label</h3>                  
          </div>
         </div><?php */?>

        </div>
        <h2 class="skin-name"><?php echo $_category->getName();?></h2>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#case-slider<?php echo $iiCounter;?>" data-slide="prev">
         <i class="fa fa-angle-left fa-lg"></i>
        </a>
        <a class="carousel-control right" href="#case-slider<?php echo $iiCounter;?>" data-slide="next">
         <i class="fa fa-angle-right fa-lg"></i>
        </a>

     </div>
    
   </div>
  <?php  
  }/*$iiCounter++;
 }		
   */?>


 
   
   
   
</div>








<!--<script type="text/javascript">
var total = getBlocks().length;
var curIndex = 0;
var nextIndex;
var IE = document.all?true:false;

function nextSlider(){
	var blocks = getBlocks();
	for(var i = 0; i < blocks.length; i++){
		if(blocks[i].style.opacity == 1 || (IE && blocks[i].filters.alpha.opacity == 100)){
			//blocks[i].style.opacity = 0;
			if(i < blocks.length -1 )
				j = i + 1;
				//blocks[i+1].style.opacity = 1;
			else 
				j = 0;
				//blocks[0].style.opacity = 1;
			showSlider(i,j);
			break;
		}
	}
}
function prevSlider(){
	var blocks = getBlocks();
	for(var i = 0; i < blocks.length; i++){
		if(blocks[i].style.opacity == 1 || (IE && blocks[i].filters.alpha.opacity == 100)){
			//blocks[i].style.opacity = 0;
			if(i > 0)
				//blocks[--i].style.opacity = 1;
				j = i-1;
			else 
				//blocks[blocks.length-1].style.opacity = 1;
				j = blocks.length-1;
			showSlider(i,j);
			break;
		}
	}
}

function getBlocks(){
	var tempBlocks = document.getElementById('frame').getElementsByTagName('div');
	var blocks = new Array();
	var j = 0;
	for(var i = 0; i < tempBlocks.length; i++){
		if(tempBlocks[i].parentNode == document.getElementById('frame')){
			blocks[j] = tempBlocks[i];
			j++;
		}
	}
	return blocks;
}
<?php if($mode == 'slider'){ ?>
	var frame = document.getElementById('frame');
	var stopSlider;
	frame.onmouseover = function(){
		stopSlider = 1;
	}
	frame.onmouseout = function(){
		stopSlider = 0;
	}
	
	setInterval(function (){
		if(stopSlider)
			return;
		if(curIndex < total - 1)
			nextIndex = curIndex + 1;
		if(curIndex == total - 1)
			nextIndex = 0;
		showSlider(curIndex, nextIndex);
		
		setTimeout(function(){
			curIndex = nextIndex;
		}, 3000);
		
	}, <?php echo($delay_time); ?> )
<?php }?>
	//nextSlider(curIndex, nextIndex);
	function showSlider(curIndex,nextIndex){
		var curSlider = document.getElementById('slider-' + curIndex);
		var nextSlider = document.getElementById('slider-' + nextIndex);
		var i = 1000, j = 100;

		var curThread, nextThread;
		var IE = document.all?true:false;
		curThread = setInterval(function(){
			if(i >= 0){
				curSlider.style.opacity = i/1000;
				if(IE)
					curSlider.filters.alpha.opacity = i/10
				i -= 100;
				if(i == 0)
					curSlider.style.display = 'none';
			}
			else{
				if(j <= 1000){
					
					nextSlider.style.display = 'block';
					nextSlider.style.opacity = j/1000;
					if(IE)
						nextSlider.filters.alpha.opacity = j/10;
					j += 100;
					
				}
				else{
					clearInterval(curThread)
				}
			}
			
		}, 100)

	}
	
	function showDes(index, e){
		var popup = document.getElementById('popup-des');
		var des = document.getElementById('des-'+index);
		var content = des.innerHTML;
		popup.innerHTML = content;
		popup.style.display = 'block';
		
		var IE = document.all?true:false;
		if (!IE) document.captureEvents(Event.MOUSEMOVE)
	
		if (IE) { // grab the x-y pos.s if browser is IE
			tempX = event.clientX + document.body.scrollLeft;
			tempY = event.clientY + document.body.scrollTop;
		}
		else {  // grab the x-y pos.s if browser is NS
			tempX = e.pageX;
			tempY = e.pageY;
		}  
		if (tempX < 0){tempX = 0;}
		if (tempY < 0){tempY = 0;}  
		moveTo(popup, tempX, tempY);	
	}
	
	function moveTo(popup, tempX, tempY){
		popup.style.top = tempY+5+'px'
		popup.style.left = tempX +5+'px'
	}
	
	function hideDes(){
		var popup = document.getElementById('popup-des');
		popup.style.display = 'none';
	}
</script>-->