<div class="row" id="after-cr-design">
   <div class="col-sm-12">
      <h1> Create Your Own</h1>
      <h4>Choose from many premium products & customize it in infinite ways by adding text, images, color, vector etc. and create a memorabble product for yourself & your special   </h4>
    </div>
    <div class="col-sm-4">
      <div class="item-box-af"> <a href="<?php echo Mage::helper('cms/page')->getPageUrl(12)?>?catid=92">
        <div class="thumbnail thumb-1">                   
          <img src="<?php echo $this->getSkinUrl('images/create-t-shirt-man.png');?>"> </div>
        <h3>Guy's Tee </h3>
        </a> </div>
      <strong></strong> </div>
    <div class="col-sm-4">
      <div class="item-box-af"> <a href="<?php echo Mage::helper('cms/page')->getPageUrl(12)?>?catid=96">
        <div class="thumbnail thumb-2">                   
          <img src="<?php echo $this->getSkinUrl('images/create-t-shirt-women.png');?>"> </div>
        <h3>Girl's Tee </h3>
        </a> </div>
      <strong></strong> </div>
    <div class="col-sm-4">
      <div class="item-box-af"> <a href="<?php echo Mage::helper('cms/page')->getPageUrl(12)?>?catid=97">
        <div class="thumbnail thumb-3">                   
          <img src="<?php echo $this->getSkinUrl('images/create-t-shirt-kid.png');?>"> </div>
        <h3>Kid's/Teen Tee </h3>
        </a> </div>
      <strong></strong> </div>
  </div>
<div class="row">
            <div class="col-sm-3">
              <div class="item-box-af"> <a href="<?php echo Mage::getModel("catalog/category")->load(66)->getUrl();?>">
                <div class="thumbnail thumb-4">                 
                  <img src="<?php echo $this->getSkinUrl('images/create-case.png');?>"> </div>
                <h3>Mobile Case</h3>
                </a> </div>
              <strong></strong> </div>
            <div class="col-sm-3">
              <div class="item-box-af "> <a href="<?php echo Mage::getModel("catalog/category")->load(75)->getUrl();?>">
                <div class="thumbnail thumb-5">                
                  <img src="<?php echo $this->getSkinUrl('images/create-skin.png');?>"> </div>
                <h3>Mobile Skin</h3>
                </a> </div>
              <strong></strong> </div>
              <div class="col-sm-3">
              <div class="item-box-af"> <a href="<?php echo Mage::helper('cms/page')->getPageUrl(12)?>?catid=84">
                <div class="thumbnail thumb-6">
                  <img src="<?php echo $this->getSkinUrl('images/create-laptop.png');?>"> </div>
                <h3>Laptop Skin</h3>
                </a> </div>
              <strong></strong> </div>
            <div class="col-sm-3">
              <div class="item-box-af"> <a href="<?php echo Mage::getModel("catalog/category")->load(106)->getUrl();?>">
                <div class="thumbnail thumb-7">               
                  <img src="<?php echo $this->getSkinUrl('images/create-mug.png');?>"> </div>
                <h3>Mug</h3>
                </a> </div>
              <strong></strong> </div>  
              <div class="col-sm-3">
              <div class="item-box-af"> <a href="<?php echo Mage::getModel("catalog/category")->load(92)->getUrl();?>">
                <div class="thumbnail  thumb-8">                   
                  <img src="<?php echo $this->getSkinUrl('images/create-keychain.png');?>"> </div>
                <h3>Key Chain </h3>
                </a> </div>
              <strong></strong> </div>
              <div class="col-sm-3">
              <div class="item-box-af"> <a href="<?php echo Mage::getModel("catalog/category")->load(92)->getUrl();?>">
                <div class="thumbnail thumb-9">                   
                  <img src="<?php echo $this->getSkinUrl('images/create-poster.png');?>"> </div>
                <h3>Poster </h3>
                </a> </div>
              <strong></strong> </div>         
          </div>
    