<?php 
$cat_id = 56;
$_categories = Mage::getModel('catalog/category')->getCategories($cat_id);
$mainCat = Mage::getModel('catalog/category')->load($cat_id)->getName();
echo '<div id="after-cr-design"><div class="col-sm-12"><h1 class="pick_device">'.$mainCat.'</h1></div></div>';
$connection = Mage::getSingleton('core/resource')->getConnection('core_read');
if(count($_categories)):
?>
 <div id="shop_pg_cate" class="shop-section vf">
  <div class="row">
   <?php $i=1; foreach ($_categories as $_category):?>
    <?php 
    if($_category->getIsActive()):
     $cur_category = Mage::getModel('catalog/category')->load($_category->getId());
     $catName = $_category->getName();
	 $cat_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/';
     $_imageUrl = $cur_category->getImageUrl();	 
     if($_imageUrl == '')
       $_imageUrl = $cur_category->getThumbnail();
     if($_imageUrl != '')
     {
    ?>       
      <div class="col-md-6">
       <div class="skin-toggle gift">
        <div class="img-skin" id="mobileSkin">  
         <a href="<?php echo $cur_category->getUrl()?>" title="<?php echo $catName;?>">
          <img alt="<?php echo $catName;?>" src="<?php echo $cat_url.$_imageUrl;?>">
         </a> 
         <div class="skin-tab">
          <a href="<?php echo $cur_category->getUrl()?>" title="<?php echo $catName;?>">
           <div class="skin-title"><?php echo $catName;?></div>
          </a>        				
         </div>
        </div>
       </div> 
      </div>            
     <?php } ?>    
    <?php  endif;?>
   <?php $i++;endforeach ?>
  </div>
 </div>  
 
<?php endif; ?>