<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use/
 * @version      Release: 1.0.0
 * @since        Available since Release 1.0.0
 */
?>
<div class="content-header">
    <h3 class="icon-head head-categories"><?php echo ($this->getId() ? Mage::helper('gomage_designer')->__('Category: %s (#%s)', $this->getName(), $this->getId()) : $this->htmlEscape($this->getHeader())) ?></h3>
    <p class="content-buttons form-buttons">
        <?php if($this->getId()): ?>
            <?php echo $this->getDeleteButtonHtml() ?>
        <?php endif; ?>
        <?php echo $this->getAdditionalButtonsHtml(); ?>
        <?php echo $this->getSaveButtonHtml() ?>
    </p>
</div>
<div>
    <iframe name="iframeSave" style="display:none; width:100%;" src="<?php echo $this->getJsUrl() ?>blank.html"></iframe>
    <form target="iframeSave" id="cliparts_edit_form" action="<?php echo $this->getSaveUrl() ?>?isAjax=true" method="post" enctype="multipart/form-data">
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
        <input name="general[category_id]" type="hidden" value="<?php echo $this->getId(); ?>">
        <input name="general[parent_id]" type="hidden" value="<?php echo $this->getParentCategoryId(); ?>" />
        <input name="general[path]" type="hidden" value="<?php echo $this->getParentCategoryPath(); ?>" />
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Category Info');?></h4>
            </div>
            <div class="fieldset fieldset-wide">
                <table cellspacing="0" class="form-list">
                    <tbody>
                    <tr>
                        <td class="label"><label for="name"><?php echo $this->__('Category Name');?></label></td>
                        <td class="value">
                            <input type="text" id="name" name="general[name]" value="<?php echo $this->getName(); ?>" class="input-text required-entry" />
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <?php echo $this->getChildHtml('gallery'); ?>
    </form>
</div>

<script type="text/javascript">
//<![CDATA[
categoryForm = new varienForm('cliparts_edit_form');

categoryForm.submit= function (url) {
    this.errorSections = $H({});
    this.canShowError = true;
    this.submitUrl = url;
    if (this.validator && this.validator.validate()) {
        if(this.validationUrl){
            this._validate();
        }
        else{
            if (this.isSubmitted) {
                return false;
            }
            this.isSubmitted = true;
            this._submit();
        }
        displayLoadingMask();
        return true;
    }
    return false;
};

categoryForm.refreshPath = function () {

    categoryId = this.getCategoryId();

    if (!categoryId) {
        return false;
    }

    var refreshPathSuccess = function(transport) {
        if (transport.responseText.isJSON()) {
            response = transport.responseText.evalJSON()
            if (response.error) {
                alert(response.message);
            } else {
                if (categoryForm.getCategoryId() == response['id']) {
                    categoryForm.setCategoryPath(response['path']);
                }
            }
        }
    };

    new Ajax.Request(
        '<?php echo $this->getRefreshPathUrl() ?>',
        {
            method:     'POST',
            evalScripts: true,
            onSuccess: refreshPathSuccess
        }
    );

};

categoryForm.getCategoryId = function () {
    collection = $(this.formId).getInputs('hidden','general[id]');
    if (collection.size() > 0) {
        return collection.first().value;
    }
    return false;
};

categoryForm.setCategoryPath = function (path) {
    collection = $(this.formId).getInputs('hidden','general[path]');
    if (collection.size() > 0) {
        return collection.first().value = path;
    }
};

/**
 * Create/edit some category
 */
function categorySubmit(url, useAjax) {
    if(typeof useAjax === 'undefined') {
        useAjax = false;
    }
    if(useAjax === true) {
        url = url.replace('?isAjax=true', '') + '?isAjax=true';
    }

    var params = {};
    var fields = $('cliparts_edit_form').getElementsBySelector('input', 'select');
    for(var i=0;i<fields.length;i++){
        if (!fields[i].name) {
            continue;
        }
        params[fields[i].name] = fields[i].getValue();
    }

    // Get info about what we're submitting - to properly update tree nodes
    var categoryId = params['general[category_id]'] ? params['general[category_id]'] : 0;
    var isCreating = categoryId == 0; // Separate variable is needed because '0' in javascript converts to TRUE
    var path = params['general[path]'].split('/');
    var parentId = path.pop();
    if (parentId == categoryId) { // Maybe path includes category id itself
        parentId = path.pop();
    }

    // Make operations with category tree
    if (isCreating) {
        /* Some specific tasks for creating category */
        if (!tree.currentNodeId) {
            // First submit of form - select some node to be current
            tree.currentNodeId = parentId;
        }
        tree.addNodeTo = parentId;
    } else {
        /* Some specific tasks for editing category */
        // Maybe change category enabled/disabled style
        if (tree && tree.storeId==0) {
            var currentNode = tree.getNodeById(categoryId);
        }
    }

    // Submit form
    categoryForm.submit(url);
}
//]]>
</script>
