<?php
/*
$catArr = array(); 
$children = Mage::getModel('catalog/category')->getCategories(34);
foreach ($children as $category) 
{
	$children2 = Mage::getModel('catalog/category')->getCategories($category->getId());
	foreach ($children2 as $category2) { 
		$catArr[] = $category2->getId(); 
	}
} 
$count1 = count($catArr);  
$children = Mage::getModel('catalog/category')->getCategories(3);
foreach ($children as $category) {
	$children2 = Mage::getModel('catalog/category')->getCategories($category->getId());
	foreach ($children2 as $category2) {
 		$catArr[] = $category2->getId();
	}
}
$count2 = count($catArr);
*/
$read = Mage::helper('function/more')->getDbReadObject();
$write = Mage::helper('function/more')->getDbWriteObject();






/*
$sql = "Select * from amenu_update_tracking where up_flag_type = 'mobile_case'";
$rows = $read->fetchRow($sql); //fetchRow($sql), fetchOne($sql),...	
$mobile_case_cat_arr_url_key = explode(',',$rows['menu_cnt_top']);
$mobile_case_cat_arr_id = explode(',',$rows['menu_cnt_pop']);
$mobile_case_cat_arr_length = (count($mobile_case_cat_arr_url_key)-1);
$sql = "Select * from amenu_update_tracking where up_flag_type = 'mobile_skin'";
$rows = $read->fetchRow($sql); //fetchRow($sql), fetchOne($sql),...	
$mobile_skin_cat_arr_url_key = explode(',',$rows['menu_cnt_top']);
$mobile_skin_cat_arr_id = explode(',',$rows['menu_cnt_pop']);
$mobile_skin_cat_arr_length = (count($mobile_skin_cat_arr_url_key)-1);
*/
$siteBaseUrl = Mage::helper('function/more')->getBhishoomSiteBaseUrl();
//if($this->getItems()->getSize()): ?>
<?php /*?><link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/jcarousel.basic.css');?>" media="all" />
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.jcarousel.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jcarousel.basic.js') ?>"></script><?php */?>
<div class="rel-like">
 <h2>You may also like:</h2>
 
 <div class="row">
  <div class="col-md-12">
   <div class="relBlock">
    <div class="block block-related">
     <div data-example-id="related" role="tabpanel"  class="block-title bs-example bs-example-tabs">
      <ul role="tablist" id="relTab" class="rel-link nav nav-tabs">
       
		   <li role="presentation" class="nav active">
				<a aria-controls="profile" data-toggle="tab" id="related-tab" role="tab" aria-expanded="false" href="#related"><?php echo $this->__('Same Products') ?></a>
		   </li>
		   <li class="nav" role="presentation">
				<a aria-expanded="true" aria-controls="home" data-toggle="tab" role="tab" id="similer-tab" href="#similer"><?php echo $this->__('Other Products') ?></a>
		   </li>
       
      </ul>        
     </div>   
    <div class="clearfix"></div>  
    <div class="row"><div class="col-md-12 col-md-offset-0 col-xs-12 col-xs-offset-0"> <div class="tab-content" id="myTabContent">
      
       <div aria-labelledby="related-tab" class="tab-pane fade active in" role="tabpanel" id="related">
         <div id="owl-example1" class="owl-carousel1">
          
           <?php 
            $cat_id1 = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
            $product_id = Mage::registry('current_product')->getId();
			$product_sku = Mage::registry('current_product')->getSku();

					$query = 'SELECT realted_product_skus FROM a_related_products WHERE cat_id = "'. $cat_id1 . '" and product_sku = "'.$product_sku.'" LIMIT 1';
					$tableRowSkus = $read->fetchOne($query);

					
			
            $prod_coll = get_prod_collection($cat_id1, $product_id, $tableRowSkus);
            $r=1;
            $_category = Mage::registry('current_category');
            $blank_backImagePath = '';
			
$path = $_category->getPath();
$cat_url_key = $_category->getUrlKey();
$ids=explode('/',$path);

if(in_array(3,explode('/',$path)) || in_array(66,explode('/',$path))){

	$blankImageParentFolderName='mobile-case';

	$imageType='back';
	$imageName='mask.png';

	$mediaFolderurl = Mage::getBaseUrl('media').'blank_images/'.$blankImageParentFolderName.'/'.$cat_url_key.'/resized/';
	$blank_backImagePath = $mediaFolderurl.'mask.png';

}
else if(in_array(34,explode('/',$path)) || in_array(75,explode('/',$path))){

	$blankImageParentFolderName='mobile-skin';
	$imageType='front-back';
	$imageName='mask-front.png';
	$imageName2='mask-back.png';

	$mediaFolderurl = Mage::getBaseUrl('media').'blank_images/'.$blankImageParentFolderName.'/'.$cat_url_key.'/resized/';
	$blank_backImagePath = $mediaFolderurl.'mask-back.png';
	$blank_frontImagePath_1 = $mediaFolderurl.'mask-front.png';

}
else if(in_array(4,explode('/',$path)) || in_array(91,explode('/',$path))){	
	$blankImageParentFolderName='';
}
else if(in_array(477,explode('/',$path)) || in_array(1144,explode('/',$path))){
	$blankImageParentFolderName='';
}
else if(in_array(8,explode('/',$path)) || in_array(84,explode('/',$path))){

	$blankImageParentFolderName='laptop-skin';
	$imageType='back';
	$imageName='mask.png';

	$mediaFolderurl = Mage::getBaseUrl('media').'blank_images/'.$blankImageParentFolderName.'/'.$cat_url_key.'/resized/';
	$blank_backImagePath = $mediaFolderurl.'mask.png';

}
else if(in_array(478,explode('/',$path)) || in_array(532,explode('/',$path))){

	$blankImageParentFolderName='tablet-skin';
	$imageType='front-back';
	$imageName='mask-front.png';
	$imageName2='mask-back.png';

	$mediaFolderurl = Mage::getBaseUrl('media').'blank_images/'.$blankImageParentFolderName.'/'.$cat_url_key.'/resized/';
	$blank_backImagePath = $mediaFolderurl.'mask-back.png';
	$blank_frontImagePath_1 = $mediaFolderurl.'mask-front.png';

}
			
			
            foreach($prod_coll as $products)
            {
              $name = $products->getName();
              $image = $products->getImageUrl();
              $url = $products->getProductUrl();?>
              
               <div>                                  
      	          <a href="<?php echo $url; ?>" title="<?php echo $name; ?>" class="product-image">
				<?php
				   if($blank_backImagePath != ''){
					  echo '<img src="'.$blank_backImagePath.'" class="graPosAbsoulte" />';
				   }
				?>	
                   <img src="<?php echo Mage::helper('catalog/image')->init($products, 'small_image')->resize(245);?>" alt="<?php echo $name;?>" /></a>
                   <div class="product-details"><p class="product-name"><a href="<?php echo $url;?>"><?php echo $name;?></a></p></div> 
                 </div>             
                          			 
                <?php	$r++; 
               } ?>
               
               </div>
             
     	   </div>
		   <div aria-labelledby="similer-tab" class="tab-pane fade" role="tabpanel" id="similer">
	  
	  
	  
      <div id="owl-example" class="owl-carousel">
		  <?php 
		  
		$query = 'SELECT related_cat_ids FROM a_other_products WHERE cat_id = "'. $cat_id1 . '" and product_sku = "'.$product_sku.'" LIMIT 1';
		$tableRowSkus = $read->fetchOne($query);

		  $related_cat_ids = $read->fetchOne($query);
		  
		  
		$query = 'SELECT realted_product_skus	 FROM a_other_products WHERE cat_id = "'. $cat_id1 . '" and product_sku = "'.$product_sku.'" LIMIT 1';
		$tableRowSkus = $read->fetchOne($query);

		  $realted_product_skus	 = $read->fetchOne($query);
		  $realted_product_skus	= explode(';',$realted_product_skus	);
		  
		  
		  if(trim($related_cat_ids)!= '')
		  $cats_id = explode(';',$related_cat_ids);
		  else
		  $cats_id = array(34, 3, 8, 39, 477);
	  
          $cat_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getParentCategory()->getParentCategory()->getId();
          $category = Mage::getModel('catalog/category')->load($cat_id); 
          $id = $category->getId();
         // echo '<ul>';
		  //for($k=0;$k<2;$k++)
		  //{
          	for($i=0;$i<count($cats_id);$i++)
          	{
				if($cats_id[$i] == $id)
              	{ 
                	continue;
              	}
              	else
             	{
					
					if(trim($related_cat_ids) == '')
					{
						$path = array();
					}	
					else{
					$category = Mage::getModel('catalog/product')->load($cats_id[$i])->getCategory();
					$path = explode('/', $category->getPath());					
					}
				   	if(trim($related_cat_ids) == '')
						$productslist = get_prod('',$cats_id[$i]);
					else			
						$productslist = get_prod($realted_product_skus[$i],$cats_id[$i]);
				  foreach($productslist as $product)
				  {
					 $name = $product->getName();
					 $image = $product->getImageUrl();
					 $url = $product->getProductUrl();
					 $imagePath = array();
					 $blank_backImagePath = '';
					 
					 
					 
					 
					?>
				
					  <div>                				
					<?php 		 //echo $cats_id[$i];
					  //if($cats_id[$i] == 3)
					  if(in_array(3,$path) || $cats_id[$i] == 3)
					  {
						  /*$get_random_cat = rand(0,$mobile_skin_cat_arr_length); 
						  while(!is_file(Mage::getBaseDir('media').'/blank_images/mobile-skin/'.$mobile_skin_cat_arr_url_key[$get_random_cat].'/mask-back.png'))
						  {
							$get_random_cat = rand(0,$mobile_skin_cat_arr_length);		
						  }		
						  $blank_backImagePath = Mage::helper('function')->getRandomMobileSkinBlankImage($mobile_skin_cat_arr_url_key[$get_random_cat]);
						  $categoryObjForUrl = Mage::getSingleton('catalog/category')->load($mobile_skin_cat_arr_id[$get_random_cat]);				  
						  $url = Mage::helper('function')->getUrlPath($product,$categoryObjForUrl);*/
						  $blankImageParentFolderName='mobile-case';
						  $get_random_cat = $cats_id[$i];
						  
						  if(trim($related_cat_ids) == '')
						  $get_random_cat = 11;
					  
						  $_category = Mage::getSingleton('catalog/category')->load($get_random_cat);	
						  //$blank_backImagePath = Mage::helper('function')->getRandomMobileCaseBlankImage($categoryObjForUrl->getUrlKey());
						  
						  $cat_url_key = $_category->getUrlKey();
						  
						  $mediaFolderurl = Mage::getBaseUrl('media').'blank_images/'.$blankImageParentFolderName.'/'.$cat_url_key.'/resized/';
						  $blank_backImagePath = $mediaFolderurl.'mask.png';

						  $url = Mage::helper('function')->getUrlPath($product,$_category);
						  
					   }
					   //else if($cats_id[$i] == 34)
					   else if(in_array(34,$path) || $cats_id[$i] == 34)
					   { 
							/*$get_random_cat = rand(0,$mobile_skin_cat_arr_length); 
							while(!is_file(Mage::getBaseDir('media').'/blank_images/mobile-skin/'.$mobile_skin_cat_arr_url_key[$get_random_cat].'/mask-back.png'))
							{
								$get_random_cat = rand(0,$mobile_skin_cat_arr_length);		
							}		
							$blank_backImagePath = Mage::helper('function')->getRandomMobileSkinBlankImage($mobile_skin_cat_arr_url_key[$get_random_cat]);
							$categoryObjForUrl = Mage::getSingleton('catalog/category')->load($mobile_skin_cat_arr_id[$get_random_cat]);				  
							$url = Mage::helper('function')->getUrlPath($product,$categoryObjForUrl);*/
							//$get_random_cat = rand(0,$mobile_skin_cat_arr_length);
							$blankImageParentFolderName='mobile-skin';
							$get_random_cat = $cats_id[$i];
							
							  if(trim($related_cat_ids) == '')
							  $get_random_cat = 1141;							
							
							$_category = Mage::getSingleton('catalog/category')->load($get_random_cat);	
							//$blank_backImagePath = Mage::helper('function')->getRandomMobileSkinBlankImage($categoryObjForUrl->getUrlKey());
							
							$cat_url_key = $_category->getUrlKey();
							
							$mediaFolderurl = Mage::getBaseUrl('media').'blank_images/'.$blankImageParentFolderName.'/'.$cat_url_key.'/resized/';
							$blank_backImagePath = $mediaFolderurl.'mask-back.png';
										  
							$url = Mage::helper('function')->getUrlPath($product,$_category);
							
					   }
					   //else if($cats_id[$i] == 8 || $cats_id[$i] == 478)
					   else if(in_array(8,$path) || in_array(478,$path)  || $cats_id[$i] == 8 || $cats_id[$i] == 478)   	   
					   { 	
						   //$rand = rand(0,($count2-1));
						  //echo 'hello and that is very.';
						  
						  if(in_array(478,$path) || $cats_id[$i] == 478){
							  $urlCatid = $cats_id[$i]; 
							  if(trim($related_cat_ids) == '')
								  $urlCatid = 477; 
						  }
						  elseif(in_array(8,$path) || $cats_id[$i] == 8){
							  $urlCatid = $cats_id[$i]; 
							  
							  if(trim($related_cat_ids) == '')
								  $urlCatid = 972; 							  
						  }
						  
						  //$imagePath = Mage::helper('function')->getBlankFrontBackImages($cats_id[$i],200,300);
						  //$blank_backImagePath = $imagePath[0];
						  $_category = Mage::getSingleton('catalog/category')->load($urlCatid);
						  
						  $cat_url_key = $_category->getUrlKey();
						  
						  $url = Mage::helper('function')->getUrlPath($product,$_category);
						}
					   //else if($cats_id[$i] == 39)
					   else if(in_array(39,$path) || $cats_id[$i] == 39)   
					    {
						  $_category = Mage::getSingleton('catalog/category')->load($cats_id[$i]);
						  
						  $cat_url_key = $_category->getUrlKey();
						  
						  $url = Mage::helper('function')->getUrlPath($product,$_category);
						}
						?>					
						<a href="<?php echo $url; ?>" title="<?php echo $name; ?>" class="product-image">
						<?php
						 if($blank_backImagePath != '' && is_url_exist_bhishoom($blank_backImagePath))
						 {
						   echo '<img src="'.$blank_backImagePath.'" class="graPosAbsoulte" />';
						 }
						 ?>					
						  <img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image')->resize(245);?>" alt="<?php echo $name;?>" /></a> 
						 <div class="product-details"><p class="product-name"><a href="<?php echo $url;?>"><?php echo $name;?></a></p></div>  
						</div>                  
					              			 
					   <?php	 
						}			
			  	}
			}
		  //}
         // echo '</ul>';?>         
	             
       	</div>
	   </div>    
		   </div></div>
           <div class="clearfix"></div>  
<script type="text/javascript">
	 jQuery(document).ready(function() {
		 
		 
    var parent = jQuery("#owl-example");
    var divs = parent.children();
    while (divs.length) {
        parent.append(divs.splice(Math.floor(Math.random() * divs.length), 1)[0]);
    }		 
		 
		 
		 
		 
		 
    jQuery("#owl-example").owlCarousel({
    items : 4,
    navigation : true
	/*
		 itemsDesktop : [1199, 8],
        itemsDesktopSmall : [979, 6],
        itemsTablet : [768, 6],
        itemsTabletSmall : false,
        itemsMobile : [479, 6],
		*/
  }); 
 
});
jQuery(document).ready(function() {
    jQuery("#owl-example1").owlCarousel({
    items : 4,
    navigation : true
  }); 
 
});
	
 
      //<![CDATA[
      /*$$('.related-checkbox').each(function(elem){
          Event.observe(elem, 'click', addRelatedToProduct)
      });
      var relatedProductsCheckFlag = false;
      function selectAllRelated(txt){
       if (relatedProductsCheckFlag == false) {
          $$('.related-checkbox').each(function(elem){
            elem.checked = true;
          });
          relatedProductsCheckFlag = true;
           txt.innerHTML="<?php echo $this->__('unselect all') ?>";
          } else {
              $$('.related-checkbox').each(function(elem){
                  elem.checked = false;
              });
              relatedProductsCheckFlag = false;
              txt.innerHTML="<?php echo $this->__('select all') ?>";
          }
          addRelatedToProduct();
      }  
      function addRelatedToProduct(){
          var checkboxes = $$('.related-checkbox');
          var values = [];
          for(var i=0;i<checkboxes.length;i++){
              if(checkboxes[i].checked) values.push(checkboxes[i].value);
          }
          if($('related-products-field')){
              $('related-products-field').value = values.join(',');
          }
      }*/
      //]]>	
	  /*
      jQuery('#relTab a').click(function (e) {
		e.preventDefault()
		jQuery(this).tab('show')
      })
	   jQuery('.carousel').carousel();*/
</script>
<style>
#owl-example .item{
  margin: 0px;
}
#owl-example .item img{
  display: block;
  width: 100%;
  height: auto;
}
	 </style>
   </div>
   </div>
  </div>
 </div>
</div>
<?php //endif ?>
<?php
function get_prod($realted_product_skus,$cat_id)
{
	$rand_page = rand(1,9);
	
	if($realted_product_skus!='')
	{
		$products = Mage::getModel('catalog/category')->load($cat_id); //put your category id here
		$productslist = $products->getProductCollection()->addAttributeToFilter('sku', array('eq' => $realted_product_skus))->addAttributeToSelect(array('name','small_image','url_key'))->setPageSize(1);		
	}	
	else{
	$products = Mage::getModel('catalog/category')->load($cat_id); //put your category id here
    $productslist = $products->getProductCollection()->addAttributeToSort('position')->addAttributeToSelect(array('name','small_image','url_key'));
	
		$productslist->getSelect()->limit(50);
		$productslist->getSelect()->order(new Zend_Db_Expr('RAND()'));
		$productslist->getSelect()->limit(5);	
	
	
	}
	//$productslist->getSelect()->order(new Zend_Db_Expr('RAND()')); 
	return $productslist ;
}

function get_prod_collection($cat_id1, $prod_id, $tableRowSkus)
{
	$tableRowSkusArr = explode(";",$tableRowSkus);	
	//print_r($tableRowSkusArr);exit;
	if(count($tableRowSkusArr) > 0 && trim($tableRowSkus) != ''){
		$prod_collection = Mage::getModel('catalog/category')->load($cat_id1); //put your category id here
		$collection  = $prod_collection->getProductCollection()->addAttributeToFilter('sku', array('in' => $tableRowSkusArr))->addAttributeToSelect(array('name','small_image','url_key'));	
		$collection->getSelect()->order(new Zend_Db_Expr('FIELD(sku, "' . implode('","', $tableRowSkusArr) . '")'));
	}
	else{
		
		$rand_page = rand(1,9);
		
		
		$prod_collection = Mage::getModel('catalog/category')->load($cat_id1); //put your category id here
		$collection  = $prod_collection->getProductCollection()->addAttributeToSort('position')->addAttributeToSelect(array('name','small_image','url_key'));
		
		$collection->getSelect()->limit(100);
		$collection->getSelect()->order(new Zend_Db_Expr('RAND()'));
		$collection->getSelect()->limit(20);
	}
	
	return $collection ;
}

function is_url_exist_bhishoom($url){
    $ch = curl_init($url);    
    curl_setopt($ch, CURLOPT_NOBODY, true);
    curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

    if($code == 200){
       $status = true;
    }else{
      $status = false;
    }
    curl_close($ch);
   return $status;
}
?>