<?php if (Mage::getStoreConfig('trackorder/trackorder_general/enabled')) { ?>

    <div class = "block block-trackorder">
        <div class = "block-title">
            <strong><span>Track Order Here</span></strong>
        </div>
        <div class = "block-content">
            
                 <label for = "widget"><a target="_blank" href="<?php echo Mage::helper('function/more')->getBhishoomSiteBaseUrl() . 'trackorder/index'; ?>"> Track Order</a></label>
            
        </div>
    </div>


<?php } ?>
