<?php
  $siteBaseUrl = Mage::helper('function/more')->getBhishoomSiteBaseUrl();  

  $displayOrderTable=Mage::getStoreConfig('tab1/order_information_system/display_order_table');
  $displayProductImage=Mage::getStoreConfig('tab1/order_information_system/display_product_image');
  $displayDiscount=Mage::getStoreConfig('tab1/order_information_system/display_discount');
  $displayShippingRate=Mage::getStoreConfig('tab1/order_information_system/display_shipping_rates');
  $displayTax=Mage::getStoreConfig('tab1/order_information_system/display_tax');
  $displayCmsBlockAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_above');
  $cmsBlockIdAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_above');
  $displayCmsBlockBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_below');
  $cmsBlockIdBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_below');
  $newsLetter=Mage::getStoreConfig('tab1/newsletter_subscription_section/display_section');

  $_coreHelper = $this->helper('core');

  $displayOrderTable=Mage::getStoreConfig('tab1/order_information_system/display_order_table');
  $displayProductImage=Mage::getStoreConfig('tab1/order_information_system/display_product_image');
  $displayDiscount=Mage::getStoreConfig('tab1/order_information_system/display_discount');
  $displayShippingRate=Mage::getStoreConfig('tab1/order_information_system/display_shipping_rates');
  $displayTax=Mage::getStoreConfig('tab1/order_information_system/display_tax');
  $displayCmsBlockAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_above');
  $cmsBlockIdAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_above');
  $displayCmsBlockBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_below');
  $cmsBlockIdBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_below');
  $newsLetter=Mage::getStoreConfig('tab1/newsletter_subscription_section/display_section');

  $_coreHelper = $this->helper('core');
 
  
  
    if($this->getOrderId()):
      $orderObj = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
	  
      $lastOrder = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId());
      $billingAddress = $lastOrder->getBillingAddress();
      $shippingAddress = $lastOrder->getShippingAddress();
      $payment_method = $lastOrder->getPayment()->getMethodInstance()->getTitle();
      $payment_method_code = $lastOrder->getPayment()->getMethodInstance()->getCode();
	  
	  
	  //echo $orderObj->getFeeAmount();
	  
?>

<div class="thanks-outer" id="thanks-order-page">
  <?php if($this->getTopBlock()!=false): ?>
  <?php if($displayCmsBlockAbove==1): ?>
  <div class="order-cms-block block1">
    <?php
      echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getTopBlock())->toHTML();
    ?>
  </div>
  <?php
     endif;
  endif;
?>
  <div class="thanks-inner">
    <div class="page-title thank">
      <h1><?php echo $this->__('Thank you for your order!') ?></h1>
    </div>
    <?php
    echo $this->getMessagesBlock()->getGroupedHtml() 
?>
    <div class="thanks-msz">
      <?php if($payment_method_code == 'phoenix_cashondelivery'){?>
      <h3>We will call you shortly!</h3>
      <p>Our team will call you within 24hrs for order confirmation.<br/>
        Your COD order will be processed after the confirmation call.</p>
      <?php }else{?>
      <h3>We will dispatch your order shortly !</h3>
      <p>A confirmation email has been sent to <a href="mailto:<?php echo $billingAddress["email"]?>"><?php echo $billingAddress["email"]?></a></p>
      <?php }?>
    </div>
    <div class="thkbox">
      <?php /*?><div class="thk-box1">
        <div class="outer-box">
          <h3><?php echo $this->__('Thank you for your order!') ?></h3>
          <div class="inner-box-1">
            <?php if($this->getOrderId()): ?>
            <?php if($this->getCanViewOrder()): ?>
            <?php  else: ?>
            <?php endif; ?>
            <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
            <?php if($this->getCanViewOrder() && $this->getCanPrintOrder()): ?>
            <?php echo $this->getChildHtml() ?>
            <?php endif; ?>
            <?php endif; ?>
            <a class="button btn-continue btn-inline" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>" title="<?php echo $this->__('Continue Shopping') ?>" ><span><span><?php echo $this->__('Continue Shopping') ?></span></span></a> </div>
        </div>
      </div><?php */?>
      <div class="section-title-big">
        <h2><?php echo $this->__('Order Summary') ?></h2  >
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="section-title">
            <h3>
              <?php if($shippingAddress['firstname']!= ''){?>
              <?php echo $this->__('Shipping Address') ?></h3>
            <?php }?>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
          <div class="inner-box-1">
            <?php if($shippingAddress['firstname']!= ''){?>
            <table class="table">
              <tr>
                <td><h3>
                    <?php 
        $country_name=Mage::app()->getLocale()->getCountryTranslation($shippingAddress['country_id']);        
        echo $shippingAddress['prefix'].' '.$shippingAddress['firstname'].' '.$shippingAddress['lastname'];
    ?>
                  </h3></td>
              </tr>
              <tr>
              <tr>
                <td><?php echo $shippingAddress['street']; ?>,<br/>
                  <?php echo $shippingAddress['city']; ?> - <?php echo $shippingAddress['postcode']; ?> (<?php echo $shippingAddress['region']; ?>) <?php echo $country_name; ?><br/>
                  <span style="width:62px;display:inline-block;">Mobile</span>: <?php echo $shippingAddress['telephone']; ?><br/>
                  <span style="width:62px;display:inline-block;">Email</span>: <?php echo $shippingAddress['email']; ?></td>
              </tr>
              <?php /*?>
<tr>
  <td><?php echo $shippingAddress['region']; ?>, Country - <?php echo $shippingAddress['country_id']; ?> </td>
</tr>
<?php */?>
            </table>
            <?php }?>
            <?php endif; ?>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="inner-box-1 order-table">
            <?php /*?><?php if($this->getOrderId()): ?>
            <?php echo $this->__('<a href="%s" onclick="this.target=\'_blank\'" class="button print-icon" title="Print Details">Print Details</a>', $this->getPrintUrl()) ?> <?php echo $this->getChildHtml() ?>
            <?php endif; ?><?php */?>
            <?php //******************************Order Summary *********************** ?>
            <table class="table">
              <?php
        if($this->getOrderId()):
          $orderObj = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
          $lastOrder = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId());
          $billingAddress = $lastOrder->getBillingAddress();
          $shippingAddress = $lastOrder->getShippingAddress();
          ?>
              <tr >
                <td><label><strong><?php echo $this->__('Date') ?></strong></label></td>
                <td><span class="sep">:</span></td>
                <td align="left"><span><?php echo $orderObj->getCreatedAtStoreDate(); ?></span></td>
              </tr>
              <tr>
                <td><label><strong><?php echo $this->__('Order Id') ?></strong></label></td>
                <td><span class="sep">:</span></td>
                <td align="left"><span>
                  <?php if($this->getCanViewOrder()): ?>
                  <?php echo $this->__(sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?>
                  <?php else: ?>
                  <?php echo $this->__($this->escapeHtml($this->getOrderId())) ?>
                  <?php endif; ?>
                  <?php echo $this->getChildHtml() ?> </span></td>
              </tr>
              <tr>
                <td><label><strong><?php echo $this->__('Order Amount') ?></strong></label></td>
                <td><span class="sep">:</span></td>
                <td align="left"><span><?php echo $_coreHelper->formatPrice($orderObj->getGrandTotal(),true) ?></span></td>
              </tr>
              <tr>
                <td><label><strong><?php echo $this->__('Payment Method') ?></strong></label></td>
                <td><span class="sep">:</span></td>
                <td align="left"><span><?php echo $payment_method ?></span></td>
              </tr>
              <?php endif; ?>
            </table>
          </div>
        </div>
      </div>
      <div class="clear"></div>
      <?php /*?><?php if($this->getOrderId()): ?>
      <?php echo $this->__('<a href="%s" onclick="this.target=\'_blank\'" class="btn btn-danger" title="Print Details">Print Details</a>', $this->getPrintUrl()) ?> <?php echo $this->getChildHtml() ?>
      <?php endif; ?>
      <div class="clear"></div><?php */?>
    </div>
    <?php 
//**********************************Order Details***************************
if($displayOrderTable==1):
  if($this->getOrderId()):
    $orderItems = $orderObj->getAllVisibleItems();
    ?>
    <div class="row">
      <div class="col-sm-12">
        <div class="section-title ">
          <h3 class="pull-left"><?php echo $this->__('Item Details') ?></h3>
          <h3 class="pull-right"><?php echo $this->__('Sub Total') ?></h3>
          <div class="clearfix"></div>
        </div>
        <?php foreach($orderItems as $items)
    {
		
	
		
      $_product = Mage::getModel('catalog/product')->load($items->getProductId());
      $product_small_image_path = Mage::helper('catalog/image')->init($_product,'small_image')->resize(75);
      
	  
	  
	  

	  
	  //$designOption = $items->getOptionByCode('design');
	  $opts = $items->getProductOptions();
	 	  
	   
	  if($opts["simple_sku"] != ''){
	  $product_small_image_path = Mage::helper('catalog/image')->init(Mage::getModel('catalog/product')->load(Mage::getModel('catalog/product')->getResource()->getIdBySku($opts["simple_sku"])),'small_image')->resize(75);  
	  } 
	  
	  $designId = '';
	  
        if ($opts["info_buyRequest"]["design"] > 0) {
             $designId = $opts["info_buyRequest"]["design"];
        }
        if ($designId) {
            if ($image = Mage::getModel('gomage_designer/design')->getDesignThumbnailImage($designId)) {
                $product_small_image_path = $this->helper('gomage_designer/image_design')->init($image);
				$product_small_image_path = str_replace('cache/','',$product_small_image_path);
				//$product_small_image_path = $product_small_image_path->resize(75);
            }
			else
			$product_small_image_path = $this->getProductThumbnail();
        }	  

		
	  $itemsInfoArray = $items->getData();
	  
	  $blank_backImagePath = '';
	  ///////////////////////////////////////Item front and back image path///////////////////////////////////
 			$folderURL = Mage::helper('function')->graGetFolderUrl($itemsInfoArray["prdUrl"]);
			$folderPath = Mage::helper('function')->graGetFolderPath($itemsInfoArray["prdUrl"]);

		if(is_file($folderPath . DS . 'mask-back.png')){		
			if(!is_file($folderPath . DS . 'resized75' . DS . 'mask-back.png'))
			{
			   $blank_backImagePath = Mage::helper('function')->resizeImg('mask-back.png', 75, 75,$folderURL,$folderPath,'resized75');
			}
			else
			{
				$blank_backImagePath = $folderURL . '/' . 'resized75' . '/' . 'mask-back.png';
			}
		}
		elseif(is_file($folderPath . DS . 'mask.png')){
			if(!is_file($folderPath . DS . 'resized75' . DS . 'mask.png'))
			{
			   $blank_backImagePath = Mage::helper('function')->resizeImg('mask.png', 75, 75,$folderURL,$folderPath,'resized75');
			}
			else
			{
				$blank_backImagePath = $folderURL . '/' . 'resized75' . '/' . 'mask.png';
			}
		}
      /////////////////////////////////////////////////////////////////////////////////////////////////////////
      
    ?>
        <table class="table">
          <tr>
            <td colspan="2" ><?php if($displayProductImage==1): ?>
              <table class="table no-border">
                <tbody>
                  <tr>
                    <td width="14%"><span class="product-image-success">
                      <?php	if($blank_backImagePath != ''){?>
                      <?php /*?><a href="<?php echo $itemsInfoArray["prdfullUrl"]?>"><?php */?><img src="<?php echo $blank_backImagePath;?>" width="75" height="75" style="position:absolute"><?php /*?></a><?php */?>
                      <?php } ?>
                      <img src="<?php echo $product_small_image_path ?>" width="75" height="75" align="<?php echo $items->getName(); ?>"/> </span></td>
                    <td><?php endif; ?>
                      <div class="product-name"> <?php /*?><a href="<?php echo $itemsInfoArray["prdfullUrl"]?>" id="<?php echo $items->getProductId();?>"> <?php */?><?php echo $items->getName(); ?> <?php /*?></a><?php */?>
                        <?php 
              
              /*echo '<pre>';
              print_r($opts);*/
              echo '<br/>';
              foreach($opts['options'] as $optsVal)
              {
                if(trim($optsVal['label']) == 'Product Detail')
                {
                  $explodeArray = explode('/',$optsVal['value']);
                  $category = Mage::getModel('catalog/category')->load($explodeArray[count($explodeArray)-1]);
                  $urlPath = Mage::helper('function')->getUrlPath($_product, $category);
/*				  
?>                  
<script type="text/javascript">
jQuery('#<?php echo $items->getProductId();?>').attr('href','<?php echo $urlPath;?>');
</script>                 
<?php
*/
                  continue;
                } 
                echo '<span class="fontSize11px fontStyleItalic"><strong>'.$optsVal['label'].': </strong></span><span class="fontSize11px fontStyleItalic fontStyleNormal">'.$optsVal['value'].'</span><br/>';                
              }
              foreach($opts['attributes_info'] as $optsVal)
              {
/*                if(trim($optsVal['label']) == 'Product Detail')
                {
                  $explodeArray = explode('/',$optsVal['value']);
                  $category = Mage::getModel('catalog/category')->load($explodeArray[count($explodeArray)-1]);
                  $urlPath = Mage::helper('function')->getUrlPath($_product, $category);
				  
?>                  
<script type="text/javascript">
jQuery('#<?php echo $items->getProductId();?>').attr('href','<?php echo $urlPath;?>');
</script>                 
<?php

                  continue;
                } */
                echo '<span class="fontSize11px fontStyleItalic"><strong>'.$optsVal['label'].': </strong></span><span class="fontSize11px fontStyleItalic fontStyleNormal">'.$optsVal['value'].'</span><br/>';                
              }
              foreach($opts['info_buyRequest'] as $optsKey => $optsVal)
              {
                if(trim($optsKey) == 'recipient_name')
                echo '<span class="fontSize11px fontStyleItalic"><strong>Recipient Name: </strong></span><span class="fontSize11px fontStyleItalic fontStyleNormal">'.$optsVal.'</span><br/>';                
                if(trim($optsKey) == 'recipient_email')
                echo '<span class="fontSize11px fontStyleItalic"><strong>Recipient Email:: </strong></span><span class="fontSize11px fontStyleItalic fontStyleNormal">'.$optsVal.'</span><br/>';                
                if(trim($optsKey) == 'recipient_phone')
                echo '<span class="fontSize11px fontStyleItalic"><strong>Recipient Phone:: </strong></span><span class="fontSize11px fontStyleItalic fontStyleNormal">'.$optsVal.'</span><br/>';                
                if(trim($optsKey) == 'recipient_message')
                echo '<span class="fontSize11px fontStyleItalic"><strong>Recipient Message: </strong></span><span class="fontSize11px fontStyleItalic fontStyleNormal">'.$optsVal.'</span><br/>';                
              }
              ?>
                      </div>
                      <div>Quantity. <?php echo (int)$items->getQtyOrdered()?>&nbsp;&nbsp;&nbsp;&nbsp; Price : <?php echo $_coreHelper->formatPrice($items->getPrice());?></div></td>
                  </tr>
                </tbody>
              </table></td>
            <td class="qty-item textAlignRight"><?php /*?><?php echo number_format($items->getQtyOrdered(),0); ?> <span class="xx">x</span> <?php echo $_coreHelper->formatPrice($items->getPrice(),true) ?>  = <?php */?>
              <?php $totalprice = ($items->getQtyOrdered())*($items->getPrice()); ?>
              <span class="alt-bg"><?php echo $_coreHelper->formatPrice($totalprice,true) ?></span></td>
          </tr>
        </table>
        <?php
            } 
          ?>
      </div>
      <div class="col-sm-6 floatRightCss">
        <?php /*?><div class="section-title text-danger text-right"><h3><?php echo $this->__('Sub Total') ?></h3></div><?php */?>
        <div class="section-title text-danger text-right">
          <h3>&nbsp;</h3>
        </div>
        <table class="table">
          <tr>
            <td width="100%" ><span ><?php echo $this->__('Cart Total') ?></span></td>
            <td class="a-right"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getSubtotal(),true) ?> </span></td>
          </tr>
          <?php //echo '<pre>'; print_r($orderObj); echo '</pre>'; 
      
      ?>
          <?php if($displayDiscount==1): ?>
          <?php if($orderObj->getDiscountAmount() != 0): ?>
          <tr class="discount">
            <td ><?php echo $this->__('Coupon Discount').'('.$orderObj->getDiscountDescription().')' ?></td>
            <td class="last a-right"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getDiscountAmount(),true) ?> </span></td>
          </tr>
          <?php 
              endif; 
            endif; 
          ?>
		  
          <?php 
		  if(($orderObj->getFeeAmount() * -1) > 0){?>
          <tr class="tax">
            <td   ><?php echo $this->__('5% Online Payment Discount')?></td>
            <td class="last a-right"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getFeeAmount(),true) ?> </span></td>
          </tr>
          <?php } ?>
		  
          <?php 
		  if(($orderObj->getGiftcertAmount()) > 0){?>
          <tr class="tax">
            <td   ><?php echo $this->__('Gift Certificates ('.$orderObj->getGiftcertCode().')')?></td>
            <td class="last a-right"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice(($orderObj->getGiftcertAmount() * -1),true) ?> </span></td>
          </tr>
          <?php } ?>		  
		  
		  
          <?php if($payment_method_code == 'phoenix_cashondelivery'){?>
          <tr class="tax">
            <td   ><?php echo $this->__('COD Handling Charges')?></td>
            <td class="last a-right"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getCodFee(),true) ?> </span></td>
          </tr>
          <?php } ?>
		  
		  
          <?php if($displayShippingRate==1): ?>
          <tr class="shipping">
            <td><?php echo $this->__('Shipping Charges'); ?></td>
            <td class="last a-right"><span class="subtotlal-value"> <?php if($orderObj->getShippingInclTax() > 0) echo $_coreHelper->formatPrice($orderObj->getShippingInclTax(),true); else echo "Free"; ?> </span></td>
          </tr>
          <?php 
            endif; 
          ?>
          <?php if($displayTax==1): ?>
          <?php if($orderObj->getTaxAmount() != 0): ?>
          <tr class="tax">
            <td    ><?php echo $this->__('Tax')?></td>
            <td class="last a-right"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getTaxAmount(),true) ?> </span></td>
          </tr>
          <?php 
              endif;
            endif;
          ?>
          <tr class="grand_total ">
            <td  ><label><strong><?php echo $this->__('Order Total') ?></strong></label></td>
            <td class="last a-right"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getGrandTotal(),true); ?></span></td>
          </tr>
        </table>
      </div>
    </div>
    <?php endif; 
endif;
?>
  </div>
  <?php if($this->getBottomBlock()!=false): ?>
  <?php if($displayCmsBlockBelow==1): ?>
  <div class="order-cms-block block_2"> <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getBottomBlock())->toHTML(); ?> </div>
  <?php
  endif;
endif;
?>
  <?php if($newsLetter==1): ?>
  <div class="order-newsletter"> <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?> </div>
  <?php 
  endif;
?>
</div>
<?php
Mage::getSingleton('core/session')->unsEmailID();
// code for t-shirt api
$read = Mage::getSingleton( 'core/resource' )->getConnection( 'core_read' );
$write = Mage::getSingleton( 'core/resource' )->getConnection( 'core_write' );
error_reporting(0);
$orderIncrementId = $this->getOrderId();
$order = Mage::getModel('sales/order')->loadByIncrementId($orderIncrementId);
$order_id = $order->getEntity_id();
$payment_method = $order->getPayment()->getMethodInstance()->getTitle();
$payment_method_code = $order->getPayment()->getMethodInstance()->getCode();
if($payment_method_code == 'payucheckout_shared')
{
  $payment_method = 'Prepaid';
  $orderItem = $read->query("SELECT `item_id` FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `product_type` = 'configurable'");
  $allOrderItem = $orderItem->fetch();
  $item_id = $allOrderItem['item_id'];
  $total_style_code = array();
  if($item_id != '')
  {
    // Shipping Address Data
    $shipping_address = $order->getShippingAddress();
    $shipping_data = $shipping_address->getData();
    $spostcode = $shipping_data['postcode'];
    $saddress1 = $shipping_data['street'];
    $fname = $shipping_data['firstname'];
    $lname = $shipping_data['lastname'];
    $scity = $shipping_data['city'];
    $sstate = $shipping_data['region'];
    $stelephone = $shipping_data['telephone'];
    $scountry_id = $shipping_data['country_id'];
    $countryModel = Mage::getModel('directory/country')->loadByCode($scountry_id);
    $scountryName = $countryModel->getName();
    
    // Billing Address Data
    $billing_address = $order->getBillingAddress();
    $billing_data = $billing_address->getData();
    $bpostcode = $billing_data['postcode'];
    $bsaddress1 = $billing_data['street'];
    $bcity = $billing_data['city'];
    $bstate = $shipping_data['region'];
    $btelephone = $billing_data['telephone'];
    $bcountry_id = $billing_data['country_id'];
    $countryModel = Mage::getModel('directory/country')->loadByCode($bcountry_id);
    $bcountryName = $countryModel->getName();
     
    if($order->canInvoice() and $order->getIncrementId())
    {
      $items = array();
      foreach ($order->getAllItems() as $item1) 
      {
      $items[$item1->getId()] = $item1->getQtyOrdered();
      }
      //public function create($orderIncrementId, $itemsQty, $comment = null, $email = false, $includeComment = false)
      $invoiceId = Mage::getModel('sales/order_invoice_api')->create($order->getIncrementId(),$items,null,false,true);
      //$invoice = Mage::getModel('sales/order_invoice_api')->capture($invoiceId);
    }
    
    if ($order->hasInvoices()) {
      foreach ($order->getInvoiceCollection() as $inv) {
      $invIncrementIDs = $inv->getIncrementId();
      $inv_total = round($inv->getGrandTotal());
      } 
    }
    
   
			   $date = date('Y'); 
				$order_date = $order->getCreatedAt();
				$orderdate =   $order->getCreatedAtStoreDate();
				$orderdate =  explode(',',$orderdate);
				$orderdate =  $orderdate[0].', '.$date;
    // $order_date = date('Ý-m-d');
    $order_qty = $order->getTotalQtyOrdered();
    $subtotal = $order->getSubtotal();
    //$grandtotal = $order->getGrandTotal();    
    $customer_id = $order->getCustomerId();
    $base_currency_code = $order->getBaseCurrencyCode();
    $bill_id = $order->getBillingAddressId();
    $ship_id = $order->getShippingAddressId();
    $email = $order->getCustomerEmail();
    $title = $order->getCustomerPrefix();
    //$fname = $order->getCustomerFirstname();
    //$lname = $order->getCustomerLastname();
    // $Company_Name = getBillingAddress()->getCompany();
	//echo $Company_Name;
    $shipping_amount = $order->getShippingAmount();
    $discount = $order->getDiscountAmount();
    $coupon = $order->getCouponCode();
    $ship_method = $order->getShippingMethod();
    
    $xml = new SimpleXMLElement("<?xml version=\"1.0\" encoding=\"utf-8\"?><order></order>");
    $xml->addChild('order_id', $order_id);
    $xml->addChild('order_date', $order_date);
    $customer_details = $xml->addChild('customer_details');
    $customer_details->addChild('title', $title);
    $customer_details->addChild('first_name', $fname);
    $customer_details->addChild('last_name', $lname);
    $customer_details->addChild('email', $email);
    $shipping_address = $xml->addChild('shipping_address');
    $shipping_address->addChild('title', $title);
    $shipping_address->addChild('first_name', $fname);
    $shipping_address->addChild('last_name', $fname);
    $shipping_address->addChild('address_line1', $saddress1);
    $shipping_address->addChild('address_line2', $saddress1);
    $shipping_address->addChild('country', $scountryName);
    $shipping_address->addChild('city', $scity);
    $shipping_address->addChild('state', $sstate);
    $shipping_address->addChild('pincode', $spostcode);
    $shipping_address->addChild('mobile', $stelephone);
    $xml->addChild('self_shipping', 'no');
    $billing_address = $xml->addChild('billing_address');
    $billing_address->addChild('title', $title);
    $billing_address->addChild('first_name', $fname);
    $billing_address->addChild('last_name', $fname);
    $billing_address->addChild('address_line1', $saddress1);
    $billing_address->addChild('address_line2', $saddress1);
    $billing_address->addChild('country', $bcountryName);
    $billing_address->addChild('city', $scity);
    $billing_address->addChild('state', $bstate);
    $billing_address->addChild('pincode', $bpostcode);
    $billing_address->addChild('mobile', $stelephone);
    $invoice = $xml->addChild('invoice');
    $invoice->addChild('invoice_number', $invIncrementIDs);
    $invoice->addChild('invoice_value', $inv_total);
    $invoice->addChild('tax_percentage', 0);
    $invoice->addChild('tax_value', 0);  
    $invoice->addChild('payment_mode', $payment_method);
    $invoice->addChild('special_instruction', 'Test');
    $invoice->addChild('discount', round($discount));
    $invoice->addChild('shipping_charges', round($shipping_amount));
    $invoice->addChild('order_comment', 'Test');
    $invoice->addChild('voucher_text', 'Test');
    $invoice->addChild('voucher_value', '123');
    $invoice->addChild('cod_convenience_fee', '50');
    $invoice->addChild('currency', $base_currency_code);
    $courier = $xml->addChild('courier');
    $courier->addChild('courier_name', 'Delhivery COD');
    $courier->addChild('docket_number', '11');
    $products = $xml->addChild('products');
    
    $orderItem = $read->query("SELECT `item_id`, `product_id`, `price`, `row_total` FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `product_type` = 'configurable'");
    $allOrderItem = $orderItem->fetchAll();
    for($i=0;$i<count($allOrderItem);$i++)
    { 
      //print_r($allOrderItem);
      $configProductid = $allOrderItem[$i]['product_id'];
      $configProduct = Mage::getModel('catalog/product')->load($configProductid);  
      $ids = $configProduct->getCategoryIds();
      $categoryId = (isset($ids[0]) ? $ids[0] : $ids[1]);
      $style_code = $configProduct['style_code'];
      $design_code = $configProduct['design_code'];

      $getSimple = $read->query("SELECT * FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `parent_item_id` = '".$allOrderItem[$i]['item_id']."'");
      $getSimpleRes = $getSimple->fetch(); 

      $pr_qty = $getSimpleRes['qty_ordered'];
      $pr_price = $allOrderItem[$i]['price']; 
      $pr_row_total = $allOrderItem[$i]['row_total'];    

      $_product = Mage::getModel('catalog/product')->load($getSimpleRes['product_id']); 
          
      $color_qry = $read->query("SELECT `value` FROM `eav_attribute_option_value` WHERE `option_id` = '".$_product['color']."'");
      $color_row = $color_qry->fetch();
        
      $size_qry = $read->query("SELECT `value` FROM `eav_attribute_option_value` WHERE `option_id` = '".$_product['size']."'");
      $size_row = $size_qry->fetch(); 
      
      $color = $color_row['value'];
      $size = $size_row['value'];
      $price = $_product['price'];
      $name = $_product['name'];  
              
      $product_detail = $products->addChild('product_detail');
      $product_detail->addChild('product_name', $name);
      $product_detail->addChild('product_code', $style_code);
      $product_detail->addChild('product_color', $color);
      $product_detail->addChild('product_design_id', $design_code);      
      $product_detail->addChild('tax', '0');
      $product_size = $product_detail->addChild('product_size');
      $product_size->addChild('size_name', $size);
      $product_size->addChild('size_quantity', round($pr_qty));
      $product_size->addChild('unit_price', round($pr_price));  

      $total_style_code[] = array($style_code, $_product['color'], $color, $_product['size'], $size, $categoryId);   
    }
    // code for invoice pdf
    require('html2pdf_sample/html2fpdf.php');
    $pdf = new HTML2FPDF();
    $pdf->AddPage();
    /*$fp = fopen("order_shipped.html","r");
    $strContent = fread($fp, filesize("order_shipped.html"));
    fclose($fp);*/
    $inv_no = rand(0, 100);
    $html = '';
    $html .= '
	<!doctype html>
      <html>
      <head>
      <meta charset="utf-8">
      <title>:: Retail Invoice dfdfd::</title>
      <style type="text/css">
      body { background: #fff; font-family: Arial, Gotham, Helvetica, sans-serif; font-size:13px }
      table { border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; /*font-size: 0*/ }
      table td { border-collapse: collapse; }
      </style>
      <style type="text/css">
      @media only screen and (max-width: 599px) {
      .social-icon { top: 100px!important }
      }
      </style>
      </head>
      <body style="padding:0; margin:0" >
      <div style="background:#fff" class="main-box">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tbody>
            <tr>
              <td align="center"><div style="width:100%; max-width:840px">
               <table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#fff">
                    <tbody>
                      <tr>
                        <td colspan="3" height="5px"></td>
                      </tr>
                      <tr>
                        <td width="150"><img src="http://www.bhishoom.com/skin/frontend/rwd/default/images/logoFooterInvoice.jpg" style="display:block; max-width:150px; width:100%; max-height:124px" alt="bhishoom"/></td>
                        <td width="20px"></td>
                        <td align="">
						<div style=" font-size:14px">
							Dreambox Retail Pvt. Ltd.<br>
                            1st Floor, 37-A, Bhagat Vatika, Raj Bhawan Road,<br>
                           Civil Lines, Jaipur, Rajasthan, India - 302006
						</div>
						<br>
                          <div style="font-size:14px">Call Us: - +91 96100 55577</div><br>
                          <div style="font-size:14px">Email: - support@bhishoom.com</div><br>
                          <div style="font-size:14px">Website: - www.bhishoom.com</div></td>
                        <td align="right" width="150" valign="top">
						<div style=""><img src="http://bhishoom.com/skin/frontend/rwd/default/images/prepaid.jpg" width="110px"  alt=""/></div>
                       </td>
                      </tr>
                      <tr>
                        <td colspan="3" height="10px"></td>
                      </tr>
                    </tbody>
                  </table>
				  
				   <table width="100%" border="0" cellspacing="0" cellpadding="10">
                    <tbody>
					<div style=" height:1px; margin:5px 0 15px; width:100%"></div>
                      <tr>
                       <td colspan="4" align="center" style="font-size:22px; font-weight:bold; text-align:center; height:50px; text-transform:uppercase"><h2>Retail Invoice</h2></td><br><br>
					   </tr>
                      <tr>
                        <td valign="top" colspan="4" align="left" ><strong >SHIP To</strong> </td>
                        
                      </tr>
                      <tr>
                        <td valign="top" colspan="2">'.$fname.' '.$lname.'</td>
                        <td valign="top"  id="iin">Invoice No.</td>
                        <td valign="top" align="right">'.$invIncrementIDs.'</td>
                      </tr>
                      
                      <tr>
                        <td colspan="2">'.$saddress1.','.$spostcode.'</td>
							<td valign="top">Order No.</td>
						  <td valign="top" align="right">'.$this->getOrderId().'</td>
                       
                      </tr>
					  
					  <tr>
						<td valign="top" colspan="2">'.$scity.'</td>
						<td valign="top">Order Date</td>
                       <td valign="top" align="right">'.$orderdate.'</td>
                      </tr>
                      <tr>
						<td valign="top" colspan="2">'.$stelephone.'</td>
                        <td valign="top">Payment</td>
                        <td valign="top" align="right">'.$payment_method.'</td>
                      </tr>
                      <tr>
                       <td valign="top" colspan="2">'.$email.'</td>
                        <td valign="top">TIN No.</td>
                        <td valign="top" align="right">08304358064</td>
                      </tr>
                      
                    </tbody>
                  </table>
				  <div style=" height:1px; margin:5px 0 15px; width:100%"></div>
                    <div style=" height:1px; margin:25px 0 15px; width:100%"></div>
				  <br><br>
                  <table width="100%" border="1" cellspacing="15" cellpadding="0">
                    <tbody>
                      <tr>
                        <td align="center" width="5px">S.No.</td>
                        <td  colspan="5" align="center" ><div style="font-size:14px">ITEM DESCRIPTION</div></td>
                        
                        <td align="center" ><div style="font-size:14px">QTY</div></td>
						<td align="center" ><div style="font-size:14px">PRICE</div></td>
                        <td align="center" ><div style="font-size:14px">TAX</div></td>
                        <td align="center" ><div style="font-size:14px">SUB TOTAL</div></td>
                      </tr>'; 
					  
                      // for shipping
                      $getTot = $read->query("SELECT * FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `product_type` = 'simple'");
                      $getTotProd = $getTot->fetchAll();
                      $t=0;$t_qty=0;
                      foreach ($getTotProd as $value) 
                      {//echo $value['parent_item_id'];
                          if($value['parent_item_id'] == NULL)
                          {
                            ++$t;
                            $t_qty += $value['qty_ordered'];
                          }
                          else
                          {
                            break;
                          }
                      }                      

                      $pr_discount_amount = 0;$pr_ship_qty = 0;$j=1;$pr_finel_total=0;
					  $pr_discount_amount_temp = 0;
					  $onLinePaymentDiscount = 5;
					  
					  $shippingprice = 0;
					  
                      $orderItem = $read->query("SELECT `item_id`, `product_id`, `price`, `row_total`, `discount_amount`, `item_shipping_price` FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `product_type` = 'configurable'");
                        $allOrderItem = $orderItem->fetchAll();
                        for($i=0;$i<count($allOrderItem);$i++)
                        {                           
                          $configProductid = $allOrderItem[$i]['product_id'];
                          $configProduct = Mage::getModel('catalog/product')->load($configProductid);  
                          $ids = $configProduct->getCategoryIds();
                          $categoryId = (isset($ids[0]) ? $ids[0] : $ids[1]);
                          $style_code = $configProduct['style_code'];
							
							$getSimple = $read->query("SELECT * FROM `sales_flat_order_item` WHERE `order_id` = '".$order_id."' AND `parent_item_id` = '".$allOrderItem[$i]['item_id']."'");
							
							$getSimpleRes = $getSimple->fetch();  
						    
                            $pr_qty = $getSimpleRes['qty_ordered'];
							
                            $pr_ship_qty += $getSimpleRes['qty_ordered'];
							
							$shippingprice = $shippingprice + $allOrderItem[$i]['item_shipping_price'];
							
							/*
                            $pr_price = $allOrderItem[$i]['price'];
							 
                            $pr_discount_amount = $allOrderItem[$i]['discount_amount'];  
							
							$pr_discount_amount_temp += $pr_discount_amount;
							
                            $pr_price = $pr_price - ($pr_discount_amount/$getSimpleRes['qty_ordered']);
							
							$onlinePaymentDiscount = (($pr_price * $onLinePaymentDiscount)/100);
							
							$pr_price = $pr_price - $onlinePaymentDiscount;

							$pr_discount_amount_temp += ($onlinePaymentDiscount * $getSimpleRes['qty_ordered']);							
							
							$tax = round($pr_price*5/105);
							
							$pr_price = $pr_price - $tax;
							
							$pr_row_total = $allOrderItem[$i]['row_total']-$pr_discount_amount - ($onlinePaymentDiscount * $getSimpleRes['qty_ordered']); 
							
                            $pr_finel_total += $allOrderItem[$i]['row_total'];
							*/
							
							
							
							
							
							
							/*
							$pr_price = $allOrderItem[$i]['row_total'] - $allOrderItem[$i]['discount_amount'];
							$pr_discount_amount = $allOrderItem[$i]['discount_amount']; 
							$pr_discount_amount_temp += $pr_discount_amount;
							$onlinePaymentDiscount = (($pr_price * $onLinePaymentDiscount)/100);
							$pr_price = $pr_price - $onlinePaymentDiscount;
							$pr_discount_amount_temp += ($onlinePaymentDiscount);	
							$tax = round($pr_price*5/105);
							$pr_price = $pr_price - $tax;
							$pr_row_total = $allOrderItem[$i]['row_total'] - ($pr_discount_amount + $onlinePaymentDiscount); 
							
							$pr_finel_total += $pr_row_total;*/
							
							
							
							
	$pr_price = $allOrderItem[$i]['row_total'] + $allOrderItem[$i]['discount_amount'];
		
	$pr_discount_amount = $allOrderItem[$i]['discount_amount'];
	
	$pr_discount_amount_temp += $pr_discount_amount;
	
	$onlinePaymentDiscount = ceil((($pr_price * $onLinePaymentDiscountPer)/100)) * -1;
	
	$pr_price = $pr_price + $onlinePaymentDiscount;
	
	$pr_discount_amount_temp += ($onlinePaymentDiscount);
	
	$tax = ceil($pr_price*5/105);
	
	$pr_price = $pr_price - $tax;
	
	$pr_row_total = $allOrderItem[$i]['row_total'] + ($pr_discount_amount + $onlinePaymentDiscount);
	
	$pr_finel_total += $pr_row_total;							
							
							
							
							
							
							
							$_product = Mage::getModel('catalog/product')->load($getSimpleRes['product_id']); 
                              
                          $color_qry = $read->query("SELECT `value` FROM `eav_attribute_option_value` WHERE `option_id` = '".$_product['color']."'");
                          $color_row = $color_qry->fetch();
                            
                          $size_qry = $read->query("SELECT `value` FROM `eav_attribute_option_value` WHERE `option_id` = '".$_product['size']."'");
                          $size_row = $size_qry->fetch(); 
                          
                          $color = $color_row['value'];
                          $size = $size_row['value'];
                          $price = $_product['price'];
                          $name = $getSimpleRes['name']; 
                          $html.= '
						  <tr>
						  <td align="center" width="5px">'.$j.'</td>
                          <td colspan="5" align="left">'.$name.'<br>
						  <b>Color</b>:&nbsp;'.$color.'&nbsp;&nbsp;<b>Size</b>:&nbsp;'.$size.'</td>
                          <td align="center" ><div style="font-size:14px">'.round($pr_qty).'</div></td>
                          <td align="center" ><div style="font-size:14px">'.round($pr_price).'</div></td>
						  <td align="center" ><div style="font-size:14px">'.$tax.'</div></td>
                          <td  align="center" ><div style="font-size:14px">'.round($pr_row_total).'</div></td>
						  </tr>';
						  
                          $j++;
                        } 
						
						$shipping_amount = $shippingprice;
						/*
                        if($shipping_amount > 0)                       
                        {
                          if($t > 0)
                          {
                            $shipping_amount = $pr_ship_qty*20;
                          }
                          else
                          {
                            $shipping_amount = ($pr_ship_qty*20)+19;
                          }
                        }*/
                        $grandtotal = ($pr_finel_total+$shipping_amount);
                      $html.='
					     <tr>
                        <td colspan="9" align="right" ><div style="font-size:14px">Shipping Charges<br>
						
						</div></td>';
						if($shipping_amount > 0)
						{
							$html.='<td align="center" ><div style="font-size:14px">'.$shipping_amount.'</div></td>';
						}
						else 
						{
							  $html.='<td align="center" ><div style="font-size:14px">Free</div></td>';
							
						}
			             
               						 
					    /*
                     
                      <tr>
                        <td colspan="5" align="center" ><div style="font-size:16px">Coupon Discount (Online Payment)</div></td>
                        <td align="center" ></td>
                        <td align="right" ><div style="font-size:16px">- INR '.$pr_discount_amount.'</div></td>
                      </tr>                       
                      */
					   $html.='
					  </tr>
					  <tr>
                        <td colspan="8" align="center" ><div style="font-size:14px"><em>Thank you for purchasing item on Bhishoom</em></div></td>
                        <td align="center" ><div style="font-size:14px"><strong>TOTAL</strong></div></td>
                        <td align="center"><div style="font-size:14px"><strong>'.$grandtotal.'</strong></div></td>
                      </tr>
					  
					  
                    </tbody>
                  </table>     
                  	<div style=" height:1px; margin:25px 0 15px; width:100%"></div>
		<br><br>
		<div style=" height:1px; margin:10px 0 10px; width:100%"></div>
		<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
				  
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tbody>
                <tr>
                  <td height="5px"></td>
                </tr>
                <tr>
                  <td align="center">
				   <div style=""><img src="http://bhishoom.com/skin/frontend/rwd/default/images/footertext.jpg" width="700px" alt=""/></div>
				  </td>
                </tr>
                <tr>
                  <td height="5px"></td>
                </tr>
              </tbody>
		</table>  
                </div></td>
            </tr>
          </tbody>
        </table>
      </div>
      </body>
      </html>';
	  
$myfile = fopen(Mage::getBaseDir()."/newfile.html", "w") or die("Unable to open file!");
$txt = $html;
fwrite($myfile, $txt);
fclose($myfile);	  
    $pdf->WriteHTML($html);
    $pdf->Output("invoice/file001.pdf");

    $invoice_url = $siteBaseUrl.'invoice/file001.pdf';

    $estore = $xml->addChild('estore');
    $estore->addChild('estore_invoice_available', 'yes');
    $estore->addChild('estore_invoice_url', $invoice_url);
    $estore->addChild('estore_clearance_available', 'yes');
    $estore->addChild('estore_clearance_url', $invoice_url);
    $estore->addChild('estore_manifest_required', 'yes');

    $xml->asXML('xml-file1.xml');
    $xml_str = $xml->asXML();
    
    $curl = curl_init();
    curl_setopt_array($curl, array(
      CURLOPT_RETURNTRANSFER => 1,
      CURLOPT_URL => 'http://99prints.99-dot-com-website-testing.com/api/create_order.php',
      //CURLOPT_URL => 'http://www.99prints.in/api/create_order.php',
      //CURLOPT_SSL_VERIFYPEER => false,
      CURLOPT_USERAGENT => 'Codular Sample cURL Request',
      CURLOPT_POST => 1,
      CURLOPT_POSTFIELDS => array(
      "api_key" => "234yNCmXtkVcFY9P",
      //"api_key" => "bhkpMxQTLfCyBHN3",
      "order_data" => $xml_str
      )
    ));
    $resp = curl_exec($curl);
    curl_close($curl);
    //print_r($resp);

    $new_style_code = array_unique($total_style_code);
    $scurl = curl_init();
    curl_setopt_array($scurl, array(
        CURLOPT_RETURNTRANSFER => 1,
        CURLOPT_URL => 'http://23.251.150.147/api_test/merchant/stock.php',
        CURLOPT_USERAGENT => 'Codular Sample cURL Request',
        CURLOPT_POST => 1,
        CURLOPT_POSTFIELDS => array(
            'api_key' => 'bDNymqvhpxKWg7fr'
        )
    ));
    $sresp = curl_exec($scurl);
    curl_close($scurl);
    $sxml = simplexml_load_string($sresp);

    for($i=0;$i<count($total_style_code);$i++)
    {
      $code = $total_style_code[$i][0];
      $color_id = $total_style_code[$i][1];
      $color_name = $total_style_code[$i][2];
      $size_id = $total_style_code[$i][3];
      $size_name = $total_style_code[$i][4];
      $cat_id = $total_style_code[$i][5];
      $this->update_stock($sxml, $code, $color_id, $color_name, $size_id, $size_name, $cat_id);
    }
    

    $style_id_array = array();
    $inventory_array = array();

    foreach($sxml as $data)
    {
      $style_id = $data->style_id;
      if(!in_array($style_id,$style_id_array))
       $style_id_array[] = $style_id;
      else
         continue; 
        foreach($data->style_color as $color)
        {
          $color_name = addslashes($color->style_color_name);
          foreach($color->style_size as $size)
          {
            $size_name = addslashes($size->size_name);
            $stock = $size->size_stock;
            $inventory_array["$style_id"]["$color_name"]["$size_name"] = array("$stock");       
          }     
        }   
    }  

    foreach($style_id_array as $style_id_array_val)
    {
       //echo $style_id_array_val;
       //echo '<br/>';
      $write->query("update a_create_tshirt_inventory set inVentory = '".base64_encode(serialize($inventory_array["$style_id_array_val"]))."' where designId = '".$style_id_array_val."'");
    }   
  }
}  
?>
