<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use/
 * @version      Release: 1.0.0
 * @since        Available since Release 1.0.0
 */
?>
<div class="account-login" id="customer-login-container" style="display: none">
    <ul class="messages" style="display: none">
        <li class="error-msg" id="login-error-msg">
            <ul>
            </ul>
        </li>
    </ul>
    <form method="post" id="login-form">
        <div class="col-2 registered-users">
            <div class="content">
                <h2><?php echo $this->__('Registered Customers') ?></h2>
                <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                <ul class="form-list">
                    <li>
                        <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                        </div>
                    </li>
                </ul>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            </div>
        </div>
        <div class="col-2 registered-users">
            <div class="buttons-set">
                <button type="button" class="button" title="<?php echo $this->__('Login') ?>" id="customer-login-btn"><span><span><?php echo $this->__('Login') ?></span></span></button>
                <button type="button" id="customer-register-btn" title="<?php echo $this->__('Create an Account') ?>" class="button"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
            </div>
        </div>
    </form>
</div>
