<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use/
 * @version      Release: 1.0.0
 * @since        Available since Release 1.0.0
 */
?>
<div class="my-designs">
    <div class="page-title title-buttons">
        <h1><?php echo $this->getTitle(); ?></h1>
    </div>
  <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
  <?php echo $this->getChildHtml('design.list');?>
</div>