<?php    $slide_status=$this->getResponsivebannersliderEnabled();?>
<?php    $slide_speed=$this->getResponsivebannersliderSpeed();   ?>
<?php    $slide_type=$this->getResponsivebannerSlideType(); ?>
<?php    $slide_BannerLoop=$this->getResponsivebannerBannerLoop(); ?>
<?php    $slide_PauseOnhover=$this->getResponsivebannerPauseOnhover(); ?>


<?php
// Module Enable/Dsable Function.......................................
if($slide_status==1){ ?>



<?php
// Module type Function.......................................
if($slide_type=='1'){ 
 // echo "fsfasf"; die;
?>


<?php /*

<?php  $cssurl =  str_replace('index.php/','',$this->getUrl());?>
<link rel="stylesheet" type="text/css" href="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/css/generic-nav.css'; ?>" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/css/grid12.css'; ?>" media="all">
<script type="text/javascript" src="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/js/jquery-1.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/js/jquery-noconflict.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/js/jquery_004.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/js/jquery_003.js'; ?>"></script> 
*/ ?>

<!-- BEGIN GOOGLE ANALYTICS CODEs -->


<div id="owl-example" class="owl-carousel">


<?php 
$connection = Mage::helper('function/more')->getDbWriteObject();	
$prefix = Mage::getConfig()->getTablePrefix();

$tblname=$prefix.'mksresponsivebannerslider';

$sql = $connection->query("select * from $tblname where status='1'");
while($row1 = $sql->fetch())
{
$title = $row1["title"];
$description = $row1["description"]; 
$urlx = $row1["image"]; 
$media_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$imgurl=$media_url.$urlx;
$url = $row1["url"]; 
// echo $imgurl; die;
?>
<div class="item">
<a href="<?php echo $url; ?>">
<img src="<?php echo $imgurl; ?>" alt="<?php echo $title; ?>" title="<?php echo $title; ?>">
</a>
</div>




<?php } ?>

 
</div>



<!-- BEGIN GOOGLE ANALYTICS CODEs -->

 <script type="text/javascript">
//<![CDATA[
//jQuery(function($) {
  jQuery(document).ready(function() {
    jQuery("#owl-example").owlCarousel({
	  autoPlay: 3000,
	  navigation : true, // Show next and prev buttons
      slideSpeed : 300,
      paginationSpeed : 400,
      singleItem:true
  }); 
 
});

//]]>
</script>   
<style>
 #owl-example .item{ margin:0}
 #owl-example .item a img{
    display: block;
    width: 100%;
    height: auto;
}
</style>


<?php 
// Module type 2 Function.......................................End
} ?>



<?php
// Module type 1 Function.......................................Start
if($slide_type=='2'){ ?>


<?php /*

<?php $cssurl =  str_replace('index.php/','',$this->getUrl());?>
<link rel="stylesheet" type="text/css" href="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/css/generic-nav.css'; ?>" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/css/grid12.css'; ?>" media="all">
<script type="text/javascript" src="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/js/jquery-1.7.2.min.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/js/jquery.easing.min.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/js/jquery.flexslider.min.js'; ?>"></script>

*/?>

	


<div class="the-slideshow gen-slider-arrows2 gen-slider-pager1 gen-slider-pager1-pos-bottom-right grid12-9  ">
<ul class="slides1" style="padding:0px!important;">
<?php 
//$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
$prefix = Mage::getConfig()->getTablePrefix();
$tblname=$prefix.'mksresponsivebannerslider';
$sql = $connection->query("select * from $tblname where status='1'");
while($row1 = $sql->fetch())
{
$title = $row1["title"];
$description = $row1["description"]; 
$urlx = $row1["image"]; 
$media_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$imgurl=$media_url.$urlx;
$url = $row1["url"]; 
?>
<li class="slide">
<a href="<?php echo $url; ?>">
<img src="<?php echo $imgurl; ?>" alt="<?php echo $title; ?>" title="<?php echo $title; ?>">
<div class="caption dark3">
<h2><?php echo $description; ?></h2>
</div>
<div class="caption dark1 top-right">
<h2></h2>
</div>
</a></li>

 



<?php } ?>
</ul>
</div>
  
<script type="text/javascript">
//<![CDATA[
//jQuery(function($) {
responsivemks = jQuery.noConflict(); 
responsivemks(window).load(function(){
responsivemks('.the-slideshow').flexslider({
namespace:"",
animation:'slide',
easing:'easeInOutCirc',
useCSS:	false,
animationLoop:<?php echo $slide_BannerLoop; ?>,
smoothHeight: true,
slideshowSpeed:<?php echo $slide_speed; ?>,
animationSpeed:	600,
pauseOnHover:<?php echo $slide_PauseOnhover; ?>
});
});
//]]>
</script>  

        



<?php
// Module type 1 Function.......................................End
 } ?>


 

<?php } 
else { ?>

<h1 style="color:red;">Enable ( Responsive banner ) Module via Admin = System -> Configuration-> MKS RESPONSIVE BANNER-> General Setting </h1>

 <?php } ?>
 
