<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use/
 * @version      Release: 1.0.0
 * @since        Available since Release 1.0.0
 */
?>
<h4 class="notes-panel-title"><?php echo $this->__('Additional instructions') ?></h4>
<ul class="form-list">
  <li>
    <div class="input-box">
      <textarea class="notes-panel-textarea" id="design_comment" cols="5" rows="18"></textarea>
    </div>
  </li>
</ul>