<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use/
 * @version      Release: 1.0.0
 * @since        Available since Release 1.0.0
 */
?>
<?php
$colors = $this->getAvailableColors();
$defaultFonts = $this->getDefaultFonts();
$fonts = $this->getFonts();
$sizes = $this->getFontSizes();
?>
<style type="text/css">
<?php foreach($fonts as $font):?>
    @font-face {
        font-family: <?php echo $this->getFontName($font);?>;
        src: url("<?php echo $this->getFontUrl($font->getFont());?>");
    }
<?php endforeach;?>
</style>
<div>
    <div class="pd-element-wrapper">
        <input type="text" id="add_text_textarea" class="input-text pd-textarea" placeholder="<?php echo $this->__('Enter text here') ?>" />
    </div>
    <div class="pd-element-wrapper">
        <select class="font-picker" id="font-selector">
        <?php foreach ($defaultFonts as $font):?>
            <option value="<?php echo $font['value']; ?>" <?php echo $this->getDefaultFontFamily() == $font['value'] ? 'selected="selected"' : ''?>><?php echo $font['label']; ?></option>
        <?php endforeach;?>
        <?php foreach($fonts as $font): ?>
            <option value="<?php echo $this->getFontName($font); ?>"><?php echo $this->getFontName($font); ?></option>
        <?php endforeach; ?>
        </select>
    </div>
    <div class="pd-element-wrapper">
        <button id="add_text_button" class="panel-btn pd-btn-add-text"><?php echo $this->__('Add'); ?></button>
        <select class="font-size-selector" id="font_size_selector">
            <?php foreach ($sizes as $size):?>
                <option value="<?php echo $size; ?>" <?php echo $this->getDefaultFontSize() == $size ? 'selected="selected"' : ''?>><?php echo $size; ?></option>
            <?php endforeach;?>
        </select>
        <button class="panel-btn pd-btn-bold" id="add_text_btn_bold"><?php echo $this->__('B'); ?></button>
        <button class="panel-btn pd-btn-italic" id="add_text_btn_italic"><?php echo $this->__('I'); ?></button>
        <button class="panel-btn pd-btn-underline" id="add_text_btn_underline"><?php echo $this->__('U'); ?></button>
        <button class="panel-btn pd-btn-vert-output" id="add_text_btn_vert_out" data-state="horizontal">|</button>
    </div>
    <?php if ($this->effectsEnabled()):?>
        <div class="pd-element-wrapper">
            <button id="curved-text-button" class="panel-btn">↭</button>
            <button id="shadow-button" class="panel-btn"><?php echo $this->__('Shadow'); ?></button>
            <button id="outline-button" class="panel-btn"><?php echo $this->__('Outline'); ?></button>
        </div>
        <div>
            <fieldset class="curved-text-config text-effect">
                <legend><?php echo $this->__('Curved Text'); ?></legend>
                <div id="curved-text-cancel" title="<?php echo $this->__('Cancel Curved') ?>" data-effect="curved" class="panel-cancel-btn">&times;</div>
                <div class="pd-element-wrapper">
                    <label for="curve_spacing"><?php echo $this->__('Radius'); ?>: </label>
                    <input type="range" id="curve_spacing" min='-40' max='40' step="1" value='0' style="width: 250px;">
                </div>
            </fieldset>
            <fieldset class="shadow-config text-effect">
                <legend><?php echo $this->__('Shadow'); ?></legend>
                <div id="shadow-cancel" title="<?php echo $this->__('Cancel Shadow') ?>" data-effect="shadow" class="panel-cancel-btn">&times;</div>
                <div class="pd-element-wrapper">
                    <label><?php echo $this->__('Offset Y'); ?>: </label>
                    <input type="range" value="0" id="shadow_y_range" min="-25" max="25" step="1">
                </div>
                <div class="pd-element-wrapper">
                    <label><?php echo $this->__('Offset X'); ?>: </label>
                    <input type="range" value="0" id="shadow_x_range" min="-25" max="25" step="1">
                </div>
                <div class="pd-element-wrapper">
                    <label><?php echo $this->__('Blur'); ?>: </label>
                    <input type="range" value="0" id="shadow_blur" min="0" max="50" step="1">
                </div>
                <div class="pd-element-wrapper">
                    <canvas height="20" width="230" id="textShadow" class="color-picker"></canvas>
                </div>
            </fieldset>
            <fieldset class="outline-config text-effect">
                <legend><?php echo $this->__('Outline'); ?></legend>
                <div id="outline-cancel" title="<?php echo $this->__('Cancel Outline') ?>" data-effect="outline" class="panel-cancel-btn">&times;</div>
                <div class="pd-element-wrapper">
                    <label><?php echo $this->__('Size')?>:</label>
                    <input type="range" value="0.00001" id="outline_range" min="0.00001" max="1.50001" step="0.05">
                </div>
                <div class="pd-element-wrapper">
                    <canvas height="20" width="230" id="strokeStyle" class="color-picker"></canvas>
                </div>
            </fieldset>
        </div>
    <?php endif;?>
    <div class="colors-panel" id="add_text_colors_panel">
        <?php foreach($colors as $color): ?>
            <span class="color-btn color-code-<?php echo $color; ?>" style="background-color:#<?php echo $color; ?>">&nbsp;</span>
        <?php endforeach; ?>
    </div>
    <div class="pd-element-wrapper">
        <canvas height="40" width="276" id="color" class="color-picker"></canvas>
    </div>
</div>

<script type="text/javascript">
    document.observe("dom:loaded", function(e){
        var textEditor = new GoMage.TextEditor('<?php echo $this->getDefaultFontFamily();?>', '<?php echo $this->getDefaultFontSize()?>');
    }.bind(this))
    var fonts = '<?php echo $this->getImplodedFontsString();?>'.split(',');
    if (fonts != '') {
        WebFontConfig = {
            custom: {
                families: fonts
            }
        };

        (function() {
            var wf = document.createElement('script');
            wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
                '://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js';
            wf.type = 'text/javascript';
            wf.async = 'true';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(wf, s);
        })();
    }
</script>