
      <div class="row" id="create-design">
       <div id="after-cr-design" class="col-sm-12">
       <?php
		$category = $this->getCurrentCategory();
		$cat_id = $category->getId();
		$catName1 = $category->getName();
		$cat_url = $category->getUrl();	
		$shop_tshirt_url = 	Mage::getBaseUrl().'shop/t-shirt.html/';	
		$collection = Mage::getModel('catalog/product')
					  ->getCollection()
					  ->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
					  ->addAttributeToSelect('*')
					  ->addAttributeToFilter('category_id', $cat_id);	
					  
		foreach ($collection as $product)
		{	
			$blankPrdId = $product->getId();
		}			 
		?>
        <h1>Create Your Own </h1>
       </div>
       <div class="col-md-offset-2 col-sm-4">
        <div class="item-box-c"> 
         <a href="<?php echo Mage::getStoreConfig(Mage_Core_Model_Url::XML_PATH_SECURE_URL); ?>designer?id=<?php echo $blankPrdId;?>">
          <div class="thumbnail"><img src="<?php echo $this->getSkinUrl('images/create-your-own.png');?>"> </div>
          <h3>Create your own design on blank product</h3>
         </a> 
        </div>
        <div class="featured-box">
         <ul>
          <li><i class="fa fa-heart"></i>Start from scratch on a blank product </li>
          <li><i class="fa fa-heart"></i>Add background color</li>
          <li><i class="fa fa-heart"></i>Add your images/designs (your  library , facebook ,instagram etc. ) or choose from 1000’s of our  designs </li>
          <li><i class="fa fa-heart"></i>Add text to personalize it </li>
          <li><i class="fa fa-heart"></i>Vectors to show your creativity</li>
         </ul>
        </div>
        <a href="<?php echo Mage::getStoreConfig(Mage_Core_Model_Url::XML_PATH_SECURE_URL); ?>designer?id=<?php echo $blankPrdId;?>" class="btn btn-danger btn-lg">Start Now</a> 
       </div>
       <div class="col-sm-4">
        <div class="item-box-c"> 
         <a href="<?php echo $shop_tshirt_url;?>">
          <div class="thumbnail"><img src="<?php echo $this->getSkinUrl('images/our-design.png');?>"> </div>
          <h3>Customize  on thousands of our  designs </h3>
         </a> 
        </div>
        <div class="featured-box">
         <ul>
          <li><i class="fa fa-heart"></i>Select from our already created awesome designs in various categories.</li>
          <li><i class="fa fa-heart"></i>Add your own images /designs on it </li>
          <li><i class="fa fa-heart"></i>Add text to personalize  it</li>
          <li><i class="fa fa-heart"></i>Add vectors to decorate it</li>
         </ul>
        </div>
        <a href="<?php echo $shop_tshirt_url;?>" class="btn btn-danger btn-lg">Start Now</a> 
       </div>
       <?php /*?><div class="col-sm-4">
                <div class="item-box-c"> <a href="#">
                  <div class="thumbnail"><img src="<?php echo $this->getSkinUrl('images/create-template.png');?>"> </div>
                  <h3>Customize our prefixed templates    </h3>
                  </a> </div>
                <div class="featured-box">
                  <ul>
                    <li><i class="fa fa-heart"></i>Choose from 100’s of templates precreated  for various occassions  and  favourite  memories </li>
                    <li><i class="fa fa-heart"></i>Add your images in prefixed slots</li>
                    <li><i class="fa fa-heart"></i>Add your text in prefixed slots </li>
                  </ul>
                </div>
                <a href="#" class="btn btn-danger btn-lg">Start Now</a> </div><?php */?>
      </div>
     