<!DOCTYPE html>
<?php
$siteBaseUrl = Mage::helper('function/more')->getBhishoomSiteBaseUrl();
$checkMobileDeviceBhishoom = Mage::helper('function/more')->chkIfmobileBhishomm();
$checkMobileDeviceBhishoom = 1;
?>
<!--[if lt IE 7 ]> <html lang="en" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" id="top" class="no-js">
<!--<![endif]-->
<head>
 
 <?php echo $this->getChildHtml('home_head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
 <?php echo $this->getChildHtml('after_body_start') ?>
 <div class="wrapper"> 
  <?php echo $this->getChildHtml('global_notices') ?>
  <div class="page"> 
   <?php echo $this->getChildHtml('header'); ?>
   <?php echo $this->getChildHtml('global_messages') ?>

<?php /*<img src="<?php echo $this->getSkinUrl('images/slider.png');?>"> */?>
   <div class="container">
   <div class="hidden-sm hidden-xs"><?php echo $this->getChildHtml('responsivebannerslider_index');?></div>
<?php if($checkMobileDeviceBhishoom){?>   
  <div id="mobileSlider" class="hidden-lg hidden-md"><?php echo $this->getChildHtml('responsivebannerslider_index1');?></div>
<?php }?>    
    <div class="main-container col1-layout">
     <div class="main"> 
	  <?php echo $this->getChildHtml('breadcrumbs') ?>
      <div class="col-main">  
	   <?php echo $this->getChildHtml('content') ?>
       <?php echo $this->getChildHtml('featuredproduct') ?>  

       <div class="row">
         <div class="col-lg-6 row-xs" id="home-cat-2">
            <div id="index-today-picks">
              <div class="mid-line">
                <h2>Trending</h2>
                
              </div>  
                  <?php echo $this->getChildHtml('home.catalog.product.new') ?> 
            </div>
         </div>
         <div class="col-lg-6 row-xs" id="home-cat-2">
           <div class="shopbyintrest  hidden-sm hidden-xs"> 
       <div class="mid-line">       
        <h2>Shop By Interest</h2>
       </div>          
       <div class="row row-xs ">     
    <?php 
        $mEdia_Base_Dir = Mage::getBaseDir('media');
        $mEdia_Base_URL = Mage::getBaseUrl('media');        
        $read = Mage::getSingleton( 'core/resource' )->getConnection( 'core_read' ); // To read from the database         
        $attribute = Mage::getSingleton('eav/config')->getAttribute('catalog_product', 'case_style');
        if ($attribute->usesSource()) {
            $options = $attribute->getSource()->getAllOptions(false); 
        }
        $kcounter = 1;
        foreach($options as $key => $optionsValue)

    {        
            if($kcounter >= 11)
            continue;
            $result = $read->query( "select * from case_style_images where attr_id='137' and attr_val_id='".$optionsValue['value']."' and active = 1" );
            $row = $result->fetch();
          if(is_file($mEdia_Base_Dir.'/case_style_home/'.$row['img_name'])){
        $style_name = $optionsValue['label'];
        $style_name1 = substr(strip_tags($style_name), 0, 20);
        //$style_name1 = substr(strip_tags($style_name),0,20);
        $marker = strrpos($style_name1, ' ');
        if($marker != '')
        {
          $style_name2 = substr($style_name1, 0, $marker);
          $style_name2 = str_replace('&', '', $style_name2);
          $style_name2 = str_replace('and', '', $style_name2);
        }
        else
        {
          $style_name2 = $style_name1;
        }
        ?>      
            <div class="col-lg-6 col-md-3 col-sm-4 col-xs-6 ">
             <div class="shop-box">
              <div class="shop-img">
        <?php /*?>
        <img src="timthumb.php?src=<?php echo $mEdia_Base_URL?>case_style_home/<?php echo $row['img_name'];?>&h=175&w=211"><?php */?> 

      <a href="<?php echo $siteBaseUrl?>shopbyinterest?case_style=<?php echo $row['attr_val_id'];?>&p=1&ref=shopbyinterest">    
        <img src="<?php echo $mEdia_Base_URL?>case_style_home/<?php echo $row['img_name'];?>" width="211" height="175">
      </a>

        
        </div>
               <a class="skin-name" href="<?php echo $siteBaseUrl?>shopbyinterest?case_style=<?php echo $row['attr_val_id'];?>&p=1&ref=shopbyinterest"><?php echo $style_name2;?></a>               
              </div>
             </div>
        <?php 
        $kcounter++; 
        }}?>             
            </div>
           </div>
         </div>
       </div>

       <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-5 col-lg-6 col-xl-7 instaImages">
             <p class="designHeader">BABACOVER AND YOU</p>
              <span>#INSTAGRAM</span>
              <a href="#" target="_blank" class="instaLink" ><img class="col-xs-6 col-sm-6 col-md-6" src="http://magento.itcslive.com/napfond/skin/frontend/rwd/default/images/footer_block_img_3.jpg"></a>
              <a href="#" target="_blank" class="instaLink" ><img class="col-xs-6 col-sm-6 col-md-6" src="http://magento.itcslive.com/napfond/skin/frontend/rwd/default/images/footer_block_img_3.jpg"></a>
              <a href="#" target="_blank" class="instaLink" ><img class="col-xs-6 col-sm-6 col-md-6" src="http://magento.itcslive.com/napfond/skin/frontend/rwd/default/images/footer_block_img_3.jpg"></a>
              <a href="#" target="_blank" class="instaLink" ><img class="col-xs-6 col-sm-6 col-md-6" src="http://magento.itcslive.com/napfond/skin/frontend/rwd/default/images/footer_block_img_3.jpg"></a>
              <a href="#" target="_blank" class="viewMore">View More</a>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-7 col-lg-6 col-xl-5 babaBlog">
              <p class="designHeader">THE BABACOVER BLOG</p>
              <a class="leftAlign" href="#" target="_blank" ><span >The Tale Of Crazy BABACOVER</span><img src="http://magento.itcslive.com/napfond/skin/frontend/rwd/default/images/footer_block_img_2.jpg" class="solidbabacoverCase" ></a>
              <a class="leftAlign" href="#" target="_blank" ><span>BABACOVER's Solid Cases make you go Ole! Ole!</span><img src="http://magento.itcslive.com/napfond/skin/frontend/rwd/default/images/footer_block_img_1.jpg" class="solidbabacoverCase" ></a>
              <a href="/blog/" target="_blank" class="viewMore" >View More</a>
          </div>
       </div>

      <!--<div class="row row-xs" id="home-cat-2">
       <div id="index-today-picks">
        <div class="mid-line">
         <h2>Trending</h2>
		 <div class="hidden-sm hidden-xs"><a class="btn btn-default nVyq-Small" id="" href="">Best Sellers</a></div>
        </div>  
        <?php echo $this->getChildHtml('home.catalog.product.new') ?> 
       </div>
      </div> -->         
      <!--<div class="row hidden-xs hidden-sm" style="display: none;">
       <div class="col-sm-12">
        <div id="create-own">
		<div class="link-footerbanner"><a href="create.html"><img src="<?php echo $this->getSkinUrl('images/start-customizer.png');?>"></a></div>
		<a href="create.html"><img src="<?php echo $this->getSkinUrl('images/footerbanner.jpg');?>"></a>
    </div>

       </div>
      </div> -->
     <!-- <div class="shopbyintrest  hidden-sm hidden-xs"> 
       <div class="mid-line">       
        <h2>Shop By Interest</h2>
       </div>          
       <div class="row row-xs">		  
		<?php 
        $mEdia_Base_Dir = Mage::getBaseDir('media');
        $mEdia_Base_URL = Mage::getBaseUrl('media');        
        $read = Mage::getSingleton( 'core/resource' )->getConnection( 'core_read' ); // To read from the database         
        $attribute = Mage::getSingleton('eav/config')->getAttribute('catalog_product', 'case_style');
        if ($attribute->usesSource()) {
            $options = $attribute->getSource()->getAllOptions(false); 
        }
        foreach($options as $optionsValue)
		{        
            $result = $read->query( "select * from case_style_images where attr_id='137' and attr_val_id='".$optionsValue['value']."' and active = 1" );
            $row = $result->fetch();
        	if(is_file($mEdia_Base_Dir.'/case_style_home/'.$row['img_name'])){
				$style_name = $optionsValue['label'];
				$style_name1 = substr(strip_tags($style_name), 0, 20);
				//$style_name1 = substr(strip_tags($style_name),0,20);
				$marker = strrpos($style_name1, ' ');
				if($marker != '')
				{
					$style_name2 = substr($style_name1, 0, $marker);
					$style_name2 = str_replace('&', '', $style_name2);
					$style_name2 = str_replace('and', '', $style_name2);
				}
				else
				{
					$style_name2 = $style_name1;
				}
        ?>		  
            <div class="col-md-3 col-sm-4 col-xs-6 ">
             <div class="shop-box">
              <div class="shop-img">
			  <?php /*?>
			  <img src="timthumb.php?src=<?php echo $mEdia_Base_URL?>case_style_home/<?php echo $row['img_name'];?>&h=175&w=211"><?php */?>	

			<a href="<?php echo $siteBaseUrl?>shopbyinterest?case_style=<?php echo $row['attr_val_id'];?>&p=1&ref=shopbyinterest">		
			  <img src="<?php echo $mEdia_Base_URL?>case_style_home/<?php echo $row['img_name'];?>" width="211" height="175">
			</a>

			  
			  </div>
               <a class="skin-name" href="<?php echo $siteBaseUrl?>shopbyinterest?case_style=<?php echo $row['attr_val_id'];?>&p=1&ref=shopbyinterest"><?php echo $style_name2;?></a>               
              </div>
             </div>
        <?php }}?>	           
            </div>
           </div>-->
          
     </div>
    </div>
   </div>
  </div>
 </div>
 <script>
  jQuery(document).ready(function() {
  
  function createCookie(name,value,days) {
      if (days) {
          var date = new Date();
          date.setTime(date.getTime()+(days*24*60*60*1000));
          var expires = "; expires="+date.toGMTString();
      }
      else var expires = "";
      document.cookie = name+"="+value+expires+"; path=/";
  }

  function readCookie(name) {
      var nameEQ = name + "=";
      var ca = document.cookie.split(';');
      for(var i=0;i < ca.length;i++) {
          var c = ca[i];
          while (c.charAt(0)==' ') c = c.substring(1,c.length);
          if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
      }
      return null;
  }

  function eraseCookie(name) {
      createCookie(name,"",-1);
  }

  jQuery('.newsletterpopup-inner-wrapper #newsletter-validate-detail').submit( function(e) {

    createCookie('ppkcookie','testcookie',7);

  });

  jQuery('.thm-btn-close-popup').on('click', function (e) {
    jQuery(this).closest('.newsletterpopup').fadeOut(300);
      jQuery('.footer-container').removeClass('thm-overlay-screen-body');
      jQuery('body').removeClass('hide-scroll');
  });

  var x = readCookie('ppkcookie');
  var submitCookie = readCookie('afterSubmitCookie');
  if (x) {
    console.log('after submit');
      jQuery('.newsletterpopup').css({ display: 'none' });
      jQuery('.footer-container').removeClass('thm-overlay-screen-body');
      jQuery('body').removeClass('hide-scroll');

      if( !submitCookie ) {
      jQuery('.thm-generic-wrapper').empty();
      jQuery('<h2>Thanks, for Subscription!</h2><p>Your request has been received and information has been sent to your inbox.</p>').appendTo('.thm-generic-wrapper');
      jQuery('.newsletterpopup').css({ display: 'block' });
      jQuery('.footer-container').addClass('thm-overlay-screen-body');
      jQuery('body').addClass('hide-scroll');
    }

    createCookie('afterSubmitCookie','testcookie',7);

  } else {
    console.log('before submit');
    jQuery('.newsletterpopup').css({ display: 'block' });
      jQuery('.footer-container').addClass('thm-overlay-screen-body');
      jQuery('body').addClass('hide-scroll');
  }
  

});
</script>
 <?php echo $this->getChildHtml('footer_before') ?> 
 <?php echo $this->getChildHtml('footer') ?> 
 <?php echo $this->getChildHtml('global_cookie_notice') ?> 
 <?php echo $this->getChildHtml('before_body_end') ?> </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>