<!DOCTYPE html>
<?php
$siteBaseUrl = Mage::helper('function/more')->getBhishoomSiteBaseUrl(); 

?>
<!--[if lt IE 7 ]> <html lang="en" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" id="top" class="no-js">
<!--<![endif]-->

<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper"> <?php echo $this->getChildHtml('global_notices') ?>
  <div class="page"> <?php echo $this->getChildHtml('header') ?> <?php echo $this->getChildHtml('global_messages') ?>
    <div class="container">
      <div class="main-container col1-layout">
        <div class="main"> <?php echo $this->getChildHtml('breadcrumbs') ?>
          <div class="col-main">
            <?php 
	    $_categories = Mage::getModel('catalog/category')->getCategories(24);
    	$mainCat = Mage::getModel('catalog/category')->load(24)->getName();
		
		$query_string = $_SERVER['QUERY_STRING'];
		$case_style = Mage::app()->getRequest()->getParam('case_style');
		
		if($case_style!=''){

			$attributeDetails = Mage::getSingleton("eav/config")->getAttribute("catalog_product", 'case_style');
			$caseStyleoptionValue = $attributeDetails->getSource()->getOptionText($case_style);		
			$caseStyleHeadingtext = " For ".$caseStyleoptionValue;
			$queryStringParaString = "?".$query_string;
		}
		
	    echo '<div id="after-cr-design"><div class="col-sm-12"><h1 class="pick_device">Shop Now'.$caseStyleHeadingtext.'</h1>
          <h4>Choose from various premium quality merchandise and thousands of designs for each product to suit your style. You can even customize any of the design by adding text, images, artwork, vectors etc. though our <strong>babcover</strong> customizer.</h4></div></div>';
       ?>
            <?php 
    	$connection = Mage::helper('function/more')->getDbReadObject();
		$currentUrl = Mage::helper('core/url')->getCurrentUrl();
    	if(count($_categories)):
       ?>
            <div id="shop_pg_cate" class="shop-section">
              <div class="row">
                <?php $i=1; foreach ($_categories as $_category):?>
                <?php 
          if($_category->getIsActive())
		  {
          	$cur_category = Mage::getModel('catalog/category')->load($_category->getId());
          	$catName = $cur_category->getName();
			// echo $catName;
			$_imageUrl = $cur_category->getImageUrl();	 
          	if($_imageUrl == '')
            {
				$_imageUrl = $cur_category->getThumbnail();
			}
			else
            {?>
                <div class="col-md-6 col-md-offset-0 col-xs-10 col-xs-offset-1">
                  <div class="skin-toggle skinToggle<?=$i?> ">
                    <div class="img-skin mobileSkin"> <a href="<?php echo $cur_category->getUrl()?><?php echo $queryStringParaString?>" title="<?php echo $catName;?>"> <img alt="<?php echo $catName;?>" src="<?php echo $_imageUrl;?>"> </a>
                      <div class="skin-tab">
                        <?php
				     if ($catName == 'Laptop Skin'){
					    echo '<div class="" style="float:left;"><a href="'.$cur_category->getUrl().$queryStringParaString.'" title="'.$catName.'">'.$catName.'</a></div>';
					    ?>
                        <div class="" style="float:right;"><a href="<?php echo $siteBaseUrl.'shop/tablet-skin.html'.$queryStringParaString;?>" target="_blank" title="Tablet Skin">Tablet Skin</a></div>
                        <?php }
                     
					   else{
					  					   
				   ?>
                        <a href="<?php echo $cur_category->getUrl().$queryStringParaString?>" title="<?php echo $catName;?>">
                        <div class="skin-title"><?php echo $catName;?></div>
                        </a>
                        <?php
					   }
					?>
                      </div>
                    </div>
                    <div class="munu-categories mobile-menu">
                      <ul>
                        <?php		
                   $children = $cur_category->getChildren();
                   $c_counter = 1;   
				   $tabletFlag = false;		
                   foreach (explode(",",$children) as $category)
                   {
                       
					   $sub_cat = Mage::getModel('catalog/category')->load($category);
					    if ($catName == 'Laptop Skin'){
							
					    echo '<li class=""><a href="'.$sub_cat->getUrl().$queryStringParaString.'" title="'.$sub_cat->getName().'">'.$sub_cat->getName().'</a></li>';
					    
                           if($catName == 'Laptop Skin' && $c_counter == 4)
                           {
                               //echo '<li ><a href="'.$currentUrl.'/laptop-skin/custom-size.html/" title="Custom Size">Custom Size</a></li>';	
                           }						
						}
                        else{    			   
                         
						 echo '<li><a href="'.$sub_cat->getUrl().$queryStringParaString.'" title="'.$sub_cat->getName().'">'.$sub_cat->getName().'</a></li>';
                       }
					   
                       if($c_counter == 6)
                       {
                           
						   break; 
                       }
					   
					   
                       $c_counter++;	   
                   }		
                   ?>
                      </ul>
                      <?php
				   if($catName == 'Mobile Skin')
				   {
					   echo '<div class="see-over"><a href="'.$currentUrl.$queryStringParaString.'/mobile-skin.html" title="'.$catName.'">See Over 200 Models</a></div>';	
				   }
				   if($catName == 'Mobile Case')
				   {
					   echo '<div class="see-over"><a href="'.$currentUrl.$queryStringParaString.'/mobile-case.html" title="'.$catName.'">See Over 100 Models</a></div>';	
				   }
				   if ($catName == 'Laptop Skin')
				   {
					   if($tabletFlag == false)
						   {
						   ?>
                      <div class="brandNameSkin">
                        <ul>
                          <li><a href="<?php echo $siteBaseUrl.'shop/tablet-skin/apple.html'.$queryStringParaString;?>" target="_blank" title="Apple">Apple</a></li>
                          <li><a href="<?php echo $siteBaseUrl.'shop/tablet-skin/samsung.html'.$queryStringParaString;?>" target="_blank" title="Samsung">Samsung</a><br>
                          </li>
                          <li><a href="<?php echo $siteBaseUrl.'shop/tablet-skin/all-tabs.html'.$queryStringParaString;?>" target="_blank" title="All other tab">All other tab</a><br>
                          </li>
                          <?php
						    $_category = Mage::getModel('catalog/category')->load(1144);
							$namee  = $_category->getName();
							$urll  = $_category->getUrl();
						  ?>
						  
						  <li><a href="<?php echo $urll.$queryStringParaString; ?> " target="_blank" title="Custom Size"><?php echo $namee;?></a></li>
                        </ul>
                      </div>
                      <?php  
						  $tabletFlag = true;
						   }
				   }
				   ?>
                    </div>
                  </div>
                </div>
                <?php } }?>
                <?php $i++;endforeach ?>
              </div>
            </div>
            <?php endif; ?>
          </div>
        </div>
      </div>
    </div>
    <?php echo $this->getChildHtml('footer_before') ?> <?php echo $this->getChildHtml('footer') ?> <?php echo $this->getChildHtml('global_cookie_notice') ?> <?php echo $this->getChildHtml('before_body_end') ?> </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
