<?php
	$displayOrderTable=Mage::getStoreConfig('tab1/order_information_system/display_order_table');
	$displayProductImage=Mage::getStoreConfig('tab1/order_information_system/display_product_image');
	$displayDiscount=Mage::getStoreConfig('tab1/order_information_system/display_discount');
	$displayShippingRate=Mage::getStoreConfig('tab1/order_information_system/display_shipping_rates');
	$displayTax=Mage::getStoreConfig('tab1/order_information_system/display_tax');
	$displayCmsBlockAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_above');
	$cmsBlockIdAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_above');
	$displayCmsBlockBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_below');
	$cmsBlockIdBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_below');
	$newsLetter=Mage::getStoreConfig('tab1/newsletter_subscription_section/display_section');
?>
<?php
	$_coreHelper = $this->helper('core');
?>
<?php
	$displayOrderTable=Mage::getStoreConfig('tab1/order_information_system/display_order_table');
	$displayProductImage=Mage::getStoreConfig('tab1/order_information_system/display_product_image');
	$displayDiscount=Mage::getStoreConfig('tab1/order_information_system/display_discount');
	$displayShippingRate=Mage::getStoreConfig('tab1/order_information_system/display_shipping_rates');
	$displayTax=Mage::getStoreConfig('tab1/order_information_system/display_tax');
	$displayCmsBlockAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_above');
	$cmsBlockIdAbove=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_above');
	$displayCmsBlockBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_below');
	$cmsBlockIdBelow=Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_below');
	$newsLetter=Mage::getStoreConfig('tab1/newsletter_subscription_section/display_section');
?>
<?php
	$_coreHelper = $this->helper('core');
?>

<div class="thanks-outer" id="thanks-order-page">
<?php if($this->getTopBlock()!=false): ?>
<?php if($displayCmsBlockAbove==1): ?>
<div class="order-cms-block block1">
  <?php
			echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getTopBlock())->toHTML();
		?>
</div>
<?php
		 endif;
	endif;
?>
<div class="thanks-inner">
<div class="page-title thank">
  <h1><?php echo $this->__('Thank you for your order!') ?></h1>
</div>
<?php
		echo $this->getMessagesBlock()->getGroupedHtml() 
?>
<div class="thanks-msz">
  <h3>We will dispatch your order shortly !</h3>
  <p>A confirmation email has been sent to <a href="#">abcdefg@gmail.com</a></p>
</div>
<div class="thkbox">
<?php /*?><div class="thk-box1">
        <div class="outer-box">
          <h3><?php echo $this->__('Thank you for your order!') ?></h3>
          <div class="inner-box-1">
            <?php if($this->getOrderId()): ?>
            <?php if($this->getCanViewOrder()): ?>
            <?php  else: ?>
            <?php endif; ?>
            <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
            <?php if($this->getCanViewOrder() && $this->getCanPrintOrder()): ?>
            <?php echo $this->getChildHtml() ?>
            <?php endif; ?>
            <?php endif; ?>
            <a class="button btn-continue btn-inline" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>" title="<?php echo $this->__('Continue Shopping') ?>" ><span><span><?php echo $this->__('Continue Shopping') ?></span></span></a> </div>
        </div>
      </div><?php */?>
      <div class="section-title-big"><h2><?php echo $this->__('Order Summary') ?></h2	></div>
<div class="row">
<div class="col-sm-12"><div class="section-title"><h3><?php echo $this->__('Shipping Address') ?></h3></div></div>
<div class="clearfix"></div>
<div class="col-sm-6">
 

<div class="inner-box-1">
<table class="table">
<?php
		if($this->getOrderId()):
			$orderObj = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
			$lastOrder = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId());
			$billingAddress = $lastOrder->getBillingAddress();
			$shippingAddress = $lastOrder->getShippingAddress();
			?>
<tr>
  <td  >
<h3>    <?php 
				$shippingAddress; 
				echo $shippingAddress['firstname']; 
			?>
    <?php echo $shippingAddress['lastname']; ?> </h3></td>
</tr>
<tr>
<tr>
  
  <td ><?php echo $shippingAddress['street']; ?>, 
 <?php echo $shippingAddress['city']; ?>, <?php echo $shippingAddress['region']; ?>
</tr>
<tr>
  <td  >PIN - <?php echo $shippingAddress['postcode']; ?>, Country - <?php echo $shippingAddress['country_id']; ?> </td>
</tr>

<?php endif; ?>
</table>
</div>
 
</div>
<div class="col-sm-6">
    
    <div class="inner-box-1 order-table">
      <?php /*?><?php if($this->getOrderId()): ?>
            <?php echo $this->__('<a href="%s" onclick="this.target=\'_blank\'" class="button print-icon" title="Print Details">Print Details</a>', $this->getPrintUrl()) ?> <?php echo $this->getChildHtml() ?>
            <?php endif; ?><?php */?>
      <?php //******************************Order Summary *********************** ?>
      <table class="table">
        <?php
				if($this->getOrderId()):
					$orderObj = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
					$lastOrder = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId());
					$billingAddress = $lastOrder->getBillingAddress();
					$shippingAddress = $lastOrder->getShippingAddress();
					?>
        <tr >
          <td><label><?php echo $this->__('Date') ?></label></td>
          <td><span class="sep">:</span></td>
          <td align="left"><span><?php echo $orderObj->getCreatedAtStoreDate(); ?></span></td>
        </tr>
        <tr>
          <td><label><?php echo $this->__('Order Number') ?></label></td>
          <td><span class="sep">:</span></td>
          <td align="left"><span>
            <?php if($this->getCanViewOrder()): ?>
            <?php echo $this->__(sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?>
            <?php else: ?>
            <?php echo $this->__($this->escapeHtml($this->getOrderId())) ?>
            <?php endif; ?>
            <?php echo $this->getChildHtml() ?> </span></td>
        </tr>
        <tr>
          <td><label><?php echo $this->__('Order Total') ?></label></td>
          <td><span class="sep">:</span></td>
          <td align="left"><span><?php echo $_coreHelper->formatPrice($orderObj->getGrandTotal(),true) ?></span></td>
        </tr>
        <?php endif; ?>
      </table>
    </div>
  
</div>
</div>
<div class="clear"></div>
<?php /*?><?php if($this->getOrderId()): ?>
      <?php echo $this->__('<a href="%s" onclick="this.target=\'_blank\'" class="btn btn-danger" title="Print Details">Print Details</a>', $this->getPrintUrl()) ?> <?php echo $this->getChildHtml() ?>
      <?php endif; ?>
      <div class="clear"></div><?php */?>
</div>
<?php	
//**********************************Order Details***************************
if($displayOrderTable==1):
	if($this->getOrderId()):
		$orderItems = $orderObj->getAllVisibleItems();
		?>
<div class="row">

  <div class="col-sm-6">
  <div class="section-title text-danger"><h3><?php echo $this->__('Item Details') ?></h3></div>
    <?php foreach($orderItems as $items)
		{
			$_product = Mage::getModel('catalog/product')->load($items->getProductId());
			$product_small_image_path = Mage::helper('catalog/image')->init($_product,'small_image')->resize(75);
		?>
    <table class="table">
      <tr>
        <td colspan="2" ><?php if($displayProductImage==1): ?>
          <?php /*?><span class="product-image-success"> <img src="<?php echo $product_small_image_path ?>" align="<?php echo $items->getName(); ?>"/> </span><?php */?>
          <?php endif; ?>
          <div class="product-name"> <?php echo $items->getName(); ?> </div></td>
      </tr>
      <tr>
        <td class="qty-item"><?php echo number_format($items->getQtyOrdered(),0); ?> <span class="xx">x</span> <?php echo $_coreHelper->formatPrice($items->getPrice(),true) ?>  = 
        <?php $totalprice = ($items->getQtyOrdered())*($items->getPrice()); ?>
         <span class="alt-bg"><?php echo $_coreHelper->formatPrice($totalprice,true) ?></span></td>
      </tr>
    </table>
    <?php
						} 
					?>
  </div>
  <div class="col-sm-6">
  <div class="section-title text-danger text-right"><h3><?php echo $this->__('Sub Total') ?></h3></div>
    <table class="table">
      <tr>
        <td width="100%" class="a-right" ><span ><?php echo $this->__('Subtotal') ?></span></td>
        <td class="a-left"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getSubtotal(),true) ?> </span></td>
      </tr>
      <?php //echo '<pre>'; print_r($orderObj); echo '</pre>'; ?>
      <?php if($displayDiscount==1): ?>
      <?php if($orderObj->getDiscountAmount() != 0): ?>
      <tr class="discount">
        <td class="a-right"  ><?php echo $this->__('Discount').'('.$orderObj->getDiscountDescription().')' ?></td>
        <td class="last a-left"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getDiscountAmount(),true) ?> </span></td>
      </tr>
      <?php 
							endif; 
						endif; 
					?>
      <?php if($displayShippingRate==1): ?>
      <tr class="shipping">
        <td class="a-right"  ><?php echo $this->__('Shipping & Handling('.$orderObj->getShippingDescription().')'); ?></td>
        <td class="last a-left"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getShippingInclTax(),true) ?> </span></td>
      </tr>
      <?php 
						endif; 
					?>
      <?php if($displayTax==1): ?>
      <?php if($orderObj->getTaxAmount() != 0): ?>
      <tr class="tax">
        <td class="a-right"  ><?php echo $this->__('Tax')?></td>
        <td class="last a-left"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getTaxAmount(),true) ?> </span></td>
      </tr>
      <?php 
							endif;
						endif;
					?>
      <tr class="grand_total ">
        <td class="a-right"  ><?php echo $this->__('Total') ?></td>
        <td class="last a-left"><span class="subtotlal-value"> <?php echo $_coreHelper->formatPrice($orderObj->getGrandTotal(),true); ?></span></td>
      </tr>
    </table>
  </div>
</div>
<?php endif; 
endif;
?>
</div>
<?php if($this->getBottomBlock()!=false): ?>
<?php if($displayCmsBlockBelow==1): ?>
<div class="order-cms-block block_2"> <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getBottomBlock())->toHTML(); ?> </div>
<?php
	endif;
endif;
?>
<?php if($newsLetter==1): ?>
<div class="order-newsletter"> <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?> </div>
<?php 
	endif;
?>
</div>
