<?php
/**
* PHXSolution Mergeinfo
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@magentocommerce.com so you can be sent a copy immediately.
*
* Original code copyright (c) 2008 Irubin Consulting Inc. DBA Varien
*
* @category   design
* @package    Phxsolution_Mergeinfo
* @author     Prakash Vaniya
* @contact    contact@phxsolution.com
* @site       www.phxsolution.com
* @copyright  Copyright (c) 2014 PHXSolution Mergeinfo
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

$checkLoggedIn = Mage::helper('function')->checkCustomerLoggedIn();
?>

<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<!-- New Code Added Below  -->
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/mergeinfocheckout.js') ?>"></script>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<ol class="opc" id="checkoutSteps">
<?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
<?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++; 
if($checkLoggedIn){
if($i==1)
	$className='step-title_1_0';
elseif($i==2)
	$className='step-title_2_50';	
}
else{
if($i==1)
	$className='step-title_1_0';
elseif($i==2)
	$className='step-title_2_33';
elseif($i==3)
	$className='step-title_3_66';
}	
?>

        <div <?php if($_stepId=='payment') echo 'id="paymentDiv"';?> onclick="javascript:eleClickEvent('<?php echo $_stepId ?>','<?php echo $className ?>')" class="step-title <?php echo $className?> <?php if($i==1){?>thisActive<?php }?>" <?php if($checkLoggedIn)echo 'style="width:50%;"';?>>
            <span class="number"><?php echo $i ?></span>
            <h2><?php echo $_stepInfo['label'] ?></h2>
            <a href="#" class="displayNone"><?php echo $this->__('Edit') ?></a>
        </div>	
	


    <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>" <?php if($checkLoggedIn) echo 'style="min-width:100%"';?>>
	

        <div class="mycustomEle thisEle<?php echo $_stepId ?> <?php echo $className?> displayNone" <?php if($checkLoggedIn)echo 'style="width:50%;"';?>>
            <span class="number"><?php echo $i ?></span>
            <h2><?php echo $_stepInfo['label'] ?></h2>
            <a href="#" class="displayNone"><?php echo $this->__('Edit') ?></a>
        </div>	

       
		
		
        <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
            <?php echo $this->getChildHtml($_stepId) ?>
        </div>
    </li>
<?php endforeach ?>
</ol>
<script type="text/javascript">
//<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.mycustomEle', false);
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    //New Code Added Below
    var checkout = new Phxsolution(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
	
	
	function eleClickEvent(eleid,classname){
		jQuery('.thisEle'+eleid).click();
		
		
		jQuery( "#checkoutSteps .step-title" ).removeClass("thisActive");
	
		jQuery( "."+classname ).addClass("thisActive");		
		
	}
	
//]]>
</script>
