<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-1.9.0.min.js');?>"></script>
<div class="content-header">
 <table cellspacing="0" class="grid-header">
  <tr>
   <td width="25%" height="35"><h3><?php echo $this->__('Home Featured Product')?></h3></td>
   <td class="a-right">
    <button onclick="cat_hide_div()" class="scalable back" id="back" type="button" style="display:none; float:right;"><span>Back</span></button>
    <button onclick="img_show_div()" class="scalable add" id="add_item" type="button" style="float:right;"><span>Add New Item</span></button>
   </td>
   <td>
    <div id="loadingmask" style="display: none;">
	 <div class="loader" id="loading-mask-loader">
      <img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif');?>" alt="<?php echo $this->__('Loading...') ?>"/></div>
	 <div id="loading-mask"></div>
	</div>
   </td>
  </tr>
 </table>
</div>
<div class="grid" id="display-cat">
 <form id="drop" name="drop" method="post" action="<?php echo $this->getUrl('*/*/post')?>" onsubmit="return drop_validate()" enctype="multipart/form-data">
  <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
  <table cellspacing="0" class="form-list">
   <thead>
    <tr class="headings">
     <th width="10%">Type</th>
     <th>Name</th>
     <th>Image</th>
     <th>Link</th>
     <th>Action</th>
    </tr>
   </thead>
   <tbody>
   <?php     
   $connection = Mage::getSingleton('core/resource')->getConnection('core_read');
   $qry = 'SELECT * FROM `featuredproduct` WHERE active = 1';
   $rowsArray = $connection->fetchAll($qry); 
   foreach($rowsArray as $rowsArray1)
   {
	   $fid = $rowsArray1['fid'];
	   $cat_id = $rowsArray1['cat_id'];
	   $category = Mage::getModel('catalog/category')->load($cat_id);
	   $cat_name = $category->getName();
	   ?> 
      <tr> 
       <td><?php echo $cat_name;?></td>      
       <td><?php echo $rowsArray1['prod_name'];?></td>
       <td><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'home_banner_img/'.$rowsArray1['prod_img'];?>" width="20" /></td> 
       <td><?php echo $rowsArray1['prod_link'];?></td> 
       <td><a href="<?php echo $this->getUrl('*/adminhtml_edit/index/fid/'.$fid)?>">Edit</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" onclick="return del('<?php echo $fid;?>')">Delete</a></td>
      </tr>    
    <?php } ?>
   </tbody> 
  </table> 
 </form>
</div>

<div class="grid" id="add-item" style="display:none;">
 <form id="add_form" name="add_form" method="post" action="<?php echo $this->getUrl('*/*/bpost')?>" enctype="multipart/form-data" onsubmit="return validate()">
  <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
   <div class="entry-edit">
    <div class="entry-edit-head">
	 <h4 class="icon-head head-edit-form fieldset-legend">Add Item</h4>
    </div> 
	<div id="responsivebannerslider_form" class="fieldset ">
     <table cellspacing="0" class="form-list">
      <tbody>
       <tr>
        <td class="label">Select Type</td>
        <td class="value">
         <select name="type_id" id="type_id">
          <option value="0">Please Select Type</option>
          <option value="3">Mobile Case</option>
          <option value="34">Mobile Skin</option>
          <option value="8">Laptop Skin</option>
          <option value="4">T-Shirt</option>
         </select> 
        </td>     
       </tr> 
       <tr>
        <td class="label">Enter Product Name</td>
        <td class="value">
          <input type="text" name="pname" id="pname" value="" class="input-text" />
        </td>     
       </tr> 
       <tr>
        <td class="label">Enter Product Link</td>
        <td class="value">
          <input type="text" name="plink" id="plink" value="" class="input-text"  />
        </td>     
       </tr>
       <tr>
        <td class="label">Enter Product Image</td>
        <td class="value">
          <input type="file" name="pimage" id="pimage" value="" class="input-text" />
        </td>     
       </tr>  
       <tr>
        <td class="label"></td>
        <td class="value"><input type="submit" value="Submit" class="pure-button pure-button-primary"></td>     
       </tr> 
      </tbody> 
     </table> 
	</div>
   </div> 
 </form>
</div>

<script type="text/javascript">
function img_show_div()
{
	if(document.getElementById("add-item").style.display == 'none')
	{
		document.getElementById("add-item").style.display = 'block';
		document.getElementById("back").style.display = 'block';	
		document.getElementById("display-cat").style.display = 'none';
	}
}
function cat_hide_div()
{
	if(document.getElementById("display-cat").style.display == 'none')
	{
		document.getElementById("display-cat").style.display = 'block';
		document.getElementById("add-item").style.display = 'none';	
		document.getElementById("back").style.display = 'none';				
	}
}
function show_cng_div(val)
{
	if(document.getElementById("cng_div_"+val).style.display == 'none')
	{
		document.getElementById("cng_div_"+val).style.display = 'block'
	}
	else
	{
		document.getElementById("cng_div_"+val).style.display = 'none'
	}
}
function del_cat(id)
{
	alert(id);
	//document.getElementById("drop_id").value = id;
	document.getElementById("del_cat").value = '1';
	document.getElementById("drop").submit();
}

function validate()
{
	if(document.getElementById("type_id").value == 0)
	{
		alert("Please Select Type");
		return false;
	}
	if(document.getElementById("pname").value == '')
	{
		alert("Please Enter Product Name");
		return false;
	}
	if(document.getElementById("plink").value == '')
	{
		alert("Please Enter Product Link");
		return false;
	}
	if(document.getElementById("pimage").value == '')
	{
		alert("Please Upload Image");
		return false;
	}
	return true;
}
function del(fid)
{
	var con = confirm("Are you sure you want to delete this.");
	if(con == true)
	{
		window.location = "<?php echo $this->getUrl('*/edit/fid/')?>";
		var dataString = "featured_id="+fid;
	    var reloadurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'admin_cat.php'?>';
		//Element.show('loadingmask');
		new Ajax.Request(reloadurl, {
		method: 'post',
		parameters: dataString,
		onComplete: function(transport) {
			window.location = "<?php echo $this->getUrl('*/adminhtml_fproductform/')?>";
		}
		});
	}
}
</script>