<?php
/**
 * Unirgy_Giftcert extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Unirgy
 * @package    Unirgy_Giftcert
 * @copyright  Copyright (c) 2008 Unirgy LLC
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @category   Unirgy
 * @package    Unirgy_Giftcert
 * @author     Boris (Moshe) Gurevich <moshe@unirgy.com>
 */
?>
<?php $_usePin = Mage::getStoreConfig('ugiftcert/default/use_pin'); ?>

<div class="my-account">
<div class="page-title">
  <div class="enter-gift-card-number">
    <div class="top-facade"></div>
    <div class="content">
      <form action="<?php echo $this->getUrl('ugiftcert/customer/balance')?>" method="post" id="form-validate">
        <div class="row">
          <div class=" col-sm-8 col-sm-offset-2">
            <fieldset>
              <ul class="form-list">
                <li>
                  <div class="field row" >
                    <label class="col-sm-4" for="cert_number"><?php echo $this->__('Card Number')?></label>
                    <div class="col-sm-8 input-field">
                      <input type="text" class="input-text required-entry"  id="cert_number" name="cert_number"/>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                  <?php if (Mage::getStoreConfig('ugiftcert/default/use_pin')): ?>
                  <div class="field row" >
                    <label class="col-sm-4" for="pin"><?php echo $this->__('Pin')?></label>
                    <div class="col-sm-8 input-field">
                      <input type="text" class="input-text required-entry" id="pin" name="pin"/>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                  <?php endif; ?>
                </li>
                <li>
                  <div class="field row">
                    <div class="col-sm-8 col-sm-offset-4">
                      <button class="button btn-block" title="Check Balance" type="submit"><span><span>Check Balance</span></span></button>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                </li>
              </ul>
              <div class="clearfix"></div>
            </fieldset>
          </div>
        </div>
      </form>
    </div>
    <div class="bottom-facade"></div>
  </div>
 </div></div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);   
//]]>
</script>
<?php if ($this->getRequest()->isPost()): ?>
<div class="retrieve-gift-card-balance">
  <?php if (is_null($this->getCert())): ?>
  <p><?php echo $this->__($_usePin ? 'Please enter a valid card number and PIN.' : 'Please enter a valid card number.')?></p>
  <?php elseif ($this->getCert()===false): ?>
  <p><?php echo $this->__($_usePin ? 'The card number or PIN entered are invalid. Please retry' : 'The card number entered is invalid. Please retry')?></p>
  <?php elseif ($this->getCert()): ?>
  <h4><?php echo $this->__('Your Gift Card Balance')?></h4>
  <p><strong><?php echo $this->__('Card Number')?></strong><br/>
    <?php echo $this->getCertNumberMasked() ?></p>
  <p><strong><?php echo $this->__('Balance')?></strong><br/>
    <big class="balance"><?php echo $this->getBalance() ?></big></p>
  <?php if ($exp = $this->getCert()->getExpireAt()): ?>
  <p><strong><?php echo $this->__('Expires On')?></strong><br/>
    <?php echo $this->helper('ugiftcert')->formatDate($exp, 'long') ?></p>
  <?php endif; ?>
  <?php endif; ?>
</div>
<?php endif; ?>
