<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use/
 * @version      Release: 1.0.0
 * @since        Available since Release 1.0.0
 */
?>
<div id="customer-login-container" style="display: none">
<link rel="stylesheet" type="text/css" href="http://www.bhishoom.com/skin/frontend/rwd/default/quicklogin/quicklogin.css">
	

<div id="quicklogin">
<div class="quickbg" >
<div class="row" > 
  
    <ul class="messages" style="display: none">
        <li class="error-msg" id="login-error-msg">
            <ul>
            </ul>
        </li>
    </ul>   
  
    <!-- <div class="page-title">
	    <h2><?php //echo $this->__('Login or Create an Account') ?></h2>
	</div> -->
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<div class="col-sm-6 rightBorderLoginBox">
	    <fieldset class="col2-set login-page">
		<?php /*?><legend><?php echo $this->__('Login or Create an Account') ?></legend><?php */?>
		
		<div class="col-2 registered-users" id="old_user">
		   <form action="#" method="post" id="login-form" class="frm-login">
		    <div class="content">
			<h3><?php echo $this->__('Sign-in') ?></h3>
			<p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
			<ul class="form-list">
			    <li>
				<label for="email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
				<input name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" type="text" class="input-text required-entry" title="<?php echo $this->__('Email Address') ?>" />
			    </li>
                <div class="clear"></div>
			    <li>
				<label for="pass"><?php echo $this->__('Password') ?> <span class="required">*</span></label><br />
				<input name="login[password]" type="password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
			    </li>
			</ul>
			<p class="required"><?php echo $this->__('* Required Fields') ?></p>
		    </div>
		    <div class="buttons-set">
			<div class="fpasscheck">
             <div class="log-but">
              <button class="action-btn" type="button" name="send"  id="customer-login-btn"><?php echo $this->__('Login') ?></button>
             </div>
             <div class="clearfix"></div>
             <div class="for_pass">
			  <input type="checkbox" name="modtype" value="value1" onclick="showForgotSection('fpass', this)" />
			  <span><?php echo $this->__('Forgot Your Password?') ?></span></div>
			</div>		
		    </div>           
            <div class="new_user_text">New around here? <a href="javascript:void(0)" id="customer-register-btn" style="cursor:pointer; text-decoration:underline;">Register </a> now.</div>
		    </form>
			<div style="display:none;position: absolute;bottom:40px;" id="fpass">
              <form class="for-pass" id="forgot-form" method="post" action="<?php echo $this->getUrl('customer/account/ajaxForgotPassword/') ?>">
              <p><?php echo $this->__('Please enter your email to get the password') ?></p>
              <ul class="form-list">
                  <li>
                      <label class="required" for="email"><em>*</em><?php echo $this->__('Email Address') ?></label>
                      <div class="input-box">
                          <input type="text" title="Email Address" class="input-text required-entry validate-email" id="forgot_email" value="" name="forgotemail">
                          <div style="display:none;" id="advice-required-entry-forgetemail" class="validation-advice"></div>
                      </div>
                  </li>
                
              </ul>
              <div style="border:0px;" class="col-2 registered-users">
                  <div class="buttons-set">
      
          		<button type="button" id="send3" name="send3" class="action-btn" onclick="return forgetpass();"><span><?php echo $this->__('Submit') ?></span></button>
                       <p style="display:none;" id="loading"></p> 
                  </div>
               </div>
             
              </form>
              </div>
		</div>
  
  
		
		</fieldset>
	
	</div>
 
		<?php 
/**
 * GoMage Social Connector Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.0
 * @since        Class available since Release 1.0
 */ 
?>
<?php 	$services = Mage::helper('gomage_social')->getServices('login');	?>
<?php if (count($services)): ?> 
	<ul class="col-sm-6 gs-login <?php if(Mage::getConfig()->getModuleConfig('Enterprise_Enterprise' )): ?>gs-login-ee<?php endif; ?> gs-login-<?php echo $this->getPlace() ?>">
		<?php 
			end($services);
			$last_key = key($services);
		?>
		<?php foreach ($services as $key => $value): ?>
		
<?php switch ($key): ?>
<?php case (GoMage_Social_Model_Type::FACEBOOK): ?>
 <li <?php if ($key == $last_key): ?>class="last"<?php endif; ?>>
  <?php if ($this->getLoginType('facebook') == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::BUTTON): ?>			
	<fb:login-button scope="email" onlogin="gomageSocialFBCheckLogin()" v="2"></fb:login-button>
  <?php else: ?>
	<a href="#" onclick="gomageSocialFBLogin();return false;" title="<?php echo $this->getText('facebook') ?>">
     <?php if (($image = $this->getImage('facebook')) && ($this->getLoginType('facebook') == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::IMAGE)): ?>
	 <img src="<?php echo $image ?>" alt="<?php echo $this->getText('facebook') ?>" />
    <?php else: ?>
	 <?php /*?><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/fb_login.png" alt="Login with facebook" title="Login with facebook" /><?php */?>
     <div class="social_login"><i class="fa fa-facebook"></i><span>You can Login with facebook</span></div>
    <?php endif; ?>
   </a>
  <?php endif; ?>
 </li> 
<?php break; ?>
<?php case (GoMage_Social_Model_Type::GOOGLE): ?>
	<li <?php if ($key == $last_key): ?>class="last"<?php endif; ?>>
		<?php if ($this->getLoginType('google') == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::BUTTON): ?>
			<button class="g-signin"
		        data-scope="https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"
		        data-requestvisibleactions="http://schemas.google.com/AddActivity"
		        data-clientId="<?php echo Mage::getStoreConfig('gomage_social/google/id') ?>"
		        data-accesstype="offline"
		        data-callback="gomageSocialGSigninCallback"        
				data-approvalprompt="force"		
		        data-cookiepolicy="single_host_origin"
		        data-height="short">
		    </button>
		<?php else: ?>
			<a href="<?php echo $this->getUrl('gomage_social/google/login', array('_secure' => true, 'gs_url' => Mage::helper('core')->urlEncode(Mage::helper('core/url')->getCurrentUrl())));  ?>" title="<?php echo $this->getText('google') ?>">
				<?php if (($image = $this->getImage('google')) && ($this->getLoginType('google') == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::IMAGE)): ?>
					<img src="<?php echo $image ?>" alt="<?php echo $this->getText('google') ?>" />
				<?php else: ?>
					<?php echo $this->getText('google') ?>
				<?php endif; ?>
			</a>
		<?php endif; ?>
	</li>	
<?php break; ?>
<?php case (GoMage_Social_Model_Type::LINKEDIN): ?>	
	<li <?php if ($key == $last_key): ?>class="last"<?php endif; ?>>
		<a href="<?php echo $this->getUrl('gomage_social/linkedin/login', array('_secure' => true, 'gs_url' => Mage::helper('core')->urlEncode(Mage::helper('core/url')->getCurrentUrl())));  ?>" title="<?php echo $this->getText('linkedin') ?>">
			<?php if (($image = $this->getImage('linkedin')) && ($this->getLoginType('linkedin') == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::IMAGE)): ?>
				<img src="<?php echo $image ?>" alt="<?php echo $this->getText('linkedin') ?>" />
			<?php else: ?>
				<?php echo $this->getText('linkedin') ?>
			<?php endif; ?>
		</a>
	</li>
<?php break; ?>
<?php endswitch; ?>
				
		<?php endforeach; ?>
	</ul>
	 
<?php endif; ?>
	<script type="text/javascript">
	//<![CDATA[
	     // var dataForm = new VarienForm('login-form', true);
	      //var dataForm1 = new VarienForm('regis-form', true);
	//]]>	

	
	</script>
    <div class="clearfix"></div>
	</div>	
</div>
	
	
<?php /*?>    <form method="post" id="login-form">
        <div class="col-2 registered-users">
            <div class="content">
                <h2><?php echo $this->__('Registered Customers') ?></h2>
                <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                <ul class="form-list">
                    <li>
                        <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                        </div>
                    </li>
                </ul>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            </div>
        </div>
        <div class="col-2 registered-users">
            <div class="buttons-set">
                <button type="button" class="button" title="<?php echo $this->__('Login') ?>" id="customer-login-btn"><span><span><?php echo $this->__('Login') ?></span></span></button>
                <button type="button" id="customer-register-btn" title="<?php echo $this->__('Create an Account') ?>" class="button"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
            </div>
        </div>
    </form>
<?php */?>
	</div>
    
</div>
