<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use/
 * @version      Release: 1.0.0
 * @since        Available since Release 1.0.0
 */
?>
<?php $licenseEnabled =  $this->licenseAgreementsEnabled() && $this->getLicenceAgreementsText(); ?>
<div>
    <div id="uploadedImages" class="displayNone">
        <?php echo $this->getChildHtml('uploadedImages'); ?>      
    </div>
   
    <?php if ($licenseEnabled):?>
    <ul class="form-list">
      <li class="control control-rights">
        <input type="checkbox" class="checkbox" name="licence_agreements" id="licence_agreements" />
        <label for="licence_agreements"><?php echo $this->__('I have the rights to use these images') ?></label>
      </li>
    </ul>
    <div class="pd_more_info_link">
        <a href="javascript:;" id="license-agreements-link"><?php echo $this->__('More info') ?></a>
        <div id="license-agreemants" class="pd-license-agreements-popup" style="display: none">
            <?php echo $this->getLicenceAgreementsText(); ?>
        </div>
    </div>
    <?php endif;?>
</div>
<div id="file-input-box" <?php echo $licenseEnabled ? 'style="display:none;"' : ''?>>
    <form target="iframeSave" id="uploadImages" enctype="multipart/form-data" action="<?php echo Mage::getUrl('designer/index/uploadImages'); ?>" method="post">
	
		<div id="ajax-loader2" class="displayNone">	
		 <?php /*?><i class="fa-li fa-lg fa fa-spinner fa-spin"></i> Processing...<?php */?>
		 
			<div class="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all">
				<div class="bar"></div >
				<div class="percent">0%</div >
			</div>
		 
		</div>
        <div class="pd-upload-input displayNone">
          <input name="filesToUpload[]" id="filesToUpload" type="file" <?php /*?>multiple="multiple"<?php */?> accept="<?php echo $this->getAllowedImageMimeTypesString(); ?>"/>
        </div>
		
        <input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $this->getMaxUploadFileSize();?>" />
         <div class="pd-upload-buttons" style="display:none">
          <button class="button" type="submit" id="gra_upload_image"><span><span><?php echo $this->__('Upload'); ?></span></span></button>
          <button class="button" id="remove-img-btn" type="button" <?php if (!$this->hasImages()):?>style="display: none"<?php endif;?>><span><span><?php echo $this->__('Remove Images'); ?></span></span></button>        
        </div>
        <iframe id="iframeSave" name="iframeSave" style="display:none;"></iframe>
    </form>
	
<script type="text/javascript">

document.getElementById("filesToUpload").onchange = function() {
    //document.getElementById("gra_upload_image").click();
	jQuery('.UploadPhotoDivCustomizer').hide();
	generateClickEvents('gra_upload_image')
	
	jQuery("#ajax-loader2").removeClass("displayNone");
	jQuery("#ajax-loader2").addClass("displayBlock");
};

var bar = jQuery('.bar');
//var percent = jQuery('.percent');
//var status = jQuery('#status');

jQuery('#uploadImages').ajaxForm({ 
    beforeSend: function() {
        status.empty();
        var percentVal = '0%';
        bar.width(percentVal)
        //percent.html(percentVal);
    },
    uploadProgress: function(event, position, total, percentComplete) {
	
        var percentVal = percentComplete + '%';
        bar.width(percentVal)
        //percent.html(percentVal);
    },
    complete: function(xhr) {
	
    bar.width("100%");
    //percent.html("100%");
		 
	if(xhr.responseText.indexOf("1337") > 0){	 
	data = JSON.parse(xhr.responseText);
	if(data.status=='error'){
		alert(data.message)
	}
	}
	else{
		
		jQueryUploadedImageIframeRespVar = xhr.responseText
	objCallDirectDesignerImage.observeUploadImageIframe();
	}
	
						jQuery("#ajax-loader2").addClass("displayNone");
					jQuery("#ajax-loader2").removeClass("displayBlock");

        //status.html(xhr.responseText);
    }
}); 	
</script>	
	
    <?php if ($this->imageConditionsEnabled() && $text = $this->getImageConditionsText()): ?>
        <div id="image-conditions">
            <?php echo $text; ?>
        </div>
    <?php endif;?>
</div>
<script type="text/javascript">
    document.observe('dom:loaded', function(e){
        var imagesUploader = new GoMage.ImageUploader(
            '<?php echo $this->getMaxUploadFileSize();?>',
            '<?php echo $this->getAllowedImageMimeTypesJson()?>',
            '<?php echo $this->getAllowedImageExtensions();?>',
            '<?php echo $this->getRemoveImgUrl();?>'
        );
    }.bind(this));
</script>